package lirproto

import "testing"

func TestRenderSimpleModuleIsDeterministic(t *testing.T) {
	i32 := IntType(32)
	i64 := IntType(64)
	ptr := PtrType()
	void := VoidType()

	var decls RuntimeDecls
	if !decls.Declare(RuntimeDecl{Symbol: "printf", Return: i32, Params: []Type{ptr}, Vararg: true}) {
		t.Fatal("first printf declaration was not accepted")
	}
	if decls.Declare(RuntimeDecl{Symbol: "printf", Return: i32, Params: []Type{ptr}, Vararg: true}) {
		t.Fatal("duplicate printf declaration was accepted")
	}
	if !decls.Declare(RuntimeDecl{Symbol: "osty_rt_ping", Return: void}) {
		t.Fatal("runtime declaration was not accepted")
	}

	var pool StringPool
	if got, want := pool.Intern("hello\n"), "@.str.0"; got != want {
		t.Fatalf("first string symbol = %q, want %q", got, want)
	}
	if got, want := pool.Intern("hello\n"), "@.str.0"; got != want {
		t.Fatalf("duplicate string symbol = %q, want %q", got, want)
	}
	if got, want := pool.Intern(`quote " slash \`), "@.str.1"; got != want {
		t.Fatalf("second string symbol = %q, want %q", got, want)
	}

	mod := Module{
		SourcePath: "/tmp/main.osty",
		Target:     "x86_64-unknown-linux-gnu",
		TypeDefs: []TypeDef{
			{Name: "%Pair", Body: "{ i64, ptr }"},
		},
		Globals: []Global{
			{Name: "@counter", Type: i64, Init: "0"},
		},
		RuntimeDecls: decls,
		StringPool:   pool,
		Functions: []Function{
			{
				Name:   "add",
				Return: i64,
				Params: []Param{
					{Name: "%a", Type: i64},
					{Name: "%b", Type: i64},
				},
				Blocks: []Block{
					{
						Label: "entry",
						Instrs: []Instr{
							Binary{Dest: "%t0", Op: "add", Type: i64, Left: "%a", Right: "%b"},
						},
						Term: Ret{Type: i64, Value: "%t0"},
					},
				},
			},
		},
		Metadata: []string{"!0 = !{!0}"},
	}

	want := `; Code generated by osty LIR Proto. DO NOT EDIT.
; Osty: /tmp/main.osty
source_filename = "/tmp/main.osty"
target triple = "x86_64-unknown-linux-gnu"

%Pair = type { i64, ptr }

@counter = global i64 0
@.str.0 = private unnamed_addr constant [7 x i8] c"hello\0A\00"
@.str.1 = private unnamed_addr constant [16 x i8] c"quote \22 slash \5C\00"

declare i32 @printf(ptr, ...)
declare void @osty_rt_ping()

define i64 @add(i64 %a, i64 %b) {
entry:
  %t0 = add i64 %a, %b
  ret i64 %t0
}

!0 = !{!0}`

	for i := 0; i < 2; i++ {
		if got := Render(mod); got != want {
			t.Fatalf("Render pass %d mismatch\n--- got ---\n%s\n--- want ---\n%s", i+1, got, want)
		}
	}
}

func TestRenderDefaultsSourceAndVoidReturn(t *testing.T) {
	got := Render(Module{
		Functions: []Function{
			{
				Name: "main",
				Blocks: []Block{
					{Term: Ret{}},
				},
			},
		},
	})

	want := `; Code generated by osty LIR Proto. DO NOT EDIT.
; Osty: <unknown>
source_filename = "<unknown>"

define void @main() {
entry:
  ret void
}`
	if got != want {
		t.Fatalf("Render() mismatch\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

func TestRenderTypedInstructionsAndTerminators(t *testing.T) {
	i1 := IntType(1)
	i64 := IntType(64)
	i128 := IntType(128)
	pair := AggregateType("%Pair")
	ptr := PtrType()
	void := VoidType()

	got := Render(Module{
		SourcePath: "/tmp/typed.osty",
		TypeDefs: []TypeDef{
			{Name: "%Pair", Body: "{ i64, i64 }"},
		},
		Functions: []Function{
			{
				Name:   "typed",
				Return: void,
				Params: []Param{
					{Name: "%p", Type: ptr},
					{Name: "%cond", Type: i1},
				},
				Blocks: []Block{
					{
						Label: "entry",
						Instrs: []Instr{
							Comment{Text: "typed body"},
							Alloca{Dest: "%slot", Type: i64, Align: 8},
							Store{Value: Operand{Type: i64, Value: "7"}, Ptr: "%slot", Align: 8},
							Load{Dest: "%v", Type: i64, Ptr: "%slot", Align: 8},
							Binary{Dest: "%sum", Op: "add", Type: i64, Left: "%v", Right: "1"},
							Cast{Dest: "%wide", Op: "sext", From: Operand{Type: i64, Value: "%sum"}, To: i128},
							InsertValue{Dest: "%pair", Type: pair, Aggregate: "undef", Value: Operand{Type: i64, Value: "%v"}, Indices: []int{0}},
							ExtractValue{Dest: "%field", Type: pair, Aggregate: "%pair", Indices: []int{0}},
							Gep{Dest: "%elem", ElemType: i64, Ptr: "%p", Indices: []Operand{{Type: i64, Value: "%field"}}, Inbounds: true},
							Call{Callee: "@side", Return: void, Args: []Operand{{Type: ptr, Value: "%elem"}, {Type: i128, Value: "%wide"}}},
						},
						Term: CondBr{Cond: "%cond", Then: "then", Else: "else"},
					},
					{
						Label: "then",
						Term:  Br{Target: "done"},
					},
					{
						Label: "else",
						Term:  Unreachable{},
					},
					{
						Label: "done",
						Term:  Ret{},
					},
				},
			},
		},
	})

	want := `; Code generated by osty LIR Proto. DO NOT EDIT.
; Osty: /tmp/typed.osty
source_filename = "/tmp/typed.osty"

%Pair = type { i64, i64 }

define void @typed(ptr %p, i1 %cond) {
entry:
  ; typed body
  %slot = alloca i64, align 8
  store i64 7, ptr %slot, align 8
  %v = load i64, ptr %slot, align 8
  %sum = add i64 %v, 1
  %wide = sext i64 %sum to i128
  %pair = insertvalue %Pair undef, i64 %v, 0
  %field = extractvalue %Pair %pair, 0
  %elem = getelementptr inbounds i64, ptr %p, i64 %field
  call void @side(ptr %elem, i128 %wide)
  br i1 %cond, label %then, label %else
then:
  br label %done
else:
  unreachable
done:
  ret void
}`
	if got != want {
		t.Fatalf("Render() mismatch\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}
