package lirproto

import (
	"fmt"
	"strings"
)

const generatedHeader = "; Code generated by osty LIR Proto. DO NOT EDIT."

// Render emits deterministic LLVM text for the module.
func Render(m Module) string {
	var out []string
	source := m.SourcePath
	if source == "" {
		source = "<unknown>"
	}
	out = append(out,
		generatedHeader,
		fmt.Sprintf("; Osty: %s", source),
		fmt.Sprintf("source_filename = %q", source),
	)
	if m.Target != "" {
		out = append(out, fmt.Sprintf("target triple = %q", m.Target))
	}
	out = append(out, "")

	for _, td := range m.TypeDefs {
		out = append(out, renderTypeDef(td))
	}
	if len(m.TypeDefs) > 0 {
		out = append(out, "")
	}

	for _, glob := range m.Globals {
		out = append(out, renderGlobal(glob))
	}
	for _, sg := range m.StringPool.Ordered() {
		out = append(out, renderStringGlobal(sg))
	}
	if len(m.Globals) > 0 || !m.StringPool.IsEmpty() {
		out = append(out, "")
	}

	for _, decl := range m.RuntimeDecls.Ordered() {
		out = append(out, renderRuntimeDecl(decl))
	}
	if !m.RuntimeDecls.IsEmpty() {
		out = append(out, "")
	}

	for i, fn := range m.Functions {
		if i > 0 {
			out = append(out, "")
		}
		out = append(out, renderFunction(fn))
	}
	if len(m.Metadata) > 0 {
		if len(m.Functions) > 0 {
			out = append(out, "")
		}
		out = append(out, m.Metadata...)
	}
	return strings.Join(trimTrailingBlank(out), "\n")
}

func renderTypeDef(td TypeDef) string {
	return fmt.Sprintf("%s = type %s", td.Name, td.Body)
}

func renderGlobal(g Global) string {
	init := g.Init
	if init == "" {
		init = "zeroinitializer"
	}
	parts := []string{g.Name, "=", "global", g.Type.String(), init}
	parts = append(parts, g.Attrs...)
	return strings.Join(parts, " ")
}

func renderStringGlobal(g StringGlobal) string {
	return fmt.Sprintf("%s = private unnamed_addr constant [%d x i8] c\"%s\"", g.Symbol, g.ByteLen, g.Encoded)
}

func renderRuntimeDecl(d RuntimeDecl) string {
	params := make([]string, 0, len(d.Params)+1)
	for _, p := range d.Params {
		params = append(params, p.String())
	}
	if d.Vararg {
		params = append(params, "...")
	}
	return fmt.Sprintf("declare %s @%s(%s)", d.Return, d.Symbol, strings.Join(params, ", "))
}

func renderFunction(fn Function) string {
	ret := fn.Return
	if ret.IsZero() {
		ret = VoidType()
	}
	linkage := fn.Linkage
	if linkage == "" {
		linkage = "define"
	}
	var head []string
	head = append(head, linkage)
	if fn.CallingConv != "" {
		head = append(head, fn.CallingConv)
	}
	head = append(head, ret.String(), "@"+fn.Name+"("+renderParams(fn.Params)+")")
	head = append(head, fn.Attrs...)

	var lines []string
	lines = append(lines, strings.Join(head, " ")+" {")
	for _, bb := range fn.Blocks {
		label := bb.Label
		if label == "" {
			label = "entry"
		}
		lines = append(lines, label+":")
		for _, instr := range bb.Instrs {
			if instr == nil {
				continue
			}
			text := instr.renderLLVM()
			if text == "" {
				continue
			}
			lines = append(lines, "  "+text)
		}
		if bb.Term != nil {
			text := bb.Term.renderLLVM()
			if text != "" {
				lines = append(lines, "  "+text)
			}
		}
	}
	lines = append(lines, "}")
	return strings.Join(lines, "\n")
}

func renderParams(params []Param) string {
	out := make([]string, 0, len(params))
	for _, p := range params {
		if p.Name == "" {
			out = append(out, p.Type.String())
			continue
		}
		out = append(out, fmt.Sprintf("%s %s", p.Type, p.Name))
	}
	return strings.Join(out, ", ")
}

func (i Alloca) renderLLVM() string {
	line := fmt.Sprintf("%s = alloca %s", i.Dest, i.Type)
	return appendAlign(line, i.Align)
}

func (i Load) renderLLVM() string {
	line := fmt.Sprintf("%s = load %s, ptr %s", i.Dest, i.Type, i.Ptr)
	return appendAlign(line, i.Align)
}

func (i Store) renderLLVM() string {
	line := fmt.Sprintf("store %s %s, ptr %s", i.Value.Type, i.Value.Value, i.Ptr)
	return appendAlign(line, i.Align)
}

func (i Binary) renderLLVM() string {
	return fmt.Sprintf("%s = %s %s %s, %s", i.Dest, i.Op, i.Type, i.Left, i.Right)
}

func (i Unary) renderLLVM() string {
	return fmt.Sprintf("%s = %s %s %s", i.Dest, i.Op, i.Type, i.Value)
}

func (i Call) renderLLVM() string {
	ret := i.Return
	if ret.IsZero() {
		ret = VoidType()
	}
	args := renderOperands(i.Args)
	var head []string
	if i.Dest != "" {
		head = append(head, i.Dest, "=")
	}
	head = append(head, "call")
	if i.CallingConv != "" {
		head = append(head, i.CallingConv)
	}
	head = append(head, ret.String(), i.Callee+"("+args+")")
	head = append(head, i.Attrs...)
	return strings.Join(head, " ")
}

func (i Cast) renderLLVM() string {
	return fmt.Sprintf("%s = %s %s %s to %s", i.Dest, i.Op, i.From.Type, i.From.Value, i.To)
}

func (i InsertValue) renderLLVM() string {
	return fmt.Sprintf("%s = insertvalue %s %s, %s %s, %s", i.Dest, i.Type, i.Aggregate, i.Value.Type, i.Value.Value, renderIndices(i.Indices))
}

func (i ExtractValue) renderLLVM() string {
	return fmt.Sprintf("%s = extractvalue %s %s, %s", i.Dest, i.Type, i.Aggregate, renderIndices(i.Indices))
}

func (i Gep) renderLLVM() string {
	op := "getelementptr"
	if i.Inbounds {
		op += " inbounds"
	}
	return fmt.Sprintf("%s = %s %s, ptr %s, %s", i.Dest, op, i.ElemType, i.Ptr, renderOperands(i.Indices))
}

func (i Comment) renderLLVM() string {
	if i.Text == "" {
		return ""
	}
	if strings.HasPrefix(i.Text, ";") {
		return i.Text
	}
	return "; " + i.Text
}

func (t Ret) renderLLVM() string {
	if t.Type.IsZero() && t.Value == "" {
		return "ret void"
	}
	return fmt.Sprintf("ret %s %s", t.Type, t.Value)
}

func (t Br) renderLLVM() string {
	return fmt.Sprintf("br label %%%s", strings.TrimPrefix(t.Target, "%"))
}

func (t CondBr) renderLLVM() string {
	return fmt.Sprintf("br i1 %s, label %%%s, label %%%s", t.Cond, strings.TrimPrefix(t.Then, "%"), strings.TrimPrefix(t.Else, "%"))
}

func (t Switch) renderLLVM() string {
	var b strings.Builder
	fmt.Fprintf(&b, "switch %s %s, label %%%s [", t.Type, t.Scrutinee, strings.TrimPrefix(t.Default, "%"))
	for _, c := range t.Cases {
		fmt.Fprintf(&b, "\n    %s %s, label %%%s", t.Type, c.Value, strings.TrimPrefix(c.Label, "%"))
	}
	if len(t.Cases) > 0 {
		b.WriteString("\n  ")
	}
	b.WriteString("]")
	return b.String()
}

func (Unreachable) renderLLVM() string {
	return "unreachable"
}

func appendAlign(line string, align int) string {
	if align <= 0 {
		return line
	}
	return fmt.Sprintf("%s, align %d", line, align)
}

func renderOperands(args []Operand) string {
	out := make([]string, 0, len(args))
	for _, arg := range args {
		out = append(out, fmt.Sprintf("%s %s", arg.Type, arg.Value))
	}
	return strings.Join(out, ", ")
}

func renderIndices(indices []int) string {
	out := make([]string, 0, len(indices))
	for _, idx := range indices {
		out = append(out, fmt.Sprintf("%d", idx))
	}
	return strings.Join(out, ", ")
}

func trimTrailingBlank(lines []string) []string {
	for len(lines) > 0 && lines[len(lines)-1] == "" {
		lines = lines[:len(lines)-1]
	}
	return lines
}

func llvmCString(s string) string {
	var b strings.Builder
	for _, c := range []byte(s) {
		switch {
		case c == '\\':
			b.WriteString(`\5C`)
		case c == '"':
			b.WriteString(`\22`)
		case c >= 0x20 && c <= 0x7e:
			b.WriteByte(c)
		default:
			b.WriteString(fmt.Sprintf(`\%02X`, c))
		}
	}
	b.WriteString(`\00`)
	return b.String()
}
