//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

var sourceFiles = []string{
	"examples/selfhost-core/semver.osty",
	"examples/selfhost-core/semver_parse.osty",
	"examples/selfhost-core/manifest_features.osty",
	"examples/selfhost-core/manifest_validation.osty",
}

const mergedPath = "/tmp/manifest_validate_core.osty"

const stringsPrelude = `use go "strings" as strings {
    fn Contains(s: String, substr: String) -> Bool
    fn Fields(s: String) -> List<String>
    fn HasPrefix(s: String, prefix: String) -> Bool
    fn Join(elems: List<String>, sep: String) -> String
    fn Split(s: String, sep: String) -> List<String>
    fn SplitN(s: String, sep: String, n: Int) -> List<String>
    fn TrimPrefix(s: String, prefix: String) -> String
    fn TrimSpace(s: String) -> String
}

`

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run() error {
	root, err := repoRoot()
	if err != nil {
		return err
	}
	merged, err := mergedSource(root)
	if err != nil {
		return err
	}
	if err := os.WriteFile(mergedPath, merged, 0o644); err != nil {
		return fmt.Errorf("write merged manifest validation source: %w", err)
	}

	outPath := filepath.Join(root, "internal/manifest/validate_core_generated.go")
	cmd := exec.Command("go", "run", "-tags", "selfhostgen", "./cmd/osty", "gen", "--package", "manifest", "-o", outPath, mergedPath)
	cmd.Dir = root
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("generate manifest validation core: %w\n%s", err, bytes.TrimSpace(output))
	}
	return rewriteGenerated(outPath)
}

func repoRoot() (string, error) {
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(wd, "go.mod")); err == nil {
			return wd, nil
		}
		parent := filepath.Dir(wd)
		if parent == wd {
			return "", fmt.Errorf("could not find repo root")
		}
		wd = parent
	}
}

func mergedSource(root string) ([]byte, error) {
	var out bytes.Buffer
	out.WriteString(stringsPrelude)
	for _, rel := range sourceFiles {
		src, err := os.ReadFile(filepath.Join(root, rel))
		if err != nil {
			return nil, fmt.Errorf("read %s: %w", rel, err)
		}
		out.Write(stripStringsUse(src))
		out.WriteByte('\n')
	}
	return out.Bytes(), nil
}

func stripStringsUse(src []byte) []byte {
	lines := strings.Split(string(src), "\n")
	out := make([]string, 0, len(lines))
	skipping := false
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if !skipping && strings.HasPrefix(trimmed, `use go "strings" as strings {`) {
			skipping = true
			continue
		}
		if skipping {
			if trimmed == "}" {
				skipping = false
			}
			continue
		}
		out = append(out, line)
	}
	return []byte(strings.Join(out, "\n"))
}

func rewriteGenerated(path string) error {
	src, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read generated manifest validation core: %w", err)
	}
	text := string(src)
	text = strings.Replace(text,
		"// Code generated by osty. DO NOT EDIT.\n// Osty source: "+mergedPath+"\n",
		"// Code generated by internal/manifest/gen_validate_core.go from examples/selfhost-core manifest sources. DO NOT EDIT.\n",
		1,
	)
	formatted, err := format.Source([]byte(text))
	if err != nil {
		return fmt.Errorf("format generated manifest validation core: %w", err)
	}
	if err := os.WriteFile(path, formatted, 0o644); err != nil {
		return fmt.Errorf("write generated manifest validation core: %w", err)
	}
	return nil
}
