// Code generated by internal/manifest/gen_validate_core.go from examples/selfhost-core manifest sources. DO NOT EDIT.

package manifest

import (
	"fmt"
	"math"
	"strings"
)

type ostyStringer interface {
	toString() string
}

func ostyToString(v any) string {
	if s, ok := v.(ostyStringer); ok {
		return s.toString()
	}
	if b, ok := v.([]byte); ok {
		return string(b)
	}
	return fmt.Sprint(v)
}

// Result is the runtime representation of Osty's Result<T, E>.
// IsOk distinguishes Ok(Value) from Err(Error).
type Result[T any, E any] struct {
	Value T
	Error E
	IsOk  bool
	ref   *byte
}

func resultRef() *byte { return new(byte) }

func resultOk[T any, E any](value T) Result[T, E] {
	return Result[T, E]{Value: value, IsOk: true, ref: resultRef()}
}

func resultErr[T any, E any](err E) Result[T, E] {
	return Result[T, E]{Error: err, ref: resultRef()}
}

func (r Result[T, E]) isOk() bool { return r.IsOk }

func (r Result[T, E]) isErr() bool { return !r.IsOk }

func (r Result[T, E]) unwrap() T {
	if !r.IsOk {
		panic("called unwrap on Err")
	}
	return r.Value
}

func (r Result[T, E]) expect(msg string) T {
	if !r.IsOk {
		panic(msg)
	}
	return r.Value
}

func (r Result[T, E]) unwrapErr() E {
	if r.IsOk {
		panic("called unwrapErr on Ok")
	}
	return r.Error
}

func (r Result[T, E]) expectErr(msg string) E {
	if r.IsOk {
		panic(msg)
	}
	return r.Error
}

func (r Result[T, E]) unwrapOr(fallback T) T {
	if r.IsOk {
		return r.Value
	}
	return fallback
}

func (r Result[T, E]) unwrapOrElse(fallback func(E) T) T {
	if r.IsOk {
		return r.Value
	}
	return fallback(r.Error)
}

func (r Result[T, E]) ok() *T {
	if r.IsOk {
		return &r.Value
	}
	return nil
}

func (r Result[T, E]) err() *E {
	if !r.IsOk {
		return &r.Error
	}
	return nil
}

func (r Result[T, E]) toString() string {
	if r.IsOk {
		return "Ok(" + ostyToString(r.Value) + ")"
	}
	return "Err(" + ostyToString(r.Error) + ")"
}

func (r Result[T, E]) inspect(f func(T)) Result[T, E] {
	if r.IsOk {
		f(r.Value)
	}
	return r
}

func (r Result[T, E]) inspectErr(f func(E)) Result[T, E] {
	if !r.IsOk {
		f(r.Error)
	}
	return r
}

func resultAnd[T any, E any, U any](r Result[T, E], other Result[U, E]) Result[U, E] {
	if r.IsOk {
		return other
	}
	return resultErr[U, E](r.Error)
}

func resultAndThen[T any, E any, U any](r Result[T, E], f func(T) Result[U, E]) Result[U, E] {
	if r.IsOk {
		return f(r.Value)
	}
	return resultErr[U, E](r.Error)
}

func resultOr[T any, E any, F any](r Result[T, E], other Result[T, F]) Result[T, F] {
	if r.IsOk {
		return resultOk[T, F](r.Value)
	}
	return other
}

func resultOrElse[T any, E any, F any](r Result[T, E], f func(E) Result[T, F]) Result[T, F] {
	if r.IsOk {
		return resultOk[T, F](r.Value)
	}
	return f(r.Error)
}

func resultMap[T any, E any, U any](r Result[T, E], f func(T) U) Result[U, E] {
	if r.IsOk {
		return resultOk[U, E](f(r.Value))
	}
	return resultErr[U, E](r.Error)
}

func resultMapErr[T any, E any, F any](r Result[T, E], f func(E) F) Result[T, F] {
	if r.IsOk {
		return resultOk[T, F](r.Value)
	}
	return resultErr[T, F](f(r.Error))
}

// Osty: /tmp/manifest_validate_core.osty:13:5
type SemPreIdent interface{ _isSemPreIdent() }
type SemPreIdent_PreNone struct{ _ref byte }

func (SemPreIdent_PreNone) _isSemPreIdent() {}

type SemPreIdent_PreNumber struct {
	F0 int
}

func (SemPreIdent_PreNumber) _isSemPreIdent() {}

type SemPreIdent_PreText struct {
	F0 string
}

func (SemPreIdent_PreText) _isSemPreIdent() {}

// Osty: /tmp/manifest_validate_core.osty:25:5
type SemVersion struct {
	major int
	minor int
	patch int
	pre1  SemPreIdent
	pre2  SemPreIdent
	pre3  SemPreIdent
	build string
}

// Osty: /tmp/manifest_validate_core.osty:36:5
func preNone() SemPreIdent {
	return SemPreIdent(&SemPreIdent_PreNone{})
}

// Osty: /tmp/manifest_validate_core.osty:41:5
func preNumber(n int) SemPreIdent {
	return SemPreIdent(&SemPreIdent_PreNumber{F0: n})
}

// Osty: /tmp/manifest_validate_core.osty:46:5
func preText(s string) SemPreIdent {
	return SemPreIdent(&SemPreIdent_PreText{F0: s})
}

// Osty: /tmp/manifest_validate_core.osty:51:5
func semVersion(major int, minor int, patch int, pre1 SemPreIdent, pre2 SemPreIdent, pre3 SemPreIdent, build string) *SemVersion {
	return &SemVersion{major: major, minor: minor, patch: patch, pre1: pre1, pre2: pre2, pre3: pre3, build: build}
}

// Osty: /tmp/manifest_validate_core.osty:64:5
func stableVersion(major int, minor int, patch int) *SemVersion {
	return semVersion(major, minor, patch, preNone(), preNone(), preNone(), "")
}

// Osty: /tmp/manifest_validate_core.osty:69:5
func prerelease1(major int, minor int, patch int, pre1 SemPreIdent) *SemVersion {
	return semVersion(major, minor, patch, pre1, preNone(), preNone(), "")
}

// Osty: /tmp/manifest_validate_core.osty:74:5
func prerelease2(major int, minor int, patch int, pre1 SemPreIdent, pre2 SemPreIdent) *SemVersion {
	return semVersion(major, minor, patch, pre1, pre2, preNone(), "")
}

// Osty: /tmp/manifest_validate_core.osty:85:5
func versionWithBuild(major int, minor int, patch int, build string) *SemVersion {
	return semVersion(major, minor, patch, preNone(), preNone(), preNone(), build)
}

// Osty: /tmp/manifest_validate_core.osty:90:5
func isSemPrerelease(v *SemVersion) bool {
	return func() bool {
		_m1 := v.pre1
		_ = _m1
		if func() bool { _, ok := _m1.(*SemPreIdent_PreNone); return ok }() {
			return false
		}
		{
			return true
		}
	}()
}

// Osty: /tmp/manifest_validate_core.osty:98:5
func compareSemVersion(a *SemVersion, b *SemVersion) int {
	// Osty: /tmp/manifest_validate_core.osty:99:5
	major := signInt(a.major, b.major)
	_ = major
	// Osty: /tmp/manifest_validate_core.osty:100:5
	if major != 0 {
		// Osty: /tmp/manifest_validate_core.osty:101:9
		return major
	}
	// Osty: /tmp/manifest_validate_core.osty:104:5
	minor := signInt(a.minor, b.minor)
	_ = minor
	// Osty: /tmp/manifest_validate_core.osty:105:5
	if minor != 0 {
		// Osty: /tmp/manifest_validate_core.osty:106:9
		return minor
	}
	// Osty: /tmp/manifest_validate_core.osty:109:5
	patch := signInt(a.patch, b.patch)
	_ = patch
	// Osty: /tmp/manifest_validate_core.osty:110:5
	if patch != 0 {
		// Osty: /tmp/manifest_validate_core.osty:111:9
		return patch
	}
	// Osty: /tmp/manifest_validate_core.osty:114:5
	aPre := isSemPrerelease(a)
	_ = aPre
	// Osty: /tmp/manifest_validate_core.osty:115:5
	bPre := isSemPrerelease(b)
	_ = bPre
	// Osty: /tmp/manifest_validate_core.osty:116:5
	if !(aPre) && !(bPre) {
		// Osty: /tmp/manifest_validate_core.osty:117:9
		return 0
	}
	// Osty: /tmp/manifest_validate_core.osty:119:5
	if !(aPre) {
		// Osty: /tmp/manifest_validate_core.osty:120:9
		return 1
	}
	// Osty: /tmp/manifest_validate_core.osty:122:5
	if !(bPre) {
		// Osty: /tmp/manifest_validate_core.osty:123:9
		return -1
	}
	// Osty: /tmp/manifest_validate_core.osty:126:5
	p1 := comparePreIdent(a.pre1, b.pre1)
	_ = p1
	// Osty: /tmp/manifest_validate_core.osty:127:5
	if p1 != 0 {
		// Osty: /tmp/manifest_validate_core.osty:128:9
		return p1
	}
	// Osty: /tmp/manifest_validate_core.osty:130:5
	p2 := comparePreIdent(a.pre2, b.pre2)
	_ = p2
	// Osty: /tmp/manifest_validate_core.osty:131:5
	if p2 != 0 {
		// Osty: /tmp/manifest_validate_core.osty:132:9
		return p2
	}
	return comparePreIdent(a.pre3, b.pre3)
}

// Osty: /tmp/manifest_validate_core.osty:138:5
func comparePreIdent(a SemPreIdent, b SemPreIdent) int {
	return func() int {
		_m2 := a
		_ = _m2
		if func() bool { _, ok := _m2.(*SemPreIdent_PreNone); return ok }() {
			return func() int {
				_m3 := b
				_ = _m3
				if func() bool { _, ok := _m3.(*SemPreIdent_PreNone); return ok }() {
					return 0
				}
				{
					return -1
				}
			}()
		}
		if func() bool { _, ok := _m2.(*SemPreIdent_PreNumber); return ok }() {
			_v4 := _m2.(*SemPreIdent_PreNumber)
			_ = _v4
			an := _v4.F0
			_ = an
			return func() int {
				_m5 := b
				_ = _m5
				if func() bool { _, ok := _m5.(*SemPreIdent_PreNone); return ok }() {
					return 1
				}
				if func() bool { _, ok := _m5.(*SemPreIdent_PreNumber); return ok }() {
					_v6 := _m5.(*SemPreIdent_PreNumber)
					_ = _v6
					bn := _v6.F0
					_ = bn
					return signInt(an, bn)
				}
				if func() bool { _, ok := _m5.(*SemPreIdent_PreText); return ok }() {
					_v7 := _m5.(*SemPreIdent_PreText)
					_ = _v7
					return -1
				}
				panic("unreachable match")
			}()
		}
		if func() bool { _, ok := _m2.(*SemPreIdent_PreText); return ok }() {
			_v8 := _m2.(*SemPreIdent_PreText)
			_ = _v8
			at := _v8.F0
			_ = at
			return func() int {
				_m9 := b
				_ = _m9
				if func() bool { _, ok := _m9.(*SemPreIdent_PreNone); return ok }() {
					return 1
				}
				if func() bool { _, ok := _m9.(*SemPreIdent_PreNumber); return ok }() {
					_v10 := _m9.(*SemPreIdent_PreNumber)
					_ = _v10
					return 1
				}
				if func() bool { _, ok := _m9.(*SemPreIdent_PreText); return ok }() {
					_v11 := _m9.(*SemPreIdent_PreText)
					_ = _v11
					bt := _v11.F0
					_ = bt
					return signString(at, bt)
				}
				panic("unreachable match")
			}()
		}
		panic("unreachable match")
	}()
}

// Osty: /tmp/manifest_validate_core.osty:158:5
func signInt(a int, b int) int {
	return func() int {
		if a < b {
			return -1
		} else if a > b {
			return 1
		} else {
			return 0
		}
	}()
}

// Osty: /tmp/manifest_validate_core.osty:169:5
func signString(a string, b string) int {
	return func() int {
		if a < b {
			return -1
		} else if a > b {
			return 1
		} else {
			return 0
		}
	}()
}

// Osty: /tmp/manifest_validate_core.osty:181:5
type SemSplit struct {
	count  int
	first  string
	second string
	third  string
}

// Osty: /tmp/manifest_validate_core.osty:189:5
func splitSummary(parts []string) *SemSplit {
	// Osty: /tmp/manifest_validate_core.osty:190:5
	count := 0
	_ = count
	// Osty: /tmp/manifest_validate_core.osty:191:5
	first := ""
	_ = first
	// Osty: /tmp/manifest_validate_core.osty:192:5
	second := ""
	_ = second
	// Osty: /tmp/manifest_validate_core.osty:193:5
	third := ""
	_ = third
	// Osty: /tmp/manifest_validate_core.osty:194:5
	for _, part := range parts {
		// Osty: /tmp/manifest_validate_core.osty:195:9
		if count == 0 {
			// Osty: /tmp/manifest_validate_core.osty:196:13
			first = part
		} else if count == 1 {
			// Osty: /tmp/manifest_validate_core.osty:198:13
			second = part
		} else if count == 2 {
			// Osty: /tmp/manifest_validate_core.osty:200:13
			third = part
		}
		// Osty: /tmp/manifest_validate_core.osty:202:9
		func() {
			var _cur12 int = count
			var _rhs13 int = 1
			if _rhs13 > 0 && _cur12 > math.MaxInt-_rhs13 {
				panic("integer overflow")
			}
			if _rhs13 < 0 && _cur12 < math.MinInt-_rhs13 {
				panic("integer overflow")
			}
			count = _cur12 + _rhs13
		}()
	}
	return &SemSplit{count: count, first: first, second: second, third: third}
}

// Osty: /tmp/manifest_validate_core.osty:208:5
func parseSemVersionText(raw string) Result[*SemVersion, string] {
	// Osty: /tmp/manifest_validate_core.osty:209:5
	if raw == "" {
		// Osty: /tmp/manifest_validate_core.osty:210:9
		return resultErr[*SemVersion, string]("empty version")
	}
	// Osty: /tmp/manifest_validate_core.osty:212:5
	text := strings.TrimPrefix(raw, "v")
	_ = text
	// Osty: /tmp/manifest_validate_core.osty:213:5
	if text == "" {
		// Osty: /tmp/manifest_validate_core.osty:214:9
		return resultErr[*SemVersion, string]("empty version")
	}
	// Osty: /tmp/manifest_validate_core.osty:217:5
	plus := splitSummary(strings.SplitN(text, "+", 2))
	_ = plus
	// Osty: /tmp/manifest_validate_core.osty:218:5
	build := plus.second
	_ = build
	// Osty: /tmp/manifest_validate_core.osty:219:5
	if plus.count == 2 && !(buildIdentifiersValid(build)) {
		// Osty: /tmp/manifest_validate_core.osty:220:9
		return resultErr[*SemVersion, string]("invalid build metadata")
	}
	// Osty: /tmp/manifest_validate_core.osty:223:5
	dash := splitSummary(strings.SplitN(plus.first, "-", 2))
	_ = dash
	// Osty: /tmp/manifest_validate_core.osty:224:5
	_q14 := parseSemCore(dash.first)
	if !_q14.IsOk {
		return Result[*SemVersion, string]{Error: _q14.Error, ref: resultRef()}
	}
	base := _q14.Value
	_ = base
	// Osty: /tmp/manifest_validate_core.osty:225:5
	if dash.count == 1 {
		// Osty: /tmp/manifest_validate_core.osty:226:9
		return resultOk[*SemVersion, string](semVersion(base.major, base.minor, base.patch, preNone(), preNone(), preNone(), build))
	}
	// Osty: /tmp/manifest_validate_core.osty:238:5
	if dash.second == "" {
		// Osty: /tmp/manifest_validate_core.osty:239:9
		return resultErr[*SemVersion, string]("empty pre-release")
	}
	// Osty: /tmp/manifest_validate_core.osty:242:5
	pre := splitSummary(strings.Split(dash.second, "."))
	_ = pre
	// Osty: /tmp/manifest_validate_core.osty:243:5
	if pre.count > 3 {
		// Osty: /tmp/manifest_validate_core.osty:244:9
		return resultErr[*SemVersion, string]("too many pre-release identifiers")
	}
	// Osty: /tmp/manifest_validate_core.osty:246:5
	pre1 := preNone()
	_ = pre1
	// Osty: /tmp/manifest_validate_core.osty:247:5
	pre2 := preNone()
	_ = pre2
	// Osty: /tmp/manifest_validate_core.osty:248:5
	pre3 := preNone()
	_ = pre3
	// Osty: /tmp/manifest_validate_core.osty:249:5
	if pre.count >= 1 {
		// Osty: /tmp/manifest_validate_core.osty:250:9
		_q15 := parseSemPreIdent(pre.first)
		if !_q15.IsOk {
			return Result[*SemVersion, string]{Error: _q15.Error, ref: resultRef()}
		}
		pre1 = _q15.Value
	}
	// Osty: /tmp/manifest_validate_core.osty:252:5
	if pre.count >= 2 {
		// Osty: /tmp/manifest_validate_core.osty:253:9
		_q16 := parseSemPreIdent(pre.second)
		if !_q16.IsOk {
			return Result[*SemVersion, string]{Error: _q16.Error, ref: resultRef()}
		}
		pre2 = _q16.Value
	}
	// Osty: /tmp/manifest_validate_core.osty:255:5
	if pre.count >= 3 {
		// Osty: /tmp/manifest_validate_core.osty:256:9
		_q17 := parseSemPreIdent(pre.third)
		if !_q17.IsOk {
			return Result[*SemVersion, string]{Error: _q17.Error, ref: resultRef()}
		}
		pre3 = _q17.Value
	}
	return resultOk[*SemVersion, string](semVersion(base.major, base.minor, base.patch, pre1, pre2, pre3, build))
}

// Osty: /tmp/manifest_validate_core.osty:263:5
func parseSemCore(text string) Result[*SemVersion, string] {
	// Osty: /tmp/manifest_validate_core.osty:264:5
	parts := splitSummary(strings.Split(text, "."))
	_ = parts
	// Osty: /tmp/manifest_validate_core.osty:265:5
	if parts.count != 3 {
		// Osty: /tmp/manifest_validate_core.osty:266:9
		return resultErr[*SemVersion, string]("version must have major.minor.patch")
	}
	// Osty: /tmp/manifest_validate_core.osty:268:5
	_q18 := parseSemNumber(parts.first)
	if !_q18.IsOk {
		return Result[*SemVersion, string]{Error: _q18.Error, ref: resultRef()}
	}
	major := _q18.Value
	_ = major
	// Osty: /tmp/manifest_validate_core.osty:269:5
	_q19 := parseSemNumber(parts.second)
	if !_q19.IsOk {
		return Result[*SemVersion, string]{Error: _q19.Error, ref: resultRef()}
	}
	minor := _q19.Value
	_ = minor
	// Osty: /tmp/manifest_validate_core.osty:270:5
	_q20 := parseSemNumber(parts.third)
	if !_q20.IsOk {
		return Result[*SemVersion, string]{Error: _q20.Error, ref: resultRef()}
	}
	patch := _q20.Value
	_ = patch
	return resultOk[*SemVersion, string](stableVersion(major, minor, patch))
}

// Osty: /tmp/manifest_validate_core.osty:275:5
func parseSemPreIdent(text string) Result[SemPreIdent, string] {
	// Osty: /tmp/manifest_validate_core.osty:276:5
	if text == "" {
		// Osty: /tmp/manifest_validate_core.osty:277:9
		return resultErr[SemPreIdent, string]("empty pre-release identifier")
	}
	// Osty: /tmp/manifest_validate_core.osty:279:5
	if allAsciiDigits(text) {
		// Osty: /tmp/manifest_validate_core.osty:280:9
		_q21 := parseSemNumber(text)
		if !_q21.IsOk {
			return Result[SemPreIdent, string]{Error: _q21.Error, ref: resultRef()}
		}
		n := _q21.Value
		_ = n
		// Osty: /tmp/manifest_validate_core.osty:281:9
		return resultOk[SemPreIdent, string](preNumber(n))
	}
	// Osty: /tmp/manifest_validate_core.osty:283:5
	if !(identifierTextValid(text)) {
		// Osty: /tmp/manifest_validate_core.osty:284:9
		return resultErr[SemPreIdent, string]("invalid pre-release identifier")
	}
	return resultOk[SemPreIdent, string](preText(text))
}

// Osty: /tmp/manifest_validate_core.osty:290:5
func parseSemNumber(text string) Result[int, string] {
	// Osty: /tmp/manifest_validate_core.osty:291:5
	if text == "" {
		// Osty: /tmp/manifest_validate_core.osty:292:9
		return resultErr[int, string]("empty number")
	}
	// Osty: /tmp/manifest_validate_core.osty:294:5
	if stringUnitCount(text) > 1 && strings.HasPrefix(text, "0") {
		// Osty: /tmp/manifest_validate_core.osty:295:9
		return resultErr[int, string]("number has leading zero")
	}
	// Osty: /tmp/manifest_validate_core.osty:297:5
	out := 0
	_ = out
	// Osty: /tmp/manifest_validate_core.osty:298:5
	for _, unit := range strings.Split(text, "") {
		// Osty: /tmp/manifest_validate_core.osty:299:9
		digit := digitStringValue(unit)
		_ = digit
		// Osty: /tmp/manifest_validate_core.osty:300:9
		if digit < 0 {
			// Osty: /tmp/manifest_validate_core.osty:301:13
			return resultErr[int, string]("invalid decimal digit")
		}
		// Osty: /tmp/manifest_validate_core.osty:303:9
		func() {
			var _cur22 int = func() int {
				var _p24 int = out
				var _rhs25 int = 10
				if _p24 != 0 && _rhs25 != 0 {
					if _p24 == int(-1) && _rhs25 == math.MinInt {
						panic("integer overflow")
					}
					if _rhs25 == int(-1) && _p24 == math.MinInt {
						panic("integer overflow")
					}
					if _p24 > 0 {
						if _rhs25 > 0 && _p24 > math.MaxInt/_rhs25 {
							panic("integer overflow")
						}
						if _rhs25 < 0 && _rhs25 < math.MinInt/_p24 {
							panic("integer overflow")
						}
					} else {
						if _rhs25 > 0 && _p24 < math.MinInt/_rhs25 {
							panic("integer overflow")
						}
						if _rhs25 < 0 && _p24 < math.MaxInt/_rhs25 {
							panic("integer overflow")
						}
					}
				}
				return _p24 * _rhs25
			}()
			var _rhs23 int = digit
			if _rhs23 > 0 && _cur22 > math.MaxInt-_rhs23 {
				panic("integer overflow")
			}
			if _rhs23 < 0 && _cur22 < math.MinInt-_rhs23 {
				panic("integer overflow")
			}
			out = _cur22 + _rhs23
		}()
	}
	return resultOk[int, string](out)
}

// Osty: /tmp/manifest_validate_core.osty:309:5
func buildIdentifiersValid(text string) bool {
	// Osty: /tmp/manifest_validate_core.osty:310:5
	if text == "" {
		// Osty: /tmp/manifest_validate_core.osty:311:9
		return false
	}
	// Osty: /tmp/manifest_validate_core.osty:313:5
	for _, part := range strings.Split(text, ".") {
		// Osty: /tmp/manifest_validate_core.osty:314:9
		if !(identifierTextValid(part)) {
			// Osty: /tmp/manifest_validate_core.osty:315:13
			return false
		}
	}
	return true
}

// Osty: /tmp/manifest_validate_core.osty:322:5
func identifierTextValid(text string) bool {
	// Osty: /tmp/manifest_validate_core.osty:323:5
	if text == "" {
		// Osty: /tmp/manifest_validate_core.osty:324:9
		return false
	}
	// Osty: /tmp/manifest_validate_core.osty:326:5
	for _, unit := range strings.Split(text, "") {
		// Osty: /tmp/manifest_validate_core.osty:327:9
		if !(isSemIdentUnit(unit)) {
			// Osty: /tmp/manifest_validate_core.osty:328:13
			return false
		}
	}
	return true
}

// Osty: /tmp/manifest_validate_core.osty:335:5
func allAsciiDigits(text string) bool {
	// Osty: /tmp/manifest_validate_core.osty:336:5
	if text == "" {
		// Osty: /tmp/manifest_validate_core.osty:337:9
		return false
	}
	// Osty: /tmp/manifest_validate_core.osty:339:5
	for _, unit := range strings.Split(text, "") {
		// Osty: /tmp/manifest_validate_core.osty:340:9
		if digitStringValue(unit) < 0 {
			// Osty: /tmp/manifest_validate_core.osty:341:13
			return false
		}
	}
	return true
}

// Osty: /tmp/manifest_validate_core.osty:348:5
func stringUnitCount(text string) int {
	// Osty: /tmp/manifest_validate_core.osty:349:5
	count := 0
	_ = count
	// Osty: /tmp/manifest_validate_core.osty:350:5
	for _, unit := range strings.Split(text, "") {
		// Osty: /tmp/manifest_validate_core.osty:351:9
		_ = unit
		// Osty: /tmp/manifest_validate_core.osty:352:9
		func() {
			var _cur26 int = count
			var _rhs27 int = 1
			if _rhs27 > 0 && _cur26 > math.MaxInt-_rhs27 {
				panic("integer overflow")
			}
			if _rhs27 < 0 && _cur26 < math.MinInt-_rhs27 {
				panic("integer overflow")
			}
			count = _cur26 + _rhs27
		}()
	}
	return count
}

// Osty: /tmp/manifest_validate_core.osty:358:5
func isSemIdentUnit(unit string) bool {
	return (unit >= "0" && unit <= "9") || (unit >= "A" && unit <= "Z") || (unit >= "a" && unit <= "z") || unit == "-"
}

// Osty: /tmp/manifest_validate_core.osty:363:5
func digitStringValue(unit string) int {
	return func() int {
		if unit == "0" {
			return 0
		} else if unit == "1" {
			return 1
		} else if unit == "2" {
			return 2
		} else if unit == "3" {
			return 3
		} else if unit == "4" {
			return 4
		} else if unit == "5" {
			return 5
		} else if unit == "6" {
			return 6
		} else if unit == "7" {
			return 7
		} else if unit == "8" {
			return 8
		} else if unit == "9" {
			return 9
		} else {
			return -1
		}
	}()
}

// Osty: /tmp/manifest_validate_core.osty:390:5
type FeatureSpec struct {
	name string
	deps []string
}

// Osty: /tmp/manifest_validate_core.osty:396:5
type FeatureValidation struct {
	undefinedDefault int
	selfReferences   int
}

// Osty: /tmp/manifest_validate_core.osty:402:5
func featureSpec(name string, deps []string) *FeatureSpec {
	return &FeatureSpec{name: name, deps: deps}
}

// Osty: /tmp/manifest_validate_core.osty:407:5
func emptyFeatureValidation() *FeatureValidation {
	return &FeatureValidation{undefinedDefault: 0, selfReferences: 0}
}

// Osty: /tmp/manifest_validate_core.osty:412:5
func featureExists(name string, features []*FeatureSpec) bool {
	// Osty: /tmp/manifest_validate_core.osty:413:5
	for _, feature := range features {
		// Osty: /tmp/manifest_validate_core.osty:414:9
		if feature.name == name {
			// Osty: /tmp/manifest_validate_core.osty:415:13
			return true
		}
	}
	return false
}

// Osty: /tmp/manifest_validate_core.osty:422:5
func validateFeatureGraph(defaults []string, features []*FeatureSpec) *FeatureValidation {
	// Osty: /tmp/manifest_validate_core.osty:423:5
	out := emptyFeatureValidation()
	_ = out
	// Osty: /tmp/manifest_validate_core.osty:424:5
	for _, name := range defaults {
		// Osty: /tmp/manifest_validate_core.osty:425:9
		if !(featureExists(name, features)) {
			// Osty: /tmp/manifest_validate_core.osty:426:16
			out.undefinedDefault = func() int {
				var _p28 int = out.undefinedDefault
				var _rhs29 int = 1
				if _rhs29 > 0 && _p28 > math.MaxInt-_rhs29 {
					panic("integer overflow")
				}
				if _rhs29 < 0 && _p28 < math.MinInt-_rhs29 {
					panic("integer overflow")
				}
				return _p28 + _rhs29
			}()
		}
	}
	// Osty: /tmp/manifest_validate_core.osty:429:5
	for _, feature := range features {
		// Osty: /tmp/manifest_validate_core.osty:430:9
		for _, dep := range feature.deps {
			// Osty: /tmp/manifest_validate_core.osty:431:13
			if dep == feature.name {
				// Osty: /tmp/manifest_validate_core.osty:432:20
				out.selfReferences = func() int {
					var _p30 int = out.selfReferences
					var _rhs31 int = 1
					if _rhs31 > 0 && _p30 > math.MaxInt-_rhs31 {
						panic("integer overflow")
					}
					if _rhs31 < 0 && _p30 < math.MinInt-_rhs31 {
						panic("integer overflow")
					}
					return _p30 + _rhs31
				}()
			}
		}
	}
	return out
}

// Osty: /tmp/manifest_validate_core.osty:441:5
type ManifestPackageSpec struct {
	present     bool
	name        string
	version     string
	edition     string
	tableLine   int
	nameLine    int
	versionLine int
	editionLine int
}

// Osty: /tmp/manifest_validate_core.osty:453:5
type ManifestWorkspaceSpec struct {
	present bool
	members []string
}

// Osty: /tmp/manifest_validate_core.osty:459:5
type ManifestProfileSpec struct {
	name        string
	inherits    string
	hasOptLevel bool
	optLevel    int
	line        int
}

// Osty: /tmp/manifest_validate_core.osty:468:5
type ManifestTargetSpec struct {
	triple string
	line   int
}

// Osty: /tmp/manifest_validate_core.osty:474:5
type ManifestDependencySpec struct {
	name       string
	versionReq string
	path       string
	git        string
	section    string
	line       int
}

// Osty: /tmp/manifest_validate_core.osty:484:5
type ManifestDiagnosticSpec struct {
	severity string
	code     string
	message  string
	line     int
	hint     string
}

// Osty: /tmp/manifest_validate_core.osty:493:5
type ManifestSpec struct {
	pkg             *ManifestPackageSpec
	workspace       *ManifestWorkspaceSpec
	dependencies    []*ManifestDependencySpec
	devDependencies []*ManifestDependencySpec
	profiles        []*ManifestProfileSpec
	targets         []*ManifestTargetSpec
	defaultFeatures []string
	features        []*FeatureSpec
}

// Osty: /tmp/manifest_validate_core.osty:505:5
type ManifestValidation struct {
	missingRoots           int
	missingPackageNames    int
	badPackageNames        int
	missingPackageVersions int
	badPackageVersions     int
	missingEditions        int
	unknownEditions        int
	emptyWorkspaces        int
	badProfileOptLevels    int
	unknownProfileBases    int
	profileCycles          int
	badTargets             int
	badDependencyVersions  int
	features               *FeatureValidation
}

// Osty: /tmp/manifest_validate_core.osty:522:5
func manifestPackageSpec(present bool, name string, version string, edition string) *ManifestPackageSpec {
	return manifestPackageSpecAt(present, name, version, edition, 1, 1, 1, 1)
}

// Osty: /tmp/manifest_validate_core.osty:531:5
func manifestPackageSpecAt(present bool, name string, version string, edition string, tableLine int, nameLine int, versionLine int, editionLine int) *ManifestPackageSpec {
	return &ManifestPackageSpec{present: present, name: name, version: version, edition: edition, tableLine: tableLine, nameLine: nameLine, versionLine: versionLine, editionLine: editionLine}
}

// Osty: /tmp/manifest_validate_core.osty:544:5
func manifestWorkspaceSpec(present bool, members []string) *ManifestWorkspaceSpec {
	return &ManifestWorkspaceSpec{present: present, members: members}
}

// Osty: /tmp/manifest_validate_core.osty:548:5
func manifestProfileSpec(name string, inherits string, hasOptLevel bool, optLevel int) *ManifestProfileSpec {
	return manifestProfileSpecAt(name, inherits, hasOptLevel, optLevel, 1)
}

// Osty: /tmp/manifest_validate_core.osty:557:5
func manifestProfileSpecAt(name string, inherits string, hasOptLevel bool, optLevel int, line int) *ManifestProfileSpec {
	return &ManifestProfileSpec{name: name, inherits: inherits, hasOptLevel: hasOptLevel, optLevel: optLevel, line: line}
}

// Osty: /tmp/manifest_validate_core.osty:567:5
func manifestTargetSpec(triple string) *ManifestTargetSpec {
	return manifestTargetSpecAt(triple, 1)
}

// Osty: /tmp/manifest_validate_core.osty:571:5
func manifestTargetSpecAt(triple string, line int) *ManifestTargetSpec {
	return &ManifestTargetSpec{triple: triple, line: line}
}

// Osty: /tmp/manifest_validate_core.osty:575:5
func manifestDependencySpec(name string, versionReq string, path string, git string) *ManifestDependencySpec {
	return manifestDependencySpecAt(name, versionReq, path, git, "dependencies", 1)
}

// Osty: /tmp/manifest_validate_core.osty:584:5
func manifestDependencySpecAt(name string, versionReq string, path string, git string, section string, line int) *ManifestDependencySpec {
	return &ManifestDependencySpec{name: name, versionReq: versionReq, path: path, git: git, section: section, line: line}
}

// Osty: /tmp/manifest_validate_core.osty:595:5
func manifestDiagnosticSpec(severity string, code string, message string, line int, hint string) *ManifestDiagnosticSpec {
	return &ManifestDiagnosticSpec{severity: severity, code: code, message: message, line: manifestLine(line), hint: hint}
}

// Osty: /tmp/manifest_validate_core.osty:605:5
func manifestSpec(pkg *ManifestPackageSpec, workspace *ManifestWorkspaceSpec, profiles []*ManifestProfileSpec, targets []*ManifestTargetSpec, defaultFeatures []string, features []*FeatureSpec) *ManifestSpec {
	return manifestSpecWithDeps(pkg, workspace, make([]*ManifestDependencySpec, 0, 1), make([]*ManifestDependencySpec, 0, 1), profiles, targets, defaultFeatures, features)
}

// Osty: /tmp/manifest_validate_core.osty:616:5
func manifestSpecWithDeps(pkg *ManifestPackageSpec, workspace *ManifestWorkspaceSpec, dependencies []*ManifestDependencySpec, devDependencies []*ManifestDependencySpec, profiles []*ManifestProfileSpec, targets []*ManifestTargetSpec, defaultFeatures []string, features []*FeatureSpec) *ManifestSpec {
	return &ManifestSpec{pkg: pkg, workspace: workspace, dependencies: dependencies, devDependencies: devDependencies, profiles: profiles, targets: targets, defaultFeatures: defaultFeatures, features: features}
}

// Osty: /tmp/manifest_validate_core.osty:629:5
func emptyManifestValidation() *ManifestValidation {
	return &ManifestValidation{missingRoots: 0, missingPackageNames: 0, badPackageNames: 0, missingPackageVersions: 0, badPackageVersions: 0, missingEditions: 0, unknownEditions: 0, emptyWorkspaces: 0, badProfileOptLevels: 0, unknownProfileBases: 0, profileCycles: 0, badTargets: 0, badDependencyVersions: 0, features: emptyFeatureValidation()}
}

// Osty: /tmp/manifest_validate_core.osty:649:5
func validateManifestSpec(spec *ManifestSpec) *ManifestValidation {
	// Osty: /tmp/manifest_validate_core.osty:650:5
	out := emptyManifestValidation()
	_ = out
	// Osty: /tmp/manifest_validate_core.osty:651:5
	if !(spec.pkg.present) && !(spec.workspace.present) {
		// Osty: /tmp/manifest_validate_core.osty:652:12
		out.missingRoots = func() int {
			var _p32 int = out.missingRoots
			var _rhs33 int = 1
			if _rhs33 > 0 && _p32 > math.MaxInt-_rhs33 {
				panic("integer overflow")
			}
			if _rhs33 < 0 && _p32 < math.MinInt-_rhs33 {
				panic("integer overflow")
			}
			return _p32 + _rhs33
		}()
		// Osty: /tmp/manifest_validate_core.osty:653:9
		return out
	}
	// Osty: /tmp/manifest_validate_core.osty:656:5
	if spec.pkg.present {
		// Osty: /tmp/manifest_validate_core.osty:657:9
		if spec.pkg.name == "" {
			// Osty: /tmp/manifest_validate_core.osty:658:16
			out.missingPackageNames = func() int {
				var _p34 int = out.missingPackageNames
				var _rhs35 int = 1
				if _rhs35 > 0 && _p34 > math.MaxInt-_rhs35 {
					panic("integer overflow")
				}
				if _rhs35 < 0 && _p34 < math.MinInt-_rhs35 {
					panic("integer overflow")
				}
				return _p34 + _rhs35
			}()
		} else if !(manifestPackageNameValid(spec.pkg.name)) {
			// Osty: /tmp/manifest_validate_core.osty:660:16
			out.badPackageNames = func() int {
				var _p36 int = out.badPackageNames
				var _rhs37 int = 1
				if _rhs37 > 0 && _p36 > math.MaxInt-_rhs37 {
					panic("integer overflow")
				}
				if _rhs37 < 0 && _p36 < math.MinInt-_rhs37 {
					panic("integer overflow")
				}
				return _p36 + _rhs37
			}()
		}
		// Osty: /tmp/manifest_validate_core.osty:663:9
		if spec.pkg.version == "" {
			// Osty: /tmp/manifest_validate_core.osty:664:16
			out.missingPackageVersions = func() int {
				var _p38 int = out.missingPackageVersions
				var _rhs39 int = 1
				if _rhs39 > 0 && _p38 > math.MaxInt-_rhs39 {
					panic("integer overflow")
				}
				if _rhs39 < 0 && _p38 < math.MinInt-_rhs39 {
					panic("integer overflow")
				}
				return _p38 + _rhs39
			}()
		} else if !(manifestPackageVersionValid(spec.pkg.version)) {
			// Osty: /tmp/manifest_validate_core.osty:666:16
			out.badPackageVersions = func() int {
				var _p40 int = out.badPackageVersions
				var _rhs41 int = 1
				if _rhs41 > 0 && _p40 > math.MaxInt-_rhs41 {
					panic("integer overflow")
				}
				if _rhs41 < 0 && _p40 < math.MinInt-_rhs41 {
					panic("integer overflow")
				}
				return _p40 + _rhs41
			}()
		}
		// Osty: /tmp/manifest_validate_core.osty:669:9
		if spec.pkg.edition == "" {
			// Osty: /tmp/manifest_validate_core.osty:670:16
			out.missingEditions = func() int {
				var _p42 int = out.missingEditions
				var _rhs43 int = 1
				if _rhs43 > 0 && _p42 > math.MaxInt-_rhs43 {
					panic("integer overflow")
				}
				if _rhs43 < 0 && _p42 < math.MinInt-_rhs43 {
					panic("integer overflow")
				}
				return _p42 + _rhs43
			}()
		} else if !(manifestEditionKnown(spec.pkg.edition)) {
			// Osty: /tmp/manifest_validate_core.osty:672:16
			out.unknownEditions = func() int {
				var _p44 int = out.unknownEditions
				var _rhs45 int = 1
				if _rhs45 > 0 && _p44 > math.MaxInt-_rhs45 {
					panic("integer overflow")
				}
				if _rhs45 < 0 && _p44 < math.MinInt-_rhs45 {
					panic("integer overflow")
				}
				return _p44 + _rhs45
			}()
		}
	}
	// Osty: /tmp/manifest_validate_core.osty:676:5
	if spec.workspace.present && len(spec.workspace.members) == 0 {
		// Osty: /tmp/manifest_validate_core.osty:677:12
		out.emptyWorkspaces = func() int {
			var _p46 int = out.emptyWorkspaces
			var _rhs47 int = 1
			if _rhs47 > 0 && _p46 > math.MaxInt-_rhs47 {
				panic("integer overflow")
			}
			if _rhs47 < 0 && _p46 < math.MinInt-_rhs47 {
				panic("integer overflow")
			}
			return _p46 + _rhs47
		}()
	}
	// Osty: /tmp/manifest_validate_core.osty:680:5
	out = validateManifestProfiles(spec.profiles, out)
	// Osty: /tmp/manifest_validate_core.osty:681:5
	out = validateManifestTargets(spec.targets, out)
	// Osty: /tmp/manifest_validate_core.osty:682:5
	out = validateManifestDependencies(spec.dependencies, out)
	// Osty: /tmp/manifest_validate_core.osty:683:5
	out = validateManifestDependencies(spec.devDependencies, out)
	// Osty: /tmp/manifest_validate_core.osty:684:8
	out.features = validateFeatureGraph(spec.defaultFeatures, spec.features)
	return out
}

// Osty: /tmp/manifest_validate_core.osty:689:5
func validateManifestDiagnostics(spec *ManifestSpec) []*ManifestDiagnosticSpec {
	// Osty: /tmp/manifest_validate_core.osty:690:5
	var out []*ManifestDiagnosticSpec = make([]*ManifestDiagnosticSpec, 0, 1)
	_ = out
	// Osty: /tmp/manifest_validate_core.osty:691:5
	if !(spec.pkg.present) && !(spec.workspace.present) {
		// Osty: /tmp/manifest_validate_core.osty:692:9
		func() struct{} {
			out = append(out, manifestError("E2010", "manifest defines neither [package] nor [workspace]", 1, ""))
			return struct{}{}
		}()
		// Osty: /tmp/manifest_validate_core.osty:698:9
		return out
	}
	// Osty: /tmp/manifest_validate_core.osty:701:5
	if spec.pkg.present {
		// Osty: /tmp/manifest_validate_core.osty:702:9
		if spec.pkg.name == "" {
			// Osty: /tmp/manifest_validate_core.osty:703:13
			func() struct{} {
				out = append(out, manifestError("E2011", "[package] missing required field `name`", spec.pkg.tableLine, ""))
				return struct{}{}
			}()
		} else if !(manifestPackageNameValid(spec.pkg.name)) {
			// Osty: /tmp/manifest_validate_core.osty:710:13
			func() struct{} {
				out = append(out, manifestError("E2014", fmt.Sprintf("package.name `%s` is not a valid identifier (must match [A-Za-z_][A-Za-z0-9_-]*)", ostyToString(spec.pkg.name)), spec.pkg.nameLine, ""))
				return struct{}{}
			}()
		}
		// Osty: /tmp/manifest_validate_core.osty:718:9
		if spec.pkg.version == "" {
			// Osty: /tmp/manifest_validate_core.osty:719:13
			func() struct{} {
				out = append(out, manifestError("E2011", "[package] missing required field `version`", spec.pkg.tableLine, ""))
				return struct{}{}
			}()
		} else if !(manifestPackageVersionValid(spec.pkg.version)) {
			// Osty: /tmp/manifest_validate_core.osty:726:13
			func() struct{} {
				out = append(out, manifestError("E2015", fmt.Sprintf("package.version `%s` is not a valid semver (want X.Y.Z)", ostyToString(spec.pkg.version)), spec.pkg.versionLine, ""))
				return struct{}{}
			}()
		}
		// Osty: /tmp/manifest_validate_core.osty:734:9
		if spec.pkg.edition == "" {
			// Osty: /tmp/manifest_validate_core.osty:735:13
			func() struct{} {
				out = append(out, manifestWarning("E2011", fmt.Sprintf("[package] missing `edition`; defaulting to %s", ostyToString(manifestCurrentEdition())), spec.pkg.tableLine, "add edition = \"0.4\" to pin the spec version"))
				return struct{}{}
			}()
		} else if !(manifestEditionKnown(spec.pkg.edition)) {
			// Osty: /tmp/manifest_validate_core.osty:742:13
			func() struct{} {
				out = append(out, manifestError("E2016", fmt.Sprintf("unknown edition `%s` (known: %s)", ostyToString(spec.pkg.edition), ostyToString(manifestKnownEditionsText())), spec.pkg.editionLine, ""))
				return struct{}{}
			}()
		}
	}
	// Osty: /tmp/manifest_validate_core.osty:751:5
	if spec.workspace.present && len(spec.workspace.members) == 0 {
		// Osty: /tmp/manifest_validate_core.osty:752:9
		func() struct{} {
			out = append(out, manifestError("E2018", "[workspace] has no `members` - a workspace must declare at least one member package", 1, ""))
			return struct{}{}
		}()
	}
	// Osty: /tmp/manifest_validate_core.osty:760:5
	out = manifestProfileDiagnostics(spec.profiles, out)
	// Osty: /tmp/manifest_validate_core.osty:761:5
	out = manifestTargetDiagnostics(spec.targets, out)
	// Osty: /tmp/manifest_validate_core.osty:762:5
	out = manifestDependencyDiagnostics(spec.dependencies, out)
	// Osty: /tmp/manifest_validate_core.osty:763:5
	out = manifestDependencyDiagnostics(spec.devDependencies, out)
	// Osty: /tmp/manifest_validate_core.osty:764:5
	out = manifestFeatureDiagnostics(spec.defaultFeatures, spec.features, out)
	return out
}

// Osty: /tmp/manifest_validate_core.osty:768:5
func manifestValidationErrorCount(v *ManifestValidation) int {
	// Osty: /tmp/manifest_validate_core.osty:769:5
	count := 0
	_ = count
	// Osty: /tmp/manifest_validate_core.osty:770:5
	func() {
		var _cur48 int = count
		var _rhs49 int = v.missingRoots
		if _rhs49 > 0 && _cur48 > math.MaxInt-_rhs49 {
			panic("integer overflow")
		}
		if _rhs49 < 0 && _cur48 < math.MinInt-_rhs49 {
			panic("integer overflow")
		}
		count = _cur48 + _rhs49
	}()
	// Osty: /tmp/manifest_validate_core.osty:771:5
	func() {
		var _cur50 int = count
		var _rhs51 int = v.missingPackageNames
		if _rhs51 > 0 && _cur50 > math.MaxInt-_rhs51 {
			panic("integer overflow")
		}
		if _rhs51 < 0 && _cur50 < math.MinInt-_rhs51 {
			panic("integer overflow")
		}
		count = _cur50 + _rhs51
	}()
	// Osty: /tmp/manifest_validate_core.osty:772:5
	func() {
		var _cur52 int = count
		var _rhs53 int = v.badPackageNames
		if _rhs53 > 0 && _cur52 > math.MaxInt-_rhs53 {
			panic("integer overflow")
		}
		if _rhs53 < 0 && _cur52 < math.MinInt-_rhs53 {
			panic("integer overflow")
		}
		count = _cur52 + _rhs53
	}()
	// Osty: /tmp/manifest_validate_core.osty:773:5
	func() {
		var _cur54 int = count
		var _rhs55 int = v.missingPackageVersions
		if _rhs55 > 0 && _cur54 > math.MaxInt-_rhs55 {
			panic("integer overflow")
		}
		if _rhs55 < 0 && _cur54 < math.MinInt-_rhs55 {
			panic("integer overflow")
		}
		count = _cur54 + _rhs55
	}()
	// Osty: /tmp/manifest_validate_core.osty:774:5
	func() {
		var _cur56 int = count
		var _rhs57 int = v.badPackageVersions
		if _rhs57 > 0 && _cur56 > math.MaxInt-_rhs57 {
			panic("integer overflow")
		}
		if _rhs57 < 0 && _cur56 < math.MinInt-_rhs57 {
			panic("integer overflow")
		}
		count = _cur56 + _rhs57
	}()
	// Osty: /tmp/manifest_validate_core.osty:775:5
	func() {
		var _cur58 int = count
		var _rhs59 int = v.unknownEditions
		if _rhs59 > 0 && _cur58 > math.MaxInt-_rhs59 {
			panic("integer overflow")
		}
		if _rhs59 < 0 && _cur58 < math.MinInt-_rhs59 {
			panic("integer overflow")
		}
		count = _cur58 + _rhs59
	}()
	// Osty: /tmp/manifest_validate_core.osty:776:5
	func() {
		var _cur60 int = count
		var _rhs61 int = v.emptyWorkspaces
		if _rhs61 > 0 && _cur60 > math.MaxInt-_rhs61 {
			panic("integer overflow")
		}
		if _rhs61 < 0 && _cur60 < math.MinInt-_rhs61 {
			panic("integer overflow")
		}
		count = _cur60 + _rhs61
	}()
	// Osty: /tmp/manifest_validate_core.osty:777:5
	func() {
		var _cur62 int = count
		var _rhs63 int = v.badProfileOptLevels
		if _rhs63 > 0 && _cur62 > math.MaxInt-_rhs63 {
			panic("integer overflow")
		}
		if _rhs63 < 0 && _cur62 < math.MinInt-_rhs63 {
			panic("integer overflow")
		}
		count = _cur62 + _rhs63
	}()
	// Osty: /tmp/manifest_validate_core.osty:778:5
	func() {
		var _cur64 int = count
		var _rhs65 int = v.unknownProfileBases
		if _rhs65 > 0 && _cur64 > math.MaxInt-_rhs65 {
			panic("integer overflow")
		}
		if _rhs65 < 0 && _cur64 < math.MinInt-_rhs65 {
			panic("integer overflow")
		}
		count = _cur64 + _rhs65
	}()
	// Osty: /tmp/manifest_validate_core.osty:779:5
	func() {
		var _cur66 int = count
		var _rhs67 int = v.profileCycles
		if _rhs67 > 0 && _cur66 > math.MaxInt-_rhs67 {
			panic("integer overflow")
		}
		if _rhs67 < 0 && _cur66 < math.MinInt-_rhs67 {
			panic("integer overflow")
		}
		count = _cur66 + _rhs67
	}()
	// Osty: /tmp/manifest_validate_core.osty:780:5
	func() {
		var _cur68 int = count
		var _rhs69 int = v.badTargets
		if _rhs69 > 0 && _cur68 > math.MaxInt-_rhs69 {
			panic("integer overflow")
		}
		if _rhs69 < 0 && _cur68 < math.MinInt-_rhs69 {
			panic("integer overflow")
		}
		count = _cur68 + _rhs69
	}()
	// Osty: /tmp/manifest_validate_core.osty:781:5
	func() {
		var _cur70 int = count
		var _rhs71 int = v.badDependencyVersions
		if _rhs71 > 0 && _cur70 > math.MaxInt-_rhs71 {
			panic("integer overflow")
		}
		if _rhs71 < 0 && _cur70 < math.MinInt-_rhs71 {
			panic("integer overflow")
		}
		count = _cur70 + _rhs71
	}()
	// Osty: /tmp/manifest_validate_core.osty:782:5
	func() {
		var _cur72 int = count
		var _rhs73 int = v.features.undefinedDefault
		if _rhs73 > 0 && _cur72 > math.MaxInt-_rhs73 {
			panic("integer overflow")
		}
		if _rhs73 < 0 && _cur72 < math.MinInt-_rhs73 {
			panic("integer overflow")
		}
		count = _cur72 + _rhs73
	}()
	// Osty: /tmp/manifest_validate_core.osty:783:5
	func() {
		var _cur74 int = count
		var _rhs75 int = v.features.selfReferences
		if _rhs75 > 0 && _cur74 > math.MaxInt-_rhs75 {
			panic("integer overflow")
		}
		if _rhs75 < 0 && _cur74 < math.MinInt-_rhs75 {
			panic("integer overflow")
		}
		count = _cur74 + _rhs75
	}()
	return count
}

// Osty: /tmp/manifest_validate_core.osty:787:5
func manifestValidationWarningCount(v *ManifestValidation) int {
	return v.missingEditions
}

// Osty: /tmp/manifest_validate_core.osty:791:5
func manifestPackageNameValid(name string) bool {
	// Osty: /tmp/manifest_validate_core.osty:792:5
	if name == "" {
		// Osty: /tmp/manifest_validate_core.osty:793:9
		return false
	}
	// Osty: /tmp/manifest_validate_core.osty:795:5
	index := 0
	_ = index
	// Osty: /tmp/manifest_validate_core.osty:796:5
	for _, unit := range strings.Split(name, "") {
		// Osty: /tmp/manifest_validate_core.osty:797:9
		if index == 0 {
			// Osty: /tmp/manifest_validate_core.osty:798:13
			if !(manifestPackageNameStart(unit)) {
				// Osty: /tmp/manifest_validate_core.osty:799:17
				return false
			}
		} else if !(manifestPackageNameUnit(unit)) {
			// Osty: /tmp/manifest_validate_core.osty:802:13
			return false
		}
		// Osty: /tmp/manifest_validate_core.osty:804:9
		func() {
			var _cur76 int = index
			var _rhs77 int = 1
			if _rhs77 > 0 && _cur76 > math.MaxInt-_rhs77 {
				panic("integer overflow")
			}
			if _rhs77 < 0 && _cur76 < math.MinInt-_rhs77 {
				panic("integer overflow")
			}
			index = _cur76 + _rhs77
		}()
	}
	return true
}

// Osty: /tmp/manifest_validate_core.osty:809:5
func manifestPackageVersionValid(version string) bool {
	// Osty: /tmp/manifest_validate_core.osty:810:5
	if version == "" || strings.HasPrefix(version, "v") {
		// Osty: /tmp/manifest_validate_core.osty:811:9
		return false
	}
	// Osty: /tmp/manifest_validate_core.osty:814:5
	plus := splitSummary(strings.SplitN(version, "+", 2))
	_ = plus
	// Osty: /tmp/manifest_validate_core.osty:815:5
	if plus.count == 2 && !(buildIdentifiersValid(plus.second)) {
		// Osty: /tmp/manifest_validate_core.osty:816:9
		return false
	}
	// Osty: /tmp/manifest_validate_core.osty:819:5
	dash := splitSummary(strings.SplitN(plus.first, "-", 2))
	_ = dash
	// Osty: /tmp/manifest_validate_core.osty:820:5
	coreValid := false
	_ = coreValid
	// Osty: /tmp/manifest_validate_core.osty:821:5
	{
		_m78 := parseSemCore(dash.first)
		_ = _m78
		if _m78.IsOk {
			// Osty: /tmp/manifest_validate_core.osty:823:13
			coreValid = true
		}
		if !_m78.IsOk {
			// Osty: /tmp/manifest_validate_core.osty:826:13
			coreValid = false
		}
	}
	// Osty: /tmp/manifest_validate_core.osty:829:5
	if !(coreValid) {
		// Osty: /tmp/manifest_validate_core.osty:830:9
		return false
	}
	// Osty: /tmp/manifest_validate_core.osty:832:5
	if dash.count == 1 {
		// Osty: /tmp/manifest_validate_core.osty:833:9
		return true
	}
	return manifestVersionIdentifiersValid(dash.second)
}

// Osty: /tmp/manifest_validate_core.osty:838:5
func manifestEditionKnown(edition string) bool {
	return edition == "0.3" || edition == "0.4"
}

// Osty: /tmp/manifest_validate_core.osty:842:5
func manifestTargetTripleValid(triple string) bool {
	// Osty: /tmp/manifest_validate_core.osty:843:5
	parts := splitSummary(strings.SplitN(triple, "-", 2))
	_ = parts
	return parts.count == 2 && parts.first != "" && parts.second != ""
}

// Osty: /tmp/manifest_validate_core.osty:847:5
func manifestProfileExists(name string, profiles []*ManifestProfileSpec) bool {
	// Osty: /tmp/manifest_validate_core.osty:848:5
	for _, profile := range profiles {
		// Osty: /tmp/manifest_validate_core.osty:849:9
		if profile.name == name {
			// Osty: /tmp/manifest_validate_core.osty:850:13
			return true
		}
	}
	return false
}

// Osty: /tmp/manifest_validate_core.osty:856:5
func manifestVersionReqValid(req string) bool {
	// Osty: /tmp/manifest_validate_core.osty:857:5
	text := strings.TrimSpace(req)
	_ = text
	// Osty: /tmp/manifest_validate_core.osty:858:5
	if text == "" {
		// Osty: /tmp/manifest_validate_core.osty:859:9
		return false
	}
	// Osty: /tmp/manifest_validate_core.osty:861:5
	if text == "*" {
		// Osty: /tmp/manifest_validate_core.osty:862:9
		return true
	}
	// Osty: /tmp/manifest_validate_core.osty:864:5
	for _, part := range strings.Fields(text) {
		// Osty: /tmp/manifest_validate_core.osty:865:9
		if !(manifestVersionReqPartValid(part)) {
			// Osty: /tmp/manifest_validate_core.osty:866:13
			return false
		}
	}
	return true
}

// Osty: /tmp/manifest_validate_core.osty:872:1
func validateManifestProfiles(profiles []*ManifestProfileSpec, validation *ManifestValidation) *ManifestValidation {
	// Osty: /tmp/manifest_validate_core.osty:876:5
	out := validation
	_ = out
	// Osty: /tmp/manifest_validate_core.osty:877:5
	for _, profile := range profiles {
		// Osty: /tmp/manifest_validate_core.osty:878:9
		if profile.hasOptLevel && (profile.optLevel < 0 || profile.optLevel > 3) {
			// Osty: /tmp/manifest_validate_core.osty:879:16
			out.badProfileOptLevels = func() int {
				var _p79 int = out.badProfileOptLevels
				var _rhs80 int = 1
				if _rhs80 > 0 && _p79 > math.MaxInt-_rhs80 {
					panic("integer overflow")
				}
				if _rhs80 < 0 && _p79 < math.MinInt-_rhs80 {
					panic("integer overflow")
				}
				return _p79 + _rhs80
			}()
		}
		// Osty: /tmp/manifest_validate_core.osty:881:9
		if profile.inherits != "" && !(manifestBuiltinProfile(profile.inherits)) && !(manifestProfileExists(profile.inherits, profiles)) {
			// Osty: /tmp/manifest_validate_core.osty:884:16
			out.unknownProfileBases = func() int {
				var _p81 int = out.unknownProfileBases
				var _rhs82 int = 1
				if _rhs82 > 0 && _p81 > math.MaxInt-_rhs82 {
					panic("integer overflow")
				}
				if _rhs82 < 0 && _p81 < math.MinInt-_rhs82 {
					panic("integer overflow")
				}
				return _p81 + _rhs82
			}()
		}
	}
	// Osty: /tmp/manifest_validate_core.osty:888:5
	for _, profile := range profiles {
		// Osty: /tmp/manifest_validate_core.osty:889:9
		if manifestProfileHasCycle(profile.name, profiles) {
			// Osty: /tmp/manifest_validate_core.osty:890:16
			out.profileCycles = func() int {
				var _p83 int = out.profileCycles
				var _rhs84 int = 1
				if _rhs84 > 0 && _p83 > math.MaxInt-_rhs84 {
					panic("integer overflow")
				}
				if _rhs84 < 0 && _p83 < math.MinInt-_rhs84 {
					panic("integer overflow")
				}
				return _p83 + _rhs84
			}()
		}
	}
	return out
}

// Osty: /tmp/manifest_validate_core.osty:896:1
func validateManifestTargets(targets []*ManifestTargetSpec, validation *ManifestValidation) *ManifestValidation {
	// Osty: /tmp/manifest_validate_core.osty:900:5
	out := validation
	_ = out
	// Osty: /tmp/manifest_validate_core.osty:901:5
	for _, target := range targets {
		// Osty: /tmp/manifest_validate_core.osty:902:9
		if !(manifestTargetTripleValid(target.triple)) {
			// Osty: /tmp/manifest_validate_core.osty:903:16
			out.badTargets = func() int {
				var _p85 int = out.badTargets
				var _rhs86 int = 1
				if _rhs86 > 0 && _p85 > math.MaxInt-_rhs86 {
					panic("integer overflow")
				}
				if _rhs86 < 0 && _p85 < math.MinInt-_rhs86 {
					panic("integer overflow")
				}
				return _p85 + _rhs86
			}()
		}
	}
	return out
}

// Osty: /tmp/manifest_validate_core.osty:909:1
func validateManifestDependencies(deps []*ManifestDependencySpec, validation *ManifestValidation) *ManifestValidation {
	// Osty: /tmp/manifest_validate_core.osty:913:5
	out := validation
	_ = out
	// Osty: /tmp/manifest_validate_core.osty:914:5
	for _, dep := range deps {
		// Osty: /tmp/manifest_validate_core.osty:915:9
		if dep.path == "" && dep.git == "" && dep.versionReq != "" && dep.versionReq != "*" {
			// Osty: /tmp/manifest_validate_core.osty:916:13
			if !(manifestVersionReqValid(dep.versionReq)) {
				// Osty: /tmp/manifest_validate_core.osty:917:20
				out.badDependencyVersions = func() int {
					var _p87 int = out.badDependencyVersions
					var _rhs88 int = 1
					if _rhs88 > 0 && _p87 > math.MaxInt-_rhs88 {
						panic("integer overflow")
					}
					if _rhs88 < 0 && _p87 < math.MinInt-_rhs88 {
						panic("integer overflow")
					}
					return _p87 + _rhs88
				}()
			}
		}
	}
	return out
}

// Osty: /tmp/manifest_validate_core.osty:924:1
func manifestError(code string, message string, line int, hint string) *ManifestDiagnosticSpec {
	return manifestDiagnosticSpec("error", code, message, line, hint)
}

// Osty: /tmp/manifest_validate_core.osty:933:1
func manifestWarning(code string, message string, line int, hint string) *ManifestDiagnosticSpec {
	return manifestDiagnosticSpec("warning", code, message, line, hint)
}

// Osty: /tmp/manifest_validate_core.osty:942:1
func manifestLine(line int) int {
	// Osty: /tmp/manifest_validate_core.osty:943:5
	if line > 0 {
		// Osty: /tmp/manifest_validate_core.osty:944:9
		return line
	}
	return 1
}

// Osty: /tmp/manifest_validate_core.osty:949:1
func manifestCurrentEdition() string {
	return "0.4"
}

// Osty: /tmp/manifest_validate_core.osty:953:1
func manifestKnownEditionsText() string {
	return "0.3, 0.4"
}

// Osty: /tmp/manifest_validate_core.osty:957:1
func manifestProfileDiagnostics(profiles []*ManifestProfileSpec, diagnostics []*ManifestDiagnosticSpec) []*ManifestDiagnosticSpec {
	// Osty: /tmp/manifest_validate_core.osty:961:5
	out := diagnostics
	_ = out
	// Osty: /tmp/manifest_validate_core.osty:962:5
	for _, profile := range profiles {
		// Osty: /tmp/manifest_validate_core.osty:963:9
		if profile.hasOptLevel && (profile.optLevel < 0 || profile.optLevel > 3) {
			// Osty: /tmp/manifest_validate_core.osty:964:13
			func() struct{} {
				out = append(out, manifestError("E2013", fmt.Sprintf("profile.%s.opt-level %s out of range (want 0-3)", ostyToString(profile.name), ostyToString(profile.optLevel)), profile.line, ""))
				return struct{}{}
			}()
		}
		// Osty: /tmp/manifest_validate_core.osty:971:9
		if profile.inherits != "" && !(manifestBuiltinProfile(profile.inherits)) && !(manifestProfileExists(profile.inherits, profiles)) {
			// Osty: /tmp/manifest_validate_core.osty:974:13
			func() struct{} {
				out = append(out, manifestError("E2017", fmt.Sprintf("profile.%s.inherits = \"{profile.inherits}\": unknown base profile", ostyToString(profile.name)), profile.line, "must be a built-in (debug, release, profile, test) or a manifest-declared profile"))
				return struct{}{}
			}()
		}
	}
	// Osty: /tmp/manifest_validate_core.osty:983:5
	for _, profile := range profiles {
		// Osty: /tmp/manifest_validate_core.osty:984:9
		if manifestProfileHasCycle(profile.name, profiles) {
			// Osty: /tmp/manifest_validate_core.osty:985:13
			func() struct{} {
				out = append(out, manifestError("E2017", fmt.Sprintf("profile.%s: inherits chain forms a cycle", ostyToString(profile.name)), profile.line, ""))
				return struct{}{}
			}()
		}
	}
	return out
}

// Osty: /tmp/manifest_validate_core.osty:996:1
func manifestTargetDiagnostics(targets []*ManifestTargetSpec, diagnostics []*ManifestDiagnosticSpec) []*ManifestDiagnosticSpec {
	// Osty: /tmp/manifest_validate_core.osty:1000:5
	out := diagnostics
	_ = out
	// Osty: /tmp/manifest_validate_core.osty:1001:5
	for _, target := range targets {
		// Osty: /tmp/manifest_validate_core.osty:1002:9
		if !(manifestTargetTripleValid(target.triple)) {
			// Osty: /tmp/manifest_validate_core.osty:1003:13
			func() struct{} {
				out = append(out, manifestError("E2017", fmt.Sprintf("target.%s: triple must be <arch>-<os>", ostyToString(target.triple)), target.line, "examples: amd64-linux, arm64-darwin, wasm-js"))
				return struct{}{}
			}()
		}
	}
	return out
}

// Osty: /tmp/manifest_validate_core.osty:1014:1
func manifestDependencyDiagnostics(deps []*ManifestDependencySpec, diagnostics []*ManifestDiagnosticSpec) []*ManifestDiagnosticSpec {
	// Osty: /tmp/manifest_validate_core.osty:1018:5
	out := diagnostics
	_ = out
	// Osty: /tmp/manifest_validate_core.osty:1019:5
	for _, dep := range deps {
		// Osty: /tmp/manifest_validate_core.osty:1020:9
		if dep.path == "" && dep.git == "" && dep.versionReq != "" && dep.versionReq != "*" {
			// Osty: /tmp/manifest_validate_core.osty:1021:13
			if !(manifestVersionReqValid(dep.versionReq)) {
				// Osty: /tmp/manifest_validate_core.osty:1022:17
				func() struct{} {
					out = append(out, manifestError("E2017", fmt.Sprintf("%s.%s has invalid version requirement \"{dep.versionReq}\"", ostyToString(dep.section), ostyToString(dep.name)), dep.line, "examples: \"1.2.3\", \"^1.0\", \">=1.0, <2\", \"*\""))
					return struct{}{}
				}()
			}
		}
	}
	return out
}

// Osty: /tmp/manifest_validate_core.osty:1034:1
func manifestFeatureDiagnostics(defaults []string, features []*FeatureSpec, diagnostics []*ManifestDiagnosticSpec) []*ManifestDiagnosticSpec {
	// Osty: /tmp/manifest_validate_core.osty:1039:5
	out := diagnostics
	_ = out
	// Osty: /tmp/manifest_validate_core.osty:1040:5
	for _, name := range defaults {
		// Osty: /tmp/manifest_validate_core.osty:1041:9
		if !(featureExists(name, features)) {
			// Osty: /tmp/manifest_validate_core.osty:1042:13
			func() struct{} {
				out = append(out, manifestError("E2017", "features.default references undefined feature \"{name}\"", 1, ""))
				return struct{}{}
			}()
		}
	}
	// Osty: /tmp/manifest_validate_core.osty:1050:5
	for _, feature := range features {
		// Osty: /tmp/manifest_validate_core.osty:1051:9
		for _, dep := range feature.deps {
			// Osty: /tmp/manifest_validate_core.osty:1052:13
			if dep == feature.name {
				// Osty: /tmp/manifest_validate_core.osty:1053:17
				func() struct{} {
					out = append(out, manifestError("E2017", fmt.Sprintf("features.%s lists itself", ostyToString(feature.name)), 1, ""))
					return struct{}{}
				}()
			}
		}
	}
	return out
}

// Osty: /tmp/manifest_validate_core.osty:1065:1
func manifestPackageNameStart(unit string) bool {
	return (unit >= "A" && unit <= "Z") || (unit >= "a" && unit <= "z") || unit == "_"
}

// Osty: /tmp/manifest_validate_core.osty:1069:1
func manifestPackageNameUnit(unit string) bool {
	return manifestPackageNameStart(unit) || (unit >= "0" && unit <= "9") || unit == "-"
}

// Osty: /tmp/manifest_validate_core.osty:1073:1
func manifestVersionIdentifiersValid(text string) bool {
	// Osty: /tmp/manifest_validate_core.osty:1074:5
	if text == "" {
		// Osty: /tmp/manifest_validate_core.osty:1075:9
		return false
	}
	// Osty: /tmp/manifest_validate_core.osty:1077:5
	for _, part := range strings.Split(text, ".") {
		// Osty: /tmp/manifest_validate_core.osty:1078:9
		if !(identifierTextValid(part)) {
			// Osty: /tmp/manifest_validate_core.osty:1079:13
			return false
		}
	}
	return true
}

// Osty: /tmp/manifest_validate_core.osty:1085:1
func manifestVersionReqPartValid(part string) bool {
	// Osty: /tmp/manifest_validate_core.osty:1086:5
	if strings.HasPrefix(part, "^") {
		// Osty: /tmp/manifest_validate_core.osty:1087:9
		return manifestPartialVersionValid(manifestTrimPrefix1(part))
	}
	// Osty: /tmp/manifest_validate_core.osty:1089:5
	if strings.HasPrefix(part, "~") {
		// Osty: /tmp/manifest_validate_core.osty:1090:9
		return manifestPartialVersionValid(manifestTrimPrefix1(part))
	}
	// Osty: /tmp/manifest_validate_core.osty:1092:5
	if strings.Contains(part, "*") {
		// Osty: /tmp/manifest_validate_core.osty:1093:9
		return manifestWildcardReqValid(part)
	}
	// Osty: /tmp/manifest_validate_core.osty:1095:5
	split := manifestSplitReqOp(part)
	_ = split
	return manifestPartialVersionValid(split.second)
}

// Osty: /tmp/manifest_validate_core.osty:1099:1
func manifestPartialVersionValid(version string) bool {
	// Osty: /tmp/manifest_validate_core.osty:1100:5
	if version == "" {
		// Osty: /tmp/manifest_validate_core.osty:1101:9
		return false
	}
	// Osty: /tmp/manifest_validate_core.osty:1103:5
	text := func() string {
		if strings.HasPrefix(version, "v") {
			return manifestTrimPrefix1(version)
		} else {
			return version
		}
	}()
	_ = text
	// Osty: /tmp/manifest_validate_core.osty:1108:5
	if text == "" {
		// Osty: /tmp/manifest_validate_core.osty:1109:9
		return false
	}
	// Osty: /tmp/manifest_validate_core.osty:1112:5
	plus := splitSummary(strings.SplitN(text, "+", 2))
	_ = plus
	// Osty: /tmp/manifest_validate_core.osty:1113:5
	dash := splitSummary(strings.SplitN(plus.first, "-", 2))
	_ = dash
	// Osty: /tmp/manifest_validate_core.osty:1114:5
	parts := splitSummary(strings.Split(dash.first, "."))
	_ = parts
	// Osty: /tmp/manifest_validate_core.osty:1115:5
	if parts.count < 1 || parts.count > 3 {
		// Osty: /tmp/manifest_validate_core.osty:1116:9
		return false
	}
	// Osty: /tmp/manifest_validate_core.osty:1118:5
	if !(manifestReqNumberValid(parts.first)) {
		// Osty: /tmp/manifest_validate_core.osty:1119:9
		return false
	}
	// Osty: /tmp/manifest_validate_core.osty:1121:5
	if parts.count >= 2 && !(manifestReqNumberValid(parts.second)) {
		// Osty: /tmp/manifest_validate_core.osty:1122:9
		return false
	}
	// Osty: /tmp/manifest_validate_core.osty:1124:5
	if parts.count >= 3 && !(manifestReqNumberValid(parts.third)) {
		// Osty: /tmp/manifest_validate_core.osty:1125:9
		return false
	}
	return true
}

// Osty: /tmp/manifest_validate_core.osty:1130:1
func manifestWildcardReqValid(req string) bool {
	// Osty: /tmp/manifest_validate_core.osty:1131:5
	if req == "*" {
		// Osty: /tmp/manifest_validate_core.osty:1132:9
		return true
	}
	// Osty: /tmp/manifest_validate_core.osty:1134:5
	parts := splitSummary(strings.Split(req, "."))
	_ = parts
	// Osty: /tmp/manifest_validate_core.osty:1135:5
	if parts.count > 3 {
		// Osty: /tmp/manifest_validate_core.osty:1136:9
		return false
	}
	// Osty: /tmp/manifest_validate_core.osty:1139:5
	starAt := manifestWildcardIndex(parts)
	_ = starAt
	// Osty: /tmp/manifest_validate_core.osty:1140:5
	if starAt < 0 {
		// Osty: /tmp/manifest_validate_core.osty:1141:9
		return false
	}
	// Osty: /tmp/manifest_validate_core.osty:1143:5
	if starAt == 0 {
		// Osty: /tmp/manifest_validate_core.osty:1144:9
		return manifestWildcardOrMissing(parts.second) && manifestWildcardOrMissing(parts.third)
	}
	// Osty: /tmp/manifest_validate_core.osty:1146:5
	if starAt == 1 {
		// Osty: /tmp/manifest_validate_core.osty:1147:9
		return manifestReqNumberValid(parts.first) && manifestWildcardOrMissing(parts.second) && manifestWildcardOrMissing(parts.third)
	}
	return manifestReqNumberValid(parts.first) && manifestReqNumberValid(parts.second) && manifestWildcardOrMissing(parts.third)
}

// Osty: /tmp/manifest_validate_core.osty:1152:1
func manifestWildcardIndex(parts *SemSplit) int {
	// Osty: /tmp/manifest_validate_core.osty:1153:5
	if manifestWildcardUnit(parts.first) {
		// Osty: /tmp/manifest_validate_core.osty:1154:9
		return 0
	}
	// Osty: /tmp/manifest_validate_core.osty:1156:5
	if parts.count >= 2 && manifestWildcardUnit(parts.second) {
		// Osty: /tmp/manifest_validate_core.osty:1157:9
		return 1
	}
	// Osty: /tmp/manifest_validate_core.osty:1159:5
	if parts.count >= 3 && manifestWildcardUnit(parts.third) {
		// Osty: /tmp/manifest_validate_core.osty:1160:9
		return 2
	}
	// Osty: /tmp/manifest_validate_core.osty:1162:5
	return -1
}

// Osty: /tmp/manifest_validate_core.osty:1165:1
func manifestWildcardUnit(unit string) bool {
	return unit == "*" || unit == "x" || unit == "X"
}

// Osty: /tmp/manifest_validate_core.osty:1169:1
func manifestWildcardOrMissing(unit string) bool {
	return unit == "" || manifestWildcardUnit(unit)
}

// Osty: /tmp/manifest_validate_core.osty:1173:1
func manifestReqNumberValid(text string) bool {
	return func() bool {
		_m89 := parseSemNumber(text)
		_ = _m89
		if _m89.IsOk {
			return true
		}
		if !_m89.IsOk {
			return false
		}
		panic("unreachable match")
	}()
}

// Osty: /tmp/manifest_validate_core.osty:1180:1
func manifestSplitReqOp(part string) *SemSplit {
	// Osty: /tmp/manifest_validate_core.osty:1181:5
	if strings.HasPrefix(part, ">=") {
		// Osty: /tmp/manifest_validate_core.osty:1182:9
		return &SemSplit{count: 2, first: ">=", second: manifestTrimPrefixN(part, 2), third: ""}
	}
	// Osty: /tmp/manifest_validate_core.osty:1184:5
	if strings.HasPrefix(part, "<=") {
		// Osty: /tmp/manifest_validate_core.osty:1185:9
		return &SemSplit{count: 2, first: "<=", second: manifestTrimPrefixN(part, 2), third: ""}
	}
	// Osty: /tmp/manifest_validate_core.osty:1187:5
	if strings.HasPrefix(part, ">") {
		// Osty: /tmp/manifest_validate_core.osty:1188:9
		return &SemSplit{count: 2, first: ">", second: manifestTrimPrefix1(part), third: ""}
	}
	// Osty: /tmp/manifest_validate_core.osty:1190:5
	if strings.HasPrefix(part, "<") {
		// Osty: /tmp/manifest_validate_core.osty:1191:9
		return &SemSplit{count: 2, first: "<", second: manifestTrimPrefix1(part), third: ""}
	}
	// Osty: /tmp/manifest_validate_core.osty:1193:5
	if strings.HasPrefix(part, "=") {
		// Osty: /tmp/manifest_validate_core.osty:1194:9
		return &SemSplit{count: 2, first: "=", second: manifestTrimPrefix1(part), third: ""}
	}
	return &SemSplit{count: 1, first: "", second: part, third: ""}
}

// Osty: /tmp/manifest_validate_core.osty:1199:1
func manifestTrimPrefix1(text string) string {
	return manifestTrimPrefixN(text, 1)
}

// Osty: /tmp/manifest_validate_core.osty:1203:1
func manifestTrimPrefixN(text string, n int) string {
	// Osty: /tmp/manifest_validate_core.osty:1204:5
	units := strings.Split(text, "")
	_ = units
	// Osty: /tmp/manifest_validate_core.osty:1205:5
	var out []string = make([]string, 0, 1)
	_ = out
	// Osty: /tmp/manifest_validate_core.osty:1206:5
	i := 0
	_ = i
	// Osty: /tmp/manifest_validate_core.osty:1207:5
	for _, unit := range units {
		// Osty: /tmp/manifest_validate_core.osty:1208:9
		if i >= n {
			// Osty: /tmp/manifest_validate_core.osty:1209:13
			func() struct{} { out = append(out, unit); return struct{}{} }()
		}
		// Osty: /tmp/manifest_validate_core.osty:1211:9
		func() {
			var _cur90 int = i
			var _rhs91 int = 1
			if _rhs91 > 0 && _cur90 > math.MaxInt-_rhs91 {
				panic("integer overflow")
			}
			if _rhs91 < 0 && _cur90 < math.MinInt-_rhs91 {
				panic("integer overflow")
			}
			i = _cur90 + _rhs91
		}()
	}
	return strings.Join(out, "")
}

// Osty: /tmp/manifest_validate_core.osty:1216:1
func manifestBuiltinProfile(name string) bool {
	return name == "debug" || name == "release" || name == "profile" || name == "test"
}

// Osty: /tmp/manifest_validate_core.osty:1220:1
func manifestProfileHasCycle(name string, profiles []*ManifestProfileSpec) bool {
	return manifestProfileCycleVisit(name, profiles, make([]string, 0, 1))
}

// Osty: /tmp/manifest_validate_core.osty:1224:1
func manifestProfileCycleVisit(name string, profiles []*ManifestProfileSpec, stack []string) bool {
	// Osty: /tmp/manifest_validate_core.osty:1229:5
	if manifestBuiltinProfile(name) {
		// Osty: /tmp/manifest_validate_core.osty:1230:9
		return false
	}
	// Osty: /tmp/manifest_validate_core.osty:1232:5
	if manifestStringListContains(stack, name) {
		// Osty: /tmp/manifest_validate_core.osty:1233:9
		return true
	}
	// Osty: /tmp/manifest_validate_core.osty:1235:5
	for _, profile := range profiles {
		// Osty: /tmp/manifest_validate_core.osty:1236:9
		if profile.name == name {
			// Osty: /tmp/manifest_validate_core.osty:1237:13
			if profile.inherits == "" {
				// Osty: /tmp/manifest_validate_core.osty:1238:17
				return false
			}
			// Osty: /tmp/manifest_validate_core.osty:1240:13
			if manifestBuiltinProfile(profile.inherits) {
				// Osty: /tmp/manifest_validate_core.osty:1241:17
				return false
			}
			// Osty: /tmp/manifest_validate_core.osty:1243:13
			if !(manifestProfileExists(profile.inherits, profiles)) {
				// Osty: /tmp/manifest_validate_core.osty:1244:17
				return false
			}
			// Osty: /tmp/manifest_validate_core.osty:1246:13
			return manifestProfileCycleVisit(profile.inherits, profiles, manifestStringListAppended(stack, name))
		}
	}
	return false
}

// Osty: /tmp/manifest_validate_core.osty:1252:1
func manifestStringListContains(items []string, target string) bool {
	// Osty: /tmp/manifest_validate_core.osty:1253:5
	for _, item := range items {
		// Osty: /tmp/manifest_validate_core.osty:1254:9
		if item == target {
			// Osty: /tmp/manifest_validate_core.osty:1255:13
			return true
		}
	}
	return false
}

// Osty: /tmp/manifest_validate_core.osty:1261:1
func manifestStringListAppended(items []string, item string) []string {
	// Osty: /tmp/manifest_validate_core.osty:1262:5
	var out []string = make([]string, 0, 1)
	_ = out
	// Osty: /tmp/manifest_validate_core.osty:1263:5
	for _, existing := range items {
		// Osty: /tmp/manifest_validate_core.osty:1264:9
		func() struct{} { out = append(out, existing); return struct{}{} }()
	}
	// Osty: /tmp/manifest_validate_core.osty:1266:5
	func() struct{} { out = append(out, item); return struct{}{} }()
	return out
}
