// lockfile_policy.go is the Go snapshot of
// toolchain/lockfile_policy.osty. Osty is the source of truth;
// the drift test in this package keeps the two in sync.
package runner

import (
	"fmt"
	"sort"
	"strings"
)

// DependencyParts mirrors toolchain/lockfile_policy.osty's
// DependencyParts. Ok=false signals a malformed line; the
// host emits the precise `invalid dependency "..."` diagnostic.
//
// Osty: toolchain/lockfile_policy.osty:22
type DependencyParts struct {
	Name    string
	Version string
	Source  string
	Ok      bool
}

// DependencyString renders one lockfile entry as the canonical
// single-line form. Empty source → `<name> <version>`; otherwise
// `<name> <version> (<source>)`.
//
// Osty: toolchain/lockfile_policy.osty:36
func DependencyString(name, version, source string) string {
	if source == "" {
		return name + " " + version
	}
	return name + " " + version + " (" + source + ")"
}

// ParseDependency is the inverse of DependencyString. Returns
// Ok=false for malformed shapes (wrong field count, etc.); the
// host blames the line with `invalid dependency "..."`.
//
// Osty: toolchain/lockfile_policy.osty:51
func ParseDependency(line string) DependencyParts {
	trimmed := strings.TrimSpace(line)
	head := trimmed
	source := ""
	if strings.HasSuffix(trimmed, ")") {
		if open := strings.Index(trimmed, "("); open > 0 {
			source = trimmed[open+1 : len(trimmed)-1]
			head = strings.TrimSpace(trimmed[:open])
		}
	}
	parts := parseDependencyFields(head)
	if len(parts) != 2 {
		return DependencyParts{}
	}
	return DependencyParts{Name: parts[0], Version: parts[1], Source: source, Ok: true}
}

// parseDependencyFields splits `head` on runs of ASCII space /
// tab. Matches Go's `strings.Fields` for the lockfile's limited
// alphabet (names/versions never carry CR/LF/VT/FF).
//
// Osty: toolchain/lockfile_policy.osty:81
func parseDependencyFields(head string) []string {
	var out []string
	start := -1
	for i := 0; i < len(head); i++ {
		b := head[i]
		isWS := b == ' ' || b == '\t'
		if isWS {
			if start >= 0 {
				out = append(out, head[start:i])
				start = -1
			}
		} else if start < 0 {
			start = i
		}
	}
	if start >= 0 {
		out = append(out, head[start:])
	}
	return out
}

// LockDepSpec mirrors toolchain/lockfile_policy.osty's
// LockDepSpec — one in-memory dependency entry the host hands
// to MarshalLockfile.
//
// Osty: toolchain/lockfile_policy.osty:104
type LockDepSpec struct {
	Name    string
	Version string
	Source  string
}

// LockPackageSpec mirrors toolchain/lockfile_policy.osty's
// LockPackageSpec. Source and Checksum are empty strings when
// absent; the marshaller omits the corresponding lines.
//
// Osty: toolchain/lockfile_policy.osty:113
type LockPackageSpec struct {
	Name         string
	Version      string
	Source       string
	Checksum     string
	Dependencies []LockDepSpec
}

// MarshalLockfile renders a complete osty.lock document as
// deterministic TOML text. Packages are sorted by (Name, Version)
// and dependencies within each package by (Name, Version) so
// diffs stay small.
//
// Osty: toolchain/lockfile_policy.osty:127
func MarshalLockfile(version int, packages []LockPackageSpec) string {
	var b strings.Builder
	b.WriteString("# This file is auto-generated by osty.\n")
	b.WriteString("# Do not edit manually; `osty update` regenerates it.\n\n")
	fmt.Fprintf(&b, "version = %d\n", version)
	sortedPkgs := make([]LockPackageSpec, len(packages))
	copy(sortedPkgs, packages)
	sort.SliceStable(sortedPkgs, func(i, j int) bool {
		return lockSortKey(sortedPkgs[i].Name, sortedPkgs[i].Version) <
			lockSortKey(sortedPkgs[j].Name, sortedPkgs[j].Version)
	})
	for _, p := range sortedPkgs {
		b.WriteString("\n[[package]]\n")
		b.WriteString("name = ")
		b.WriteString(TomlBasicString(p.Name))
		b.WriteString("\n")
		b.WriteString("version = ")
		b.WriteString(TomlBasicString(p.Version))
		b.WriteString("\n")
		if p.Source != "" {
			b.WriteString("source = ")
			b.WriteString(TomlBasicString(p.Source))
			b.WriteString("\n")
		}
		if p.Checksum != "" {
			b.WriteString("checksum = ")
			b.WriteString(TomlBasicString(p.Checksum))
			b.WriteString("\n")
		}
		if len(p.Dependencies) > 0 {
			sortedDeps := make([]LockDepSpec, len(p.Dependencies))
			copy(sortedDeps, p.Dependencies)
			sort.SliceStable(sortedDeps, func(i, j int) bool {
				return lockSortKey(sortedDeps[i].Name, sortedDeps[i].Version) <
					lockSortKey(sortedDeps[j].Name, sortedDeps[j].Version)
			})
			b.WriteString("dependencies = [\n")
			for _, d := range sortedDeps {
				b.WriteString("    ")
				b.WriteString(TomlBasicString(DependencyString(d.Name, d.Version, d.Source)))
				b.WriteString(",\n")
			}
			b.WriteString("]\n")
		}
	}
	return b.String()
}

func lockSortKey(name, version string) string {
	return name + "\x00" + version
}

// TomlBasicString renders s as a TOML basic (double-quoted)
// string with Go `%q` escape semantics on the ASCII range. See
// toolchain/lockfile_policy.osty for the full table.
//
// Osty: toolchain/lockfile_policy.osty:172
func TomlBasicString(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case c == 0x22:
			b.WriteString("\\\"")
		case c == 0x5C:
			b.WriteString("\\\\")
		case c == 0x07:
			b.WriteString("\\a")
		case c == 0x08:
			b.WriteString("\\b")
		case c == 0x09:
			b.WriteString("\\t")
		case c == 0x0A:
			b.WriteString("\\n")
		case c == 0x0B:
			b.WriteString("\\v")
		case c == 0x0C:
			b.WriteString("\\f")
		case c == 0x0D:
			b.WriteString("\\r")
		case c >= 0x20 && c <= 0x7E:
			b.WriteByte(c)
		case c < 0x20 || c == 0x7F:
			b.WriteString("\\x")
			b.WriteString(twoHexLower(int(c)))
		default:
			b.WriteByte(c)
		}
	}
	b.WriteByte('"')
	return b.String()
}

const hexDigitsLower = "0123456789abcdef"

func twoHexLower(b int) string {
	hi := (b >> 4) & 0xF
	lo := b & 0xF
	return string(hexDigitsLower[hi]) + string(hexDigitsLower[lo])
}
