package runner

import (
	"strings"
	"testing"
)

func TestDependencyString(t *testing.T) {
	cases := []struct {
		name, version, source string
		want                  string
	}{
		{"serde", "1.2.3", "", "serde 1.2.3"},
		{"serde", "1.2.3", "git+https://github.com/x/y", "serde 1.2.3 (git+https://github.com/x/y)"},
	}
	for _, c := range cases {
		if got := DependencyString(c.name, c.version, c.source); got != c.want {
			t.Errorf("DependencyString = %q, want %q", got, c.want)
		}
	}
}

func TestParseDependency(t *testing.T) {
	cases := []struct {
		name        string
		in          string
		wantOk      bool
		wantName    string
		wantVersion string
		wantSource  string
	}{
		{"two-fields", "serde 1.2.3", true, "serde", "1.2.3", ""},
		{"with-source", "serde 1.2.3 (path:./vendor/serde)", true, "serde", "1.2.3", "path:./vendor/serde"},
		{"trims-leading-trailing", "  serde 1.2.3  ", true, "serde", "1.2.3", ""},
		{"reject-single-field", "serde", false, "", "", ""},
		{"reject-too-many-fields", "serde 1.2.3 extra", false, "", "", ""},
		{"reject-empty", "", false, "", "", ""},
		{"reject-whitespace-only", "   ", false, "", "", ""},
		{
			"source-with-embedded-parens",
			"crate 0.1.0 (registry+(local))",
			true, "crate", "0.1.0", "registry+(local)",
		},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			got := ParseDependency(c.in)
			if got.Ok != c.wantOk || got.Name != c.wantName ||
				got.Version != c.wantVersion || got.Source != c.wantSource {
				t.Errorf("ParseDependency(%q) = %+v, want {%q %q %q %v}",
					c.in, got, c.wantName, c.wantVersion, c.wantSource, c.wantOk)
			}
		})
	}
}

func TestParseDependencyRoundTrip(t *testing.T) {
	original := "tokio 1.5.0 (git+https://github.com/tokio-rs/tokio)"
	p := ParseDependency(original)
	if !p.Ok {
		t.Fatalf("parse failed for %q", original)
	}
	if got := DependencyString(p.Name, p.Version, p.Source); got != original {
		t.Errorf("round-trip = %q, want %q", got, original)
	}
}

func TestTomlBasicString(t *testing.T) {
	cases := []struct {
		name string
		in   string
		want string
	}{
		{"ascii", "serde", `"serde"`},
		{"empty", "", `""`},
		{"quote", `a"b`, `"a\"b"`},
		{"backslash", `a\b`, `"a\\b"`},
		{"newline", "\n", `"\n"`},
		{"tab", "\t", `"\t"`},
		{"return", "\r", `"\r"`},
		{"bell", "\x07", `"\a"`},
		{"backspace", "\x08", `"\b"`},
		{"vtab", "\x0B", `"\v"`},
		{"formfeed", "\x0C", `"\f"`},
		{"low-control", "\x01", `"\x01"`},
		{"del", "\x7f", `"\x7f"`},
		{"url", "https://x.io/v1?q=1", `"https://x.io/v1?q=1"`},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := TomlBasicString(c.in); got != c.want {
				t.Errorf("TomlBasicString(%q) = %q, want %q", c.in, got, c.want)
			}
		})
	}
}

func TestMarshalLockfileEmpty(t *testing.T) {
	got := MarshalLockfile(1, nil)
	want := "# This file is auto-generated by osty.\n# Do not edit manually; `osty update` regenerates it.\n\nversion = 1\n"
	if got != want {
		t.Errorf("MarshalLockfile(empty) =\n%q\nwant\n%q", got, want)
	}
}

func TestMarshalLockfileSinglePackageNoDeps(t *testing.T) {
	pkg := LockPackageSpec{
		Name:     "serde",
		Version:  "1.0.0",
		Source:   "registry+default",
		Checksum: "sha256:abc",
	}
	got := MarshalLockfile(1, []LockPackageSpec{pkg})
	want := "# This file is auto-generated by osty.\n# Do not edit manually; `osty update` regenerates it.\n\nversion = 1\n\n[[package]]\nname = \"serde\"\nversion = \"1.0.0\"\nsource = \"registry+default\"\nchecksum = \"sha256:abc\"\n"
	if got != want {
		t.Errorf("MarshalLockfile mismatch\n  got: %q\n want: %q", got, want)
	}
}

func TestMarshalLockfilePathSourceNoChecksum(t *testing.T) {
	pkg := LockPackageSpec{
		Name:    "local",
		Version: "0.1.0",
		Source:  "path+../local",
	}
	got := MarshalLockfile(1, []LockPackageSpec{pkg})
	if !strings.Contains(got, `source = "path+../local"`+"\n") {
		t.Errorf("missing source line: %q", got)
	}
	if strings.Contains(got, "checksum") {
		t.Errorf("path source should omit checksum line: %q", got)
	}
}

func TestMarshalLockfileSortsPackages(t *testing.T) {
	zed := LockPackageSpec{Name: "zed", Version: "1.0.0"}
	alpha := LockPackageSpec{Name: "alpha", Version: "0.1.0"}
	got := MarshalLockfile(1, []LockPackageSpec{zed, alpha})
	alphaAt := strings.Index(got, `name = "alpha"`)
	zedAt := strings.Index(got, `name = "zed"`)
	if alphaAt < 0 || zedAt < 0 || alphaAt > zedAt {
		t.Errorf("alpha (%d) should sort before zed (%d)\n%s", alphaAt, zedAt, got)
	}
}

func TestMarshalLockfileSortsDeps(t *testing.T) {
	pkg := LockPackageSpec{
		Name:    "root",
		Version: "1.0.0",
		Dependencies: []LockDepSpec{
			{Name: "zed", Version: "1.0.0"},
			{Name: "alpha", Version: "0.1.0"},
		},
	}
	got := MarshalLockfile(1, []LockPackageSpec{pkg})
	alphaAt := strings.Index(got, "alpha 0.1.0")
	zedAt := strings.Index(got, "zed 1.0.0")
	if alphaAt < 0 || zedAt < 0 || alphaAt > zedAt {
		t.Errorf("alpha (%d) should sort before zed (%d)\n%s", alphaAt, zedAt, got)
	}
}

func TestMarshalLockfileVersionTiebreak(t *testing.T) {
	v110 := LockPackageSpec{Name: "alpha", Version: "1.10.0"}
	v90 := LockPackageSpec{Name: "alpha", Version: "1.9.0"}
	got := MarshalLockfile(1, []LockPackageSpec{v90, v110})
	v110At := strings.Index(got, `version = "1.10.0"`)
	v90At := strings.Index(got, `version = "1.9.0"`)
	// 1.10.0 sorts BEFORE 1.9.0 lexicographically.
	if v110At < 0 || v90At < 0 || v110At > v90At {
		t.Errorf("1.10.0 (%d) should sort before 1.9.0 (%d)\n%s", v110At, v90At, got)
	}
}
