// Code generated by osty. DO NOT EDIT.
// Osty source: /tmp/pkgmgr_selfhost_merged.osty

package pkgmgr

import (
	"fmt"
	"math"
	pkgStrings "strings"
)

type ostyStringer interface {
	toString() string
}

func ostyToString(v any) string {
	if s, ok := v.(ostyStringer); ok {
		return s.toString()
	}
	if b, ok := v.([]byte); ok {
		return string(b)
	}
	return fmt.Sprint(v)
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:3:5
type SemPreIdent interface{ _isSemPreIdent() }
type SemPreIdent_PreNone struct{ _ref byte }

func (SemPreIdent_PreNone) _isSemPreIdent() {}

type SemPreIdent_PreNumber struct {
	F0 int
}

func (SemPreIdent_PreNumber) _isSemPreIdent() {}

type SemPreIdent_PreText struct {
	F0 string
}

func (SemPreIdent_PreText) _isSemPreIdent() {}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:15:5
type SemVersion struct {
	major int
	minor int
	patch int
	pre1  SemPreIdent
	pre2  SemPreIdent
	pre3  SemPreIdent
	build string
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:26:5
func preNone() SemPreIdent {
	return SemPreIdent(&SemPreIdent_PreNone{})
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:31:5
func preNumber(n int) SemPreIdent {
	return SemPreIdent(&SemPreIdent_PreNumber{F0: n})
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:36:5
func preText(s string) SemPreIdent {
	return SemPreIdent(&SemPreIdent_PreText{F0: s})
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:41:5
func semVersion(major int, minor int, patch int, pre1 SemPreIdent, pre2 SemPreIdent, pre3 SemPreIdent, build string) *SemVersion {
	return &SemVersion{major: major, minor: minor, patch: patch, pre1: pre1, pre2: pre2, pre3: pre3, build: build}
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:54:5
func stableVersion(major int, minor int, patch int) *SemVersion {
	return semVersion(major, minor, patch, preNone(), preNone(), preNone(), "")
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:59:5
// Osty: /tmp/pkgmgr_selfhost_merged.osty:64:5
// Osty: /tmp/pkgmgr_selfhost_merged.osty:75:5
// Osty: /tmp/pkgmgr_selfhost_merged.osty:80:5
func isSemPrerelease(v *SemVersion) bool {
	return func() bool {
		_m1 := v.pre1
		_ = _m1
		if func() bool { _, ok := _m1.(*SemPreIdent_PreNone); return ok }() {
			return false
		}
		{
			return true
		}
	}()
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:88:5
func compareSemVersion(a *SemVersion, b *SemVersion) int {
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:89:5
	major := signInt(a.major, b.major)
	_ = major
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:90:5
	if major != 0 {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:91:9
		return major
	}
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:94:5
	minor := signInt(a.minor, b.minor)
	_ = minor
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:95:5
	if minor != 0 {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:96:9
		return minor
	}
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:99:5
	patch := signInt(a.patch, b.patch)
	_ = patch
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:100:5
	if patch != 0 {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:101:9
		return patch
	}
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:104:5
	aPre := isSemPrerelease(a)
	_ = aPre
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:105:5
	bPre := isSemPrerelease(b)
	_ = bPre
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:106:5
	if !(aPre) && !(bPre) {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:107:9
		return 0
	}
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:109:5
	if !(aPre) {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:110:9
		return 1
	}
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:112:5
	if !(bPre) {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:113:9
		return -1
	}
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:116:5
	p1 := comparePreIdent(a.pre1, b.pre1)
	_ = p1
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:117:5
	if p1 != 0 {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:118:9
		return p1
	}
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:120:5
	p2 := comparePreIdent(a.pre2, b.pre2)
	_ = p2
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:121:5
	if p2 != 0 {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:122:9
		return p2
	}
	return comparePreIdent(a.pre3, b.pre3)
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:128:5
func comparePreIdent(a SemPreIdent, b SemPreIdent) int {
	return func() int {
		_m2 := a
		_ = _m2
		if func() bool { _, ok := _m2.(*SemPreIdent_PreNone); return ok }() {
			return func() int {
				_m3 := b
				_ = _m3
				if func() bool { _, ok := _m3.(*SemPreIdent_PreNone); return ok }() {
					return 0
				}
				{
					return -1
				}
			}()
		}
		if func() bool { _, ok := _m2.(*SemPreIdent_PreNumber); return ok }() {
			_v4 := _m2.(*SemPreIdent_PreNumber)
			_ = _v4
			an := _v4.F0
			_ = an
			return func() int {
				_m5 := b
				_ = _m5
				if func() bool { _, ok := _m5.(*SemPreIdent_PreNone); return ok }() {
					return 1
				}
				if func() bool { _, ok := _m5.(*SemPreIdent_PreNumber); return ok }() {
					_v6 := _m5.(*SemPreIdent_PreNumber)
					_ = _v6
					bn := _v6.F0
					_ = bn
					return signInt(an, bn)
				}
				if func() bool { _, ok := _m5.(*SemPreIdent_PreText); return ok }() {
					_v7 := _m5.(*SemPreIdent_PreText)
					_ = _v7
					return -1
				}
				panic("unreachable match")
			}()
		}
		if func() bool { _, ok := _m2.(*SemPreIdent_PreText); return ok }() {
			_v8 := _m2.(*SemPreIdent_PreText)
			_ = _v8
			at := _v8.F0
			_ = at
			return func() int {
				_m9 := b
				_ = _m9
				if func() bool { _, ok := _m9.(*SemPreIdent_PreNone); return ok }() {
					return 1
				}
				if func() bool { _, ok := _m9.(*SemPreIdent_PreNumber); return ok }() {
					_v10 := _m9.(*SemPreIdent_PreNumber)
					_ = _v10
					return 1
				}
				if func() bool { _, ok := _m9.(*SemPreIdent_PreText); return ok }() {
					_v11 := _m9.(*SemPreIdent_PreText)
					_ = _v11
					bt := _v11.F0
					_ = bt
					return signString(at, bt)
				}
				panic("unreachable match")
			}()
		}
		panic("unreachable match")
	}()
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:148:5
func signInt(a int, b int) int {
	return func() int {
		if a < b {
			return -1
		} else if a > b {
			return 1
		} else {
			return 0
		}
	}()
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:159:5
func signString(a string, b string) int {
	return func() int {
		if a < b {
			return -1
		} else if a > b {
			return 1
		} else {
			return 0
		}
	}()
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:170:5
func semPreIdentIsNone(ident SemPreIdent) bool {
	return func() bool {
		_m12 := ident
		_ = _m12
		if func() bool { _, ok := _m12.(*SemPreIdent_PreNone); return ok }() {
			return true
		}
		{
			return false
		}
	}()
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:178:5
func semPreIdentText(ident SemPreIdent) string {
	return func() string {
		_m13 := ident
		_ = _m13
		if func() bool { _, ok := _m13.(*SemPreIdent_PreNone); return ok }() {
			return ""
		}
		if func() bool { _, ok := _m13.(*SemPreIdent_PreNumber); return ok }() {
			_v14 := _m13.(*SemPreIdent_PreNumber)
			_ = _v14
			n := _v14.F0
			_ = n
			return fmt.Sprintf("%s", ostyToString(n))
		}
		if func() bool { _, ok := _m13.(*SemPreIdent_PreText); return ok }() {
			_v15 := _m13.(*SemPreIdent_PreText)
			_ = _v15
			text := _v15.F0
			_ = text
			return text
		}
		panic("unreachable match")
	}()
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:187:5
func semVersionText(v *SemVersion) string {
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:188:5
	out := fmt.Sprintf("%s.%s.%s", ostyToString(v.major), ostyToString(v.minor), ostyToString(v.patch))
	_ = out
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:189:5
	if isSemPrerelease(v) {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:190:9
		first := semPreIdentText(v.pre1)
		_ = first
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:191:9
		out = fmt.Sprintf("%s-%s", ostyToString(out), ostyToString(first))
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:192:9
		if !(semPreIdentIsNone(v.pre2)) {
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:193:13
			second := semPreIdentText(v.pre2)
			_ = second
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:194:13
			out = fmt.Sprintf("%s.%s", ostyToString(out), ostyToString(second))
		}
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:196:9
		if !(semPreIdentIsNone(v.pre3)) {
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:197:13
			third := semPreIdentText(v.pre3)
			_ = third
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:198:13
			out = fmt.Sprintf("%s.%s", ostyToString(out), ostyToString(third))
		}
	}
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:201:5
	if v.build != "" {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:202:9
		out = fmt.Sprintf("%s+%s", ostyToString(out), ostyToString(v.build))
	}
	return out
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:209:5
type SemReqOp interface{ _isSemReqOp() }
type SemReqOp_ReqEQ struct{ _ref byte }

func (SemReqOp_ReqEQ) _isSemReqOp() {}

type SemReqOp_ReqGE struct{ _ref byte }

func (SemReqOp_ReqGE) _isSemReqOp() {}

type SemReqOp_ReqGT struct{ _ref byte }

func (SemReqOp_ReqGT) _isSemReqOp() {}

type SemReqOp_ReqLE struct{ _ref byte }

func (SemReqOp_ReqLE) _isSemReqOp() {}

type SemReqOp_ReqLT struct{ _ref byte }

func (SemReqOp_ReqLT) _isSemReqOp() {}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:218:5
type SemReqClause struct {
	op      SemReqOp
	version *SemVersion
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:224:5
type SemReq struct {
	allowPre bool
	clauses  []*SemReqClause
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:230:5
type SemMaxResult struct {
	found   bool
	version *SemVersion
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:236:5
func reqClause(op SemReqOp, version *SemVersion) *SemReqClause {
	return &SemReqClause{op: op, version: version}
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:241:5
func semReq(allowPre bool, clauses []*SemReqClause) *SemReq {
	return &SemReq{allowPre: allowPre, clauses: clauses}
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:246:5
func anySemReq() *SemReq {
	return semReq(false, make([]*SemReqClause, 0, 1))
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:251:5
// Osty: /tmp/pkgmgr_selfhost_merged.osty:256:5
// Osty: /tmp/pkgmgr_selfhost_merged.osty:261:5
// Osty: /tmp/pkgmgr_selfhost_merged.osty:266:5
// Osty: /tmp/pkgmgr_selfhost_merged.osty:271:5
// Osty: /tmp/pkgmgr_selfhost_merged.osty:276:5
// Osty: /tmp/pkgmgr_selfhost_merged.osty:287:5
// Osty: /tmp/pkgmgr_selfhost_merged.osty:299:5
// Osty: /tmp/pkgmgr_selfhost_merged.osty:304:5
// Osty: /tmp/pkgmgr_selfhost_merged.osty:309:5
// Osty: /tmp/pkgmgr_selfhost_merged.osty:314:5
func semReqMatches(req *SemReq, version *SemVersion) bool {
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:315:5
	if isSemPrerelease(version) && !(req.allowPre) {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:316:9
		return false
	}
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:318:5
	for _, clause := range req.clauses {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:319:9
		if !(semClauseMatches(clause, version)) {
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:320:13
			return false
		}
	}
	return true
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:327:5
func semClauseMatches(clause *SemReqClause, version *SemVersion) bool {
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:328:5
	cmp := compareSemVersion(version, clause.version)
	_ = cmp
	return func() bool {
		_m28 := clause.op
		_ = _m28
		if func() bool { _, ok := _m28.(*SemReqOp_ReqEQ); return ok }() {
			return cmp == 0
		}
		if func() bool { _, ok := _m28.(*SemReqOp_ReqGE); return ok }() {
			return cmp >= 0
		}
		if func() bool { _, ok := _m28.(*SemReqOp_ReqGT); return ok }() {
			return cmp > 0
		}
		if func() bool { _, ok := _m28.(*SemReqOp_ReqLE); return ok }() {
			return cmp <= 0
		}
		if func() bool { _, ok := _m28.(*SemReqOp_ReqLT); return ok }() {
			return cmp < 0
		}
		panic("unreachable match")
	}()
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:339:5
// Osty: /tmp/pkgmgr_selfhost_merged.osty:367:5
type SelfPkgSourceKind interface{ _isSelfPkgSourceKind() }
type SelfPkgSourceKind_SelfPkgSourceRegistry struct{ _ref byte }

func (SelfPkgSourceKind_SelfPkgSourceRegistry) _isSelfPkgSourceKind() {}

type SelfPkgSourceKind_SelfPkgSourcePath struct{ _ref byte }

func (SelfPkgSourceKind_SelfPkgSourcePath) _isSelfPkgSourceKind() {}

type SelfPkgSourceKind_SelfPkgSourceGit struct{ _ref byte }

func (SelfPkgSourceKind_SelfPkgSourceGit) _isSelfPkgSourceKind() {}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:374:5
type SelfPkgDependency struct {
	name        string
	packageName string
	sourceKind  SelfPkgSourceKind
	versionReq  *SemReq
	registry    string
	sourceRef   string
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:384:5
type SelfPkgCandidate struct {
	packageName string
	version     *SemVersion
	checksum    string
	yanked      bool
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:392:5
type SelfPkgLockDependency struct {
	name    string
	version *SemVersion
	source  string
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:399:5
type SelfPkgLockPackage struct {
	name         string
	version      *SemVersion
	source       string
	checksum     string
	dependencies []*SelfPkgLockDependency
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:408:5
type SelfPkgLockLookup struct {
	found bool
	pkg   *SelfPkgLockPackage
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:414:5
type SelfPkgResolveDecision struct {
	found       bool
	name        string
	packageName string
	version     *SemVersion
	source      string
	checksum    string
	fromLock    bool
	message     string
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:426:5
type SelfPkgResolvePlan struct {
	decisions []*SelfPkgResolveDecision
	missing   int
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:432:5
type SelfPkgLockChangeKind interface{ _isSelfPkgLockChangeKind() }
type SelfPkgLockChangeKind_SelfPkgLockAdded struct{ _ref byte }

func (SelfPkgLockChangeKind_SelfPkgLockAdded) _isSelfPkgLockChangeKind() {}

type SelfPkgLockChangeKind_SelfPkgLockRemoved struct{ _ref byte }

func (SelfPkgLockChangeKind_SelfPkgLockRemoved) _isSelfPkgLockChangeKind() {}

type SelfPkgLockChangeKind_SelfPkgLockVersion struct{ _ref byte }

func (SelfPkgLockChangeKind_SelfPkgLockVersion) _isSelfPkgLockChangeKind() {}

type SelfPkgLockChangeKind_SelfPkgLockChecksum struct{ _ref byte }

func (SelfPkgLockChangeKind_SelfPkgLockChecksum) _isSelfPkgLockChangeKind() {}

type SelfPkgLockChangeKind_SelfPkgLockSource struct{ _ref byte }

func (SelfPkgLockChangeKind_SelfPkgLockSource) _isSelfPkgLockChangeKind() {}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:441:5
type SelfPkgLockChange struct {
	name       string
	kind       SelfPkgLockChangeKind
	oldVersion *SemVersion
	newVersion *SemVersion
	detail     string
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:450:5
type SelfPkgGitRef struct {
	url    string
	tag    string
	branch string
	rev    string
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:458:5
type SelfPkgChecksumCheck struct {
	ok      bool
	message string
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:464:5
type SelfPkgRegistryRequest struct {
	method        string
	url           string
	accept        string
	contentType   string
	authorization string
	checksum      string
	metadata      string
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:475:5
type SelfPkgStatusCheck struct {
	ok      bool
	message string
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:481:5
type SelfPkgGraphNode struct {
	name        string
	packageName string
	version     *SemVersion
	source      string
	checksum    string
	deps        []string
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:491:5
type SelfPkgGraph struct {
	nodes  []*SelfPkgGraphNode
	order  []string
	errors []string
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:498:5
type SelfPkgDepLookupItem struct {
	name   string
	gitURL string
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:504:5
type SelfPkgDepLookupResult struct {
	found bool
	name  string
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:510:5
// Osty: /tmp/pkgmgr_selfhost_merged.osty:516:5
func selfPkgRegistryDependencyAs(name string, packageName string, registry string, req *SemReq) *SelfPkgDependency {
	return &SelfPkgDependency{name: name, packageName: packageName, sourceKind: SelfPkgSourceKind(&SelfPkgSourceKind_SelfPkgSourceRegistry{}), versionReq: req, registry: registry, sourceRef: ""}
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:533:5
func selfPkgPathDependency(name string, path string) *SelfPkgDependency {
	return &SelfPkgDependency{name: name, packageName: "", sourceKind: SelfPkgSourceKind(&SelfPkgSourceKind_SelfPkgSourcePath{}), versionReq: anySemReq(), registry: "", sourceRef: path}
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:545:5
// Osty: /tmp/pkgmgr_selfhost_merged.osty:557:5
func selfPkgCandidate(packageName string, version *SemVersion, checksum string, yanked bool) *SelfPkgCandidate {
	return &SelfPkgCandidate{packageName: packageName, version: version, checksum: checksum, yanked: yanked}
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:567:5
func selfPkgGitRef(url string, tag string, branch string, rev string) *SelfPkgGitRef {
	return &SelfPkgGitRef{url: url, tag: tag, branch: branch, rev: rev}
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:572:5
func selfPkgLockDependency(name string, version *SemVersion, source string) *SelfPkgLockDependency {
	return &SelfPkgLockDependency{name: name, version: version, source: source}
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:581:5
func selfPkgLockPackage(name string, version *SemVersion, source string, checksum string, dependencies []*SelfPkgLockDependency) *SelfPkgLockPackage {
	return &SelfPkgLockPackage{name: name, version: version, source: source, checksum: checksum, dependencies: dependencies}
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:591:1
func emptySelfPkgLockPackage() *SelfPkgLockPackage {
	return selfPkgLockPackage("", stableVersion(0, 0, 0), "", "", make([]*SelfPkgLockDependency, 0, 1))
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:595:1
func emptySelfPkgResolveDecision(name string, message string) *SelfPkgResolveDecision {
	return &SelfPkgResolveDecision{found: false, name: name, packageName: "", version: stableVersion(0, 0, 0), source: "", checksum: "", fromLock: false, message: message}
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:609:5
func selfPkgCanonicalName(dep *SelfPkgDependency) string {
	return func() string {
		if dep.packageName != "" {
			return dep.packageName
		} else {
			return dep.name
		}
	}()
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:618:5
func selfPkgSourceURI(dep *SelfPkgDependency) string {
	return func() string {
		_m29 := dep.sourceKind
		_ = _m29
		if func() bool { _, ok := _m29.(*SelfPkgSourceKind_SelfPkgSourceRegistry); return ok }() {
			return func() string {
				if dep.registry == "" {
					return "registry+default"
				} else {
					return fmt.Sprintf("registry+%s", ostyToString(dep.registry))
				}
			}()
		}
		if func() bool { _, ok := _m29.(*SelfPkgSourceKind_SelfPkgSourcePath); return ok }() {
			return fmt.Sprintf("path+%s", ostyToString(dep.sourceRef))
		}
		if func() bool { _, ok := _m29.(*SelfPkgSourceKind_SelfPkgSourceGit); return ok }() {
			return fmt.Sprintf("git+%s", ostyToString(dep.sourceRef))
		}
		panic("unreachable match")
	}()
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:633:5
func selfPkgGitURI(source *SelfPkgGitRef) string {
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:634:5
	var params []string = make([]string, 0, 1)
	_ = params
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:635:5
	if source.tag != "" {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:636:9
		func() struct{} {
			params = append(params, fmt.Sprintf("tag=%s", ostyToString(source.tag)))
			return struct{}{}
		}()
	}
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:638:5
	if source.branch != "" {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:639:9
		func() struct{} {
			params = append(params, fmt.Sprintf("branch=%s", ostyToString(source.branch)))
			return struct{}{}
		}()
	}
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:641:5
	if source.rev != "" {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:642:9
		func() struct{} {
			params = append(params, fmt.Sprintf("rev=%s", ostyToString(source.rev)))
			return struct{}{}
		}()
	}
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:644:5
	base := fmt.Sprintf("git+%s", ostyToString(source.url))
	_ = base
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:645:5
	if len(params) == 0 {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:646:9
		return base
	}
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:648:5
	joined := pkgStrings.Join(params, "&")
	_ = joined
	return fmt.Sprintf("%s?%s", ostyToString(base), ostyToString(joined))
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:653:5
func selfPkgGitCheckoutRef(source *SelfPkgGitRef) string {
	return func() string {
		if source.rev != "" {
			return source.rev
		} else if source.tag != "" {
			return fmt.Sprintf("refs/tags/%s", ostyToString(source.tag))
		} else if source.branch != "" {
			return fmt.Sprintf("origin/%s", ostyToString(source.branch))
		} else {
			return "origin/HEAD"
		}
	}()
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:666:5
func selfPkgSanitizeURL(url string) string {
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:667:5
	out := ""
	_ = out
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:668:5
	for _, unit := range pkgStrings.Split(url, "") {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:669:9
		if selfPkgURLUnitSafe(unit) {
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:670:13
			out = fmt.Sprintf("%s%s", ostyToString(out), ostyToString(unit))
		} else {
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:672:13
			out = fmt.Sprintf("%s_", ostyToString(out))
		}
	}
	return out
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:678:1
func selfPkgURLUnitSafe(unit string) bool {
	return (unit >= "A" && unit <= "Z") || (unit >= "a" && unit <= "z") || (unit >= "0" && unit <= "9") || unit == "-" || unit == "." || unit == "_"
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:683:5
func selfPkgLockDependencyString(dep *SelfPkgLockDependency) string {
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:684:5
	version := semVersionText(dep.version)
	_ = version
	return func() string {
		if dep.source == "" {
			return fmt.Sprintf("%s %s", ostyToString(dep.name), ostyToString(version))
		} else {
			return fmt.Sprintf("%s %s (%s)", ostyToString(dep.name), ostyToString(version), ostyToString(dep.source))
		}
	}()
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:693:5
func selfPkgTomlQuote(text string) string {
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:694:5
	slash := "\\"
	_ = slash
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:695:5
	quote := "\""
	_ = quote
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:696:5
	out := quote
	_ = out
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:697:5
	for _, unit := range pkgStrings.Split(text, "") {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:698:9
		if unit == "\\" {
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:699:13
			out = fmt.Sprintf("%s%s%s", ostyToString(out), ostyToString(slash), ostyToString(slash))
		} else if unit == "\"" {
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:701:13
			out = fmt.Sprintf("%s%s%s", ostyToString(out), ostyToString(slash), ostyToString(quote))
		} else if unit == "\n" {
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:703:13
			out = fmt.Sprintf("%s%sn", ostyToString(out), ostyToString(slash))
		} else if unit == "\r" {
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:705:13
			out = fmt.Sprintf("%s%sr", ostyToString(out), ostyToString(slash))
		} else if unit == "\t" {
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:707:13
			out = fmt.Sprintf("%s%st", ostyToString(out), ostyToString(slash))
		} else {
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:709:13
			out = fmt.Sprintf("%s%s", ostyToString(out), ostyToString(unit))
		}
	}
	return fmt.Sprintf("%s%s", ostyToString(out), ostyToString(quote))
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:716:5
func selfPkgMarshalLock(packages []*SelfPkgLockPackage) string {
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:717:5
	sorted := selfPkgSortLockPackages(packages)
	_ = sorted
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:718:5
	out := "# This file is auto-generated by osty.\n"
	_ = out
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:719:5
	out = fmt.Sprintf("%s# Do not edit manually; `osty update` regenerates it.\n\n", ostyToString(out))
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:720:5
	out = fmt.Sprintf("%sversion = 1\n", ostyToString(out))
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:721:5
	for _, pkg := range sorted {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:722:9
		version := semVersionText(pkg.version)
		_ = version
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:723:9
		out = fmt.Sprintf("%s\n[[package]]\n", ostyToString(out))
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:724:9
		out = fmt.Sprintf("%sname = %s\n", ostyToString(out), ostyToString(selfPkgTomlQuote(pkg.name)))
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:725:9
		out = fmt.Sprintf("%sversion = %s\n", ostyToString(out), ostyToString(selfPkgTomlQuote(version)))
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:726:9
		if pkg.source != "" {
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:727:13
			out = fmt.Sprintf("%ssource = %s\n", ostyToString(out), ostyToString(selfPkgTomlQuote(pkg.source)))
		}
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:729:9
		if pkg.checksum != "" {
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:730:13
			out = fmt.Sprintf("%schecksum = %s\n", ostyToString(out), ostyToString(selfPkgTomlQuote(pkg.checksum)))
		}
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:732:9
		if selfPkgLockDependencyCount(pkg.dependencies) > 0 {
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:733:13
			out = fmt.Sprintf("%sdependencies = [\n", ostyToString(out))
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:734:13
			for _, dep := range selfPkgSortLockDependencies(pkg.dependencies) {
				// Osty: /tmp/pkgmgr_selfhost_merged.osty:735:17
				out = fmt.Sprintf("%s    %s,\n", ostyToString(out), ostyToString(selfPkgTomlQuote(selfPkgLockDependencyString(dep))))
			}
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:737:13
			out = fmt.Sprintf("%s]\n", ostyToString(out))
		}
	}
	return out
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:743:1
func selfPkgLockDependencyCount(dependencies []*SelfPkgLockDependency) int {
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:744:5
	count := 0
	_ = count
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:745:5
	for _, dep := range dependencies {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:746:9
		_ = dep
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:747:9
		func() {
			var _cur30 int = count
			var _rhs31 int = 1
			if _rhs31 > 0 && _cur30 > math.MaxInt-_rhs31 {
				panic("integer overflow")
			}
			if _rhs31 < 0 && _cur30 < math.MinInt-_rhs31 {
				panic("integer overflow")
			}
			count = _cur30 + _rhs31
		}()
	}
	return count
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:753:5
func selfPkgSortLockPackages(packages []*SelfPkgLockPackage) []*SelfPkgLockPackage {
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:754:5
	var out []*SelfPkgLockPackage = make([]*SelfPkgLockPackage, 0, 1)
	_ = out
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:755:5
	for _, pkg := range packages {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:756:9
		out = selfPkgInsertLockPackage(out, pkg)
	}
	return out
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:761:1
func selfPkgInsertLockPackage(packages []*SelfPkgLockPackage, item *SelfPkgLockPackage) []*SelfPkgLockPackage {
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:765:5
	var out []*SelfPkgLockPackage = make([]*SelfPkgLockPackage, 0, 1)
	_ = out
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:766:5
	inserted := false
	_ = inserted
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:767:5
	for _, pkg := range packages {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:768:9
		if !(inserted) && selfPkgLockPackageLess(item, pkg) {
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:769:13
			func() struct{} { out = append(out, item); return struct{}{} }()
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:770:13
			inserted = true
		}
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:772:9
		func() struct{} { out = append(out, pkg); return struct{}{} }()
	}
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:774:5
	if !(inserted) {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:775:9
		func() struct{} { out = append(out, item); return struct{}{} }()
	}
	return out
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:780:1
func selfPkgLockPackageLess(a *SelfPkgLockPackage, b *SelfPkgLockPackage) bool {
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:781:5
	if a.name != b.name {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:782:9
		return a.name < b.name
	}
	return semVersionText(a.version) < semVersionText(b.version)
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:788:5
func selfPkgSortLockDependencies(dependencies []*SelfPkgLockDependency) []*SelfPkgLockDependency {
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:789:5
	var out []*SelfPkgLockDependency = make([]*SelfPkgLockDependency, 0, 1)
	_ = out
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:790:5
	for _, dep := range dependencies {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:791:9
		out = selfPkgInsertLockDependency(out, dep)
	}
	return out
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:796:1
func selfPkgInsertLockDependency(dependencies []*SelfPkgLockDependency, item *SelfPkgLockDependency) []*SelfPkgLockDependency {
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:800:5
	var out []*SelfPkgLockDependency = make([]*SelfPkgLockDependency, 0, 1)
	_ = out
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:801:5
	inserted := false
	_ = inserted
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:802:5
	for _, dep := range dependencies {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:803:9
		if !(inserted) && selfPkgLockDependencyLess(item, dep) {
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:804:13
			func() struct{} { out = append(out, item); return struct{}{} }()
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:805:13
			inserted = true
		}
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:807:9
		func() struct{} { out = append(out, dep); return struct{}{} }()
	}
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:809:5
	if !(inserted) {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:810:9
		func() struct{} { out = append(out, item); return struct{}{} }()
	}
	return out
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:815:1
func selfPkgLockDependencyLess(a *SelfPkgLockDependency, b *SelfPkgLockDependency) bool {
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:816:5
	if a.name != b.name {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:817:9
		return a.name < b.name
	}
	return semVersionText(a.version) < semVersionText(b.version)
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:824:5
func selfPkgCandidateMatches(dep *SelfPkgDependency, candidate *SelfPkgCandidate) bool {
	return candidate.packageName == selfPkgCanonicalName(dep) && !(candidate.yanked) && semReqMatches(dep.versionReq, candidate.version)
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:832:5
func selfPkgFindLockedPackage(name string, locked []*SelfPkgLockPackage) *SelfPkgLockLookup {
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:833:5
	for _, pkg := range locked {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:834:9
		if pkg.name == name {
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:835:13
			return &SelfPkgLockLookup{found: true, pkg: pkg}
		}
	}
	return &SelfPkgLockLookup{found: false, pkg: emptySelfPkgLockPackage()}
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:844:5
func selfPkgFindCompatibleLockedPackage(dep *SelfPkgDependency, locked []*SelfPkgLockPackage) *SelfPkgLockLookup {
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:848:5
	wantSource := selfPkgSourceURI(dep)
	_ = wantSource
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:849:5
	for _, pkg := range locked {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:850:9
		if pkg.name == dep.name {
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:851:13
			if (pkg.source == "" || pkg.source == wantSource) && semReqMatches(dep.versionReq, pkg.version) {
				// Osty: /tmp/pkgmgr_selfhost_merged.osty:855:17
				return &SelfPkgLockLookup{found: true, pkg: pkg}
			}
		}
	}
	return &SelfPkgLockLookup{found: false, pkg: emptySelfPkgLockPackage()}
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:865:5
func selfPkgSelectRegistryCandidate(dep *SelfPkgDependency, candidates []*SelfPkgCandidate, locked []*SelfPkgLockPackage) *SelfPkgResolveDecision {
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:870:5
	source := selfPkgSourceURI(dep)
	_ = source
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:871:5
	canonical := selfPkgCanonicalName(dep)
	_ = canonical
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:872:5
	lockedPkg := selfPkgFindCompatibleLockedPackage(dep, locked)
	_ = lockedPkg
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:873:5
	if lockedPkg.found {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:874:9
		for _, candidate := range candidates {
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:875:13
			if selfPkgCandidateMatches(dep, candidate) && compareSemVersion(candidate.version, lockedPkg.pkg.version) == 0 {
				// Osty: /tmp/pkgmgr_selfhost_merged.osty:879:17
				return &SelfPkgResolveDecision{found: true, name: dep.name, packageName: canonical, version: candidate.version, source: source, checksum: candidate.checksum, fromLock: true, message: "locked"}
			}
		}
	}
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:893:5
	found := false
	_ = found
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:894:5
	best := stableVersion(0, 0, 0)
	_ = best
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:895:5
	checksum := ""
	_ = checksum
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:896:5
	for _, candidate := range candidates {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:897:9
		if selfPkgCandidateMatches(dep, candidate) {
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:898:13
			if !(found) || compareSemVersion(best, candidate.version) < 0 {
				// Osty: /tmp/pkgmgr_selfhost_merged.osty:899:17
				found = true
				// Osty: /tmp/pkgmgr_selfhost_merged.osty:900:17
				best = candidate.version
				// Osty: /tmp/pkgmgr_selfhost_merged.osty:901:17
				checksum = candidate.checksum
			}
		}
	}
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:905:5
	if found {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:906:9
		return &SelfPkgResolveDecision{found: true, name: dep.name, packageName: canonical, version: best, source: source, checksum: checksum, fromLock: false, message: "selected"}
	}
	return emptySelfPkgResolveDecision(dep.name, "no matching registry version")
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:922:5
// Osty: /tmp/pkgmgr_selfhost_merged.osty:940:5
// Osty: /tmp/pkgmgr_selfhost_merged.osty:951:5
// Osty: /tmp/pkgmgr_selfhost_merged.osty:970:5
func selfPkgChecksumPrefix() string {
	return "sha256:"
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:975:5
func selfPkgVerifyChecksum(want string, got string) *SelfPkgChecksumCheck {
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:976:5
	if want == "" {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:977:9
		return &SelfPkgChecksumCheck{ok: true, message: ""}
	}
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:979:5
	prefix := selfPkgChecksumPrefix()
	_ = prefix
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:980:5
	quote := "\""
	_ = quote
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:981:5
	if !(pkgStrings.HasPrefix(want, prefix)) || !(pkgStrings.HasPrefix(got, prefix)) {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:982:9
		return &SelfPkgChecksumCheck{ok: false, message: fmt.Sprintf("checksum mismatch: want %s%s%s, got %s%s%s (unsupported algorithm)", ostyToString(quote), ostyToString(want), ostyToString(quote), ostyToString(quote), ostyToString(got), ostyToString(quote))}
	}
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:987:5
	if want != got {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:988:9
		return &SelfPkgChecksumCheck{ok: false, message: fmt.Sprintf("checksum mismatch:\n  want %s\n  got  %s", ostyToString(want), ostyToString(got))}
	}
	return &SelfPkgChecksumCheck{ok: true, message: ""}
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:997:5
func selfPkgDiffLocks(old []*SelfPkgLockPackage, new []*SelfPkgLockPackage) []*SelfPkgLockChange {
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1001:5
	var out []*SelfPkgLockChange = make([]*SelfPkgLockChange, 0, 1)
	_ = out
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1002:5
	for _, oldPkg := range old {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1003:9
		next := selfPkgFindLockedPackage(oldPkg.name, new)
		_ = next
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1004:9
		if !(next.found) {
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:1005:13
			func() struct{} {
				out = append(out, selfPkgLockChange(oldPkg.name, SelfPkgLockChangeKind(&SelfPkgLockChangeKind_SelfPkgLockRemoved{}), oldPkg.version, stableVersion(0, 0, 0), ""))
				return struct{}{}
			}()
		} else if compareSemVersion(oldPkg.version, next.pkg.version) != 0 {
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:1015:13
			func() struct{} {
				out = append(out, selfPkgLockChange(oldPkg.name, SelfPkgLockChangeKind(&SelfPkgLockChangeKind_SelfPkgLockVersion{}), oldPkg.version, next.pkg.version, ""))
				return struct{}{}
			}()
		} else if oldPkg.checksum != next.pkg.checksum {
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:1025:13
			oldShort := selfPkgShortChecksum(oldPkg.checksum)
			_ = oldShort
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:1026:13
			newShort := selfPkgShortChecksum(next.pkg.checksum)
			_ = newShort
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:1027:13
			func() struct{} {
				out = append(out, selfPkgLockChange(oldPkg.name, SelfPkgLockChangeKind(&SelfPkgLockChangeKind_SelfPkgLockChecksum{}), oldPkg.version, next.pkg.version, fmt.Sprintf("%s -> %s", ostyToString(oldShort), ostyToString(newShort))))
				return struct{}{}
			}()
		} else if oldPkg.source != next.pkg.source {
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:1037:13
			func() struct{} {
				out = append(out, selfPkgLockChange(oldPkg.name, SelfPkgLockChangeKind(&SelfPkgLockChangeKind_SelfPkgLockSource{}), oldPkg.version, next.pkg.version, fmt.Sprintf("%s -> %s", ostyToString(oldPkg.source), ostyToString(next.pkg.source))))
				return struct{}{}
			}()
		}
	}
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1048:5
	for _, newPkg := range new {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1049:9
		prev := selfPkgFindLockedPackage(newPkg.name, old)
		_ = prev
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1050:9
		if !(prev.found) {
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:1051:13
			func() struct{} {
				out = append(out, selfPkgLockChange(newPkg.name, SelfPkgLockChangeKind(&SelfPkgLockChangeKind_SelfPkgLockAdded{}), stableVersion(0, 0, 0), newPkg.version, ""))
				return struct{}{}
			}()
		}
	}
	return out
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:1065:1
func selfPkgShortChecksum(checksum string) string {
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1066:5
	prefix := selfPkgChecksumPrefix()
	_ = prefix
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1067:5
	text := pkgStrings.TrimPrefix(checksum, prefix)
	_ = text
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1068:5
	if selfPkgStringUnitCount(text) > 12 {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1069:9
		return fmt.Sprintf("%s%s", ostyToString(prefix), ostyToString(selfPkgFirstUnits(text, 12)))
	}
	return checksum
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:1074:1
func selfPkgFirstUnits(text string, limit int) string {
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1075:5
	out := ""
	_ = out
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1076:5
	count := 0
	_ = count
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1077:5
	for _, unit := range pkgStrings.Split(text, "") {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1078:9
		if count < limit {
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:1079:13
			out = fmt.Sprintf("%s%s", ostyToString(out), ostyToString(unit))
		}
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1081:9
		func() {
			var _cur36 int = count
			var _rhs37 int = 1
			if _rhs37 > 0 && _cur36 > math.MaxInt-_rhs37 {
				panic("integer overflow")
			}
			if _rhs37 < 0 && _cur36 < math.MinInt-_rhs37 {
				panic("integer overflow")
			}
			count = _cur36 + _rhs37
		}()
	}
	return out
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:1086:1
func selfPkgStringUnitCount(text string) int {
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1087:5
	count := 0
	_ = count
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1088:5
	for _, unit := range pkgStrings.Split(text, "") {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1089:9
		_ = unit
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1090:9
		func() {
			var _cur38 int = count
			var _rhs39 int = 1
			if _rhs39 > 0 && _cur38 > math.MaxInt-_rhs39 {
				panic("integer overflow")
			}
			if _rhs39 < 0 && _cur38 < math.MinInt-_rhs39 {
				panic("integer overflow")
			}
			count = _cur38 + _rhs39
		}()
	}
	return count
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:1096:5
func selfPkgLockChange(name string, kind SelfPkgLockChangeKind, oldVersion *SemVersion, newVersion *SemVersion, detail string) *SelfPkgLockChange {
	return &SelfPkgLockChange{name: name, kind: kind, oldVersion: oldVersion, newVersion: newVersion, detail: detail}
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:1107:5
// Osty: /tmp/pkgmgr_selfhost_merged.osty:1121:5
// Osty: /tmp/pkgmgr_selfhost_merged.osty:1147:5
func selfPkgRegistryEndpoint(baseURL string, segments []string) string {
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1148:5
	var parts []string = []string{pkgStrings.TrimRight(baseURL, "/")}
	_ = parts
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1149:5
	for _, segment := range segments {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1150:9
		func() struct{} { parts = append(parts, segment); return struct{}{} }()
	}
	return pkgStrings.Join(parts, "/")
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:1156:5
func selfPkgRegistryVersionsRequest(baseURL string, name string, token string) *SelfPkgRegistryRequest {
	return selfPkgRegistryRequest("GET", selfPkgRegistryEndpoint(baseURL, []string{"v1", "crates", name}), "application/json", "", selfPkgBearer(token), "", "")
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:1169:5
func selfPkgRegistryTarballRequest(baseURL string, name string, version string, token string) *SelfPkgRegistryRequest {
	return selfPkgRegistryRequest("GET", selfPkgRegistryEndpoint(baseURL, []string{"v1", "crates", name, version, "tar"}), "application/json", "", selfPkgBearer(token), "", "")
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:1187:5
func selfPkgRegistryPublishRequest(baseURL string, name string, version string, token string, checksum string, metadata string) *SelfPkgRegistryRequest {
	return selfPkgRegistryRequest("PUT", selfPkgRegistryEndpoint(baseURL, []string{"v1", "crates", name, version}), "application/json", "application/x-tar+gzip", selfPkgBearer(token), checksum, metadata)
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:1207:5
func selfPkgRegistryYankRequest(baseURL string, name string, version string, token string, yanked bool) *SelfPkgRegistryRequest {
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1214:5
	method := "DELETE"
	_ = method
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1215:5
	segment := "yank"
	_ = segment
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1216:5
	if !(yanked) {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1217:9
		method = "PUT"
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1218:9
		segment = "unyank"
	}
	return selfPkgRegistryRequest(method, selfPkgRegistryEndpoint(baseURL, []string{"v1", "crates", name, version, segment}), "application/json", "", selfPkgBearer(token), "", "")
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:1231:1
func selfPkgRegistryRequest(method string, url string, accept string, contentType string, authorization string, checksum string, metadata string) *SelfPkgRegistryRequest {
	return &SelfPkgRegistryRequest{method: method, url: url, accept: accept, contentType: contentType, authorization: authorization, checksum: checksum, metadata: metadata}
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:1243:1
func selfPkgBearer(token string) string {
	return func() string {
		if token == "" {
			return ""
		} else {
			return fmt.Sprintf("Bearer %s", ostyToString(token))
		}
	}()
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:1252:5
// Osty: /tmp/pkgmgr_selfhost_merged.osty:1272:5
func selfPkgGraphNode(name string, packageName string, version *SemVersion, source string, checksum string, deps []string) *SelfPkgGraphNode {
	return &SelfPkgGraphNode{name: name, packageName: packageName, version: version, source: source, checksum: checksum, deps: deps}
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:1284:5
// Osty: /tmp/pkgmgr_selfhost_merged.osty:1294:5
// Osty: /tmp/pkgmgr_selfhost_merged.osty:1304:5
// Osty: /tmp/pkgmgr_selfhost_merged.osty:1313:1
func emptySelfPkgGraphNode() *SelfPkgGraphNode {
	return selfPkgGraphNode("", "", stableVersion(0, 0, 0), "", "", make([]string, 0, 1))
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:1320:5
// Osty: /tmp/pkgmgr_selfhost_merged.osty:1332:1
func selfPkgResolveRegistryPending(graph *SelfPkgGraph, pending []*SelfPkgDependency, candidates []*SelfPkgCandidate, candidateDeps []*SelfPkgCandidateDeps, locked []*SelfPkgLockPackage) *SelfPkgGraph {
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1339:5
	if len(pending) == 0 {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1340:9
		return graph
	}
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1342:5
	dep := pending[0]
	_ = dep
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1343:5
	rest := selfPkgDropFirstDependency(pending)
	_ = rest
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1344:5
	next := graph
	_ = next
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1345:5
	existing := selfPkgFindGraphNode(dep.name, next.nodes)
	_ = existing
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1346:5
	if existing.found {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1347:9
		if !(semReqMatches(dep.versionReq, existing.node.version)) {
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:1348:13
			func() struct{} {
				next.errors = append(next.errors, fmt.Sprintf("dependency %s already resolved to incompatible version", ostyToString(dep.name)))
				return struct{}{}
			}()
		}
	} else {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1351:9
		decision := selfPkgSelectRegistryCandidate(dep, candidates, locked)
		_ = decision
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1352:9
		if !(decision.found) {
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:1353:13
			func() struct{} { next.errors = append(next.errors, decision.message); return struct{}{} }()
		} else {
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:1355:13
			childDeps := selfPkgCandidateDependencyList(decision.packageName, decision.version, candidateDeps)
			_ = childDeps
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:1360:13
			var childNames []string = make([]string, 0, 1)
			_ = childNames
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:1361:13
			for _, child := range childDeps {
				// Osty: /tmp/pkgmgr_selfhost_merged.osty:1362:17
				func() struct{} { childNames = append(childNames, child.name); return struct{}{} }()
				// Osty: /tmp/pkgmgr_selfhost_merged.osty:1363:17
				func() struct{} { rest = append(rest, child); return struct{}{} }()
			}
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:1365:13
			func() struct{} {
				next.nodes = append(next.nodes, selfPkgGraphNode(decision.name, decision.packageName, decision.version, decision.source, decision.checksum, childNames))
				return struct{}{}
			}()
		}
	}
	return selfPkgResolveRegistryPending(next, rest, candidates, candidateDeps, locked)
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:1381:5
type SelfPkgGraphNodeLookup struct {
	found bool
	node  *SelfPkgGraphNode
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:1387:5
type SelfPkgCandidateDeps struct {
	packageName  string
	version      *SemVersion
	dependencies []*SelfPkgDependency
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:1394:5
// Osty: /tmp/pkgmgr_selfhost_merged.osty:1402:1
func selfPkgFindGraphNode(name string, nodes []*SelfPkgGraphNode) *SelfPkgGraphNodeLookup {
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1403:5
	for _, node := range nodes {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1404:9
		if node.name == name {
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:1405:13
			return &SelfPkgGraphNodeLookup{found: true, node: node}
		}
	}
	return &SelfPkgGraphNodeLookup{found: false, node: emptySelfPkgGraphNode()}
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:1411:1
func selfPkgCandidateDependencyList(packageName string, version *SemVersion, candidates []*SelfPkgCandidateDeps) []*SelfPkgDependency {
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1416:5
	for _, item := range candidates {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1417:9
		if item.packageName == packageName && compareSemVersion(item.version, version) == 0 {
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:1418:13
			return item.dependencies
		}
	}
	return make([]*SelfPkgDependency, 0, 1)
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:1424:1
func selfPkgDropFirstDependency(deps []*SelfPkgDependency) []*SelfPkgDependency {
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1425:5
	var out []*SelfPkgDependency = make([]*SelfPkgDependency, 0, 1)
	_ = out
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1426:5
	idx := 0
	_ = idx
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1427:5
	for _, dep := range deps {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1428:9
		if idx > 0 {
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:1429:13
			func() struct{} { out = append(out, dep); return struct{}{} }()
		}
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1431:9
		func() {
			var _cur54 int = idx
			var _rhs55 int = 1
			if _rhs55 > 0 && _cur54 > math.MaxInt-_rhs55 {
				panic("integer overflow")
			}
			if _rhs55 < 0 && _cur54 < math.MinInt-_rhs55 {
				panic("integer overflow")
			}
			idx = _cur54 + _rhs55
		}()
	}
	return out
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:1437:5
func selfPkgTopoOrder(nodes []*SelfPkgGraphNode) []string {
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1438:5
	var out []string = make([]string, 0, 1)
	_ = out
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1439:5
	var names []string = make([]string, 0, 1)
	_ = names
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1440:5
	for _, node := range nodes {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1441:9
		names = selfPkgInsertStringSorted(names, node.name)
	}
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1443:5
	for _, name := range names {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1444:9
		out = selfPkgTopoVisit(name, nodes, out)
	}
	return out
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:1449:1
func selfPkgTopoVisit(name string, nodes []*SelfPkgGraphNode, out []string) []string {
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1454:5
	if selfPkgStringListHas(out, name) {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1455:9
		return out
	}
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1457:5
	lookup := selfPkgFindGraphNode(name, nodes)
	_ = lookup
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1458:5
	if !(lookup.found) {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1459:9
		return out
	}
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1461:5
	next := out
	_ = next
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1462:5
	var deps []string = make([]string, 0, 1)
	_ = deps
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1463:5
	for _, dep := range lookup.node.deps {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1464:9
		deps = selfPkgInsertStringSorted(deps, dep)
	}
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1466:5
	for _, dep := range deps {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1467:9
		next = selfPkgTopoVisit(dep, nodes, next)
	}
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1469:5
	if !(selfPkgStringListHas(next, name)) {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1470:9
		func() struct{} { next = append(next, name); return struct{}{} }()
	}
	return next
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:1475:1
func selfPkgInsertStringSorted(items []string, item string) []string {
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1476:5
	var out []string = make([]string, 0, 1)
	_ = out
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1477:5
	inserted := false
	_ = inserted
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1478:5
	for _, existing := range items {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1479:9
		if !(inserted) && item < existing {
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:1480:13
			func() struct{} { out = append(out, item); return struct{}{} }()
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:1481:13
			inserted = true
		}
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1483:9
		if existing != item {
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:1484:13
			func() struct{} { out = append(out, existing); return struct{}{} }()
		}
	}
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1487:5
	if !(inserted) && !(selfPkgStringListHas(out, item)) {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1488:9
		func() struct{} { out = append(out, item); return struct{}{} }()
	}
	return out
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:1493:1
func selfPkgStringListHas(items []string, item string) bool {
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1494:5
	for _, existing := range items {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1495:9
		if existing == item {
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:1496:13
			return true
		}
	}
	return false
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:1503:5
func selfPkgDepLookupItem(name string, gitURL string) *SelfPkgDepLookupItem {
	return &SelfPkgDepLookupItem{name: name, gitURL: gitURL}
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:1508:5
func selfPkgLookupDependency(rawPath string, graphNodes []*SelfPkgDepLookupItem, manifestDeps []*SelfPkgDepLookupItem) *SelfPkgDepLookupResult {
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1513:5
	graphAlias := selfPkgFindLookupItemByName(graphNodes, rawPath)
	_ = graphAlias
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1514:5
	if graphAlias.found {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1515:9
		return graphAlias
	}
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1517:5
	manifestAlias := selfPkgFindLookupItemByName(manifestDeps, rawPath)
	_ = manifestAlias
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1518:5
	if manifestAlias.found {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1519:9
		return manifestAlias
	}
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1521:5
	if selfPkgPathHasSlash(rawPath) {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1522:9
		graphGit := selfPkgFindLookupItemByGitURL(graphNodes, rawPath)
		_ = graphGit
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1523:9
		if graphGit.found {
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:1524:13
			return graphGit
		}
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1526:9
		manifestGit := selfPkgFindLookupItemByGitURL(manifestDeps, rawPath)
		_ = manifestGit
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1527:9
		if manifestGit.found {
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:1528:13
			return manifestGit
		}
	}
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1531:5
	last := selfPkgLastPathSegment(rawPath)
	_ = last
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1532:5
	if last != rawPath {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1533:9
		graphLast := selfPkgFindLookupItemByName(graphNodes, last)
		_ = graphLast
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1534:9
		if graphLast.found {
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:1535:13
			return graphLast
		}
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1537:9
		manifestLast := selfPkgFindLookupItemByName(manifestDeps, last)
		_ = manifestLast
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1538:9
		if manifestLast.found {
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:1539:13
			return manifestLast
		}
	}
	return &SelfPkgDepLookupResult{found: false, name: ""}
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:1545:1
func selfPkgFindLookupItemByName(items []*SelfPkgDepLookupItem, name string) *SelfPkgDepLookupResult {
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1549:5
	for _, item := range items {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1550:9
		if item.name == name {
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:1551:13
			return &SelfPkgDepLookupResult{found: true, name: item.name}
		}
	}
	return &SelfPkgDepLookupResult{found: false, name: ""}
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:1557:1
func selfPkgFindLookupItemByGitURL(items []*SelfPkgDepLookupItem, rawPath string) *SelfPkgDepLookupResult {
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1561:5
	needle := selfPkgNormalizeGitURL(rawPath)
	_ = needle
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1562:5
	for _, item := range items {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1563:9
		if item.gitURL != "" && selfPkgNormalizeGitURL(item.gitURL) == needle {
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:1564:13
			return &SelfPkgDepLookupResult{found: true, name: item.name}
		}
	}
	return &SelfPkgDepLookupResult{found: false, name: ""}
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:1571:5
func selfPkgNormalizeGitURL(url string) string {
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1572:5
	text := pkgStrings.TrimSuffix(url, "/")
	_ = text
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1573:5
	text = pkgStrings.TrimSuffix(text, ".git")
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1574:5
	scheme := pkgStrings.SplitN(text, "://", 2)
	_ = scheme
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1575:5
	if selfPkgStringListCount(scheme) == 2 {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1576:9
		text = scheme[1]
	}
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1578:5
	if pkgStrings.HasPrefix(text, "git@") {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1579:9
		text = pkgStrings.TrimPrefix(text, "git@")
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1580:9
		scp := pkgStrings.SplitN(text, ":", 2)
		_ = scp
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1581:9
		if selfPkgStringListCount(scp) == 2 {
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:1582:13
			host := scp[0]
			_ = host
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:1583:13
			repo := scp[1]
			_ = repo
			// Osty: /tmp/pkgmgr_selfhost_merged.osty:1584:13
			text = fmt.Sprintf("%s/%s", ostyToString(host), ostyToString(repo))
		}
	}
	return text
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:1590:1
func selfPkgPathHasSlash(path string) bool {
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1591:5
	parts := pkgStrings.Split(path, "/")
	_ = parts
	return selfPkgStringListCount(parts) > 1
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:1595:1
func selfPkgLastPathSegment(path string) string {
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1596:5
	last := path
	_ = last
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1597:5
	for _, part := range pkgStrings.Split(path, "/") {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1598:9
		last = part
	}
	return last
}

// Osty: /tmp/pkgmgr_selfhost_merged.osty:1603:1
func selfPkgStringListCount(items []string) int {
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1604:5
	count := 0
	_ = count
	// Osty: /tmp/pkgmgr_selfhost_merged.osty:1605:5
	for _, item := range items {
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1606:9
		_ = item
		// Osty: /tmp/pkgmgr_selfhost_merged.osty:1607:9
		func() {
			var _cur56 int = count
			var _rhs57 int = 1
			if _rhs57 > 0 && _cur56 > math.MaxInt-_rhs57 {
				panic("integer overflow")
			}
			if _rhs57 < 0 && _cur56 < math.MinInt-_rhs57 {
				panic("integer overflow")
			}
			count = _cur56 + _rhs57
		}()
	}
	return count
}
