//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strconv"

	"github.com/osty/osty/internal/bootstrap/seedgen"
	"github.com/osty/osty/internal/llvmgen"
)

const supportSnapshotHeader = `// support_snapshot.go snapshots the Osty-authored LLVM helper surface into
// the native backend package so the bridge file can stay deleted while
// toolchain sources remain the long-term owner.
`

const toolchainSourceLineOffset = 6

var (
	generatedHeaderRE = regexp.MustCompile(`(?m)\A// Code generated by osty\. DO NOT EDIT\.\n// Osty source: .*\n`)
	helperContainsRE  = regexp.MustCompile("(?s)// Osty: .*\\nfunc ostyStringsContains\\(s string, substr string\\) bool \\{\\n\\treturn llvmStrings\\.Contains\\(s, substr\\)\\n\\}\\n\\n")
	helperPrefixRE    = regexp.MustCompile("(?s)// Osty: .*\\nfunc ostyStringsHasPrefix\\(s string, prefix string\\) bool \\{\\n\\treturn llvmStrings\\.HasPrefix\\(s, prefix\\)\\n\\}\\n\\n")
	cStringEscapeRE   = regexp.MustCompile(`(?s)func llvmCStringEscape\(text string\) string \{\n.*?\n\}\n`)
	mergedCommentRE   = regexp.MustCompile(`// Osty: .*?/merged\.osty:(\d+):(\d+)`)
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run() error {
	root, err := findRepoRoot()
	if err != nil {
		return err
	}
	outPath := filepath.Join(root, "internal/llvmgen/support_snapshot.go")
	tmpDir, err := os.MkdirTemp("", "osty-llvmgen-snapshot-*")
	if err != nil {
		return fmt.Errorf("create llvmgen temp dir: %w", err)
	}
	defer os.RemoveAll(tmpDir)

	merged, err := llvmgen.MergeToolchainSupport(root)
	if err != nil {
		return err
	}
	merged = bytes.ReplaceAll(merged, []byte("\r\n"), []byte("\n"))
	mergedPath := filepath.Join(tmpDir, "merged.osty")
	if err := os.WriteFile(mergedPath, merged, 0o644); err != nil {
		return fmt.Errorf("write merged llvmgen support: %w", err)
	}
	data, err := seedgen.Generate(seedgen.Config{
		SourcePath:  mergedPath,
		PackageName: "llvmgen",
		RepoRoot:    root,
	})
	if err != nil {
		return fmt.Errorf("generate llvmgen support snapshot: %w", err)
	}
	data = postprocessSnapshot(data)
	return installWithCompileGate(root, outPath, data)
}

func postprocessSnapshot(data []byte) []byte {
	out := generatedHeaderRE.ReplaceAll(data, []byte(supportSnapshotHeader))
	out = helperContainsRE.ReplaceAll(out, nil)
	out = helperPrefixRE.ReplaceAll(out, nil)
	out = bytes.ReplaceAll(out, []byte("ostyStringsContains("), []byte("llvmStrings.Contains("))
	out = bytes.ReplaceAll(out, []byte("ostyStringsHasPrefix("), []byte("llvmStrings.HasPrefix("))
	out = cStringEscapeRE.ReplaceAll(out, []byte(`func llvmCStringEscape(text string) string {
	var b llvmStrings.Builder
	b.Grow(len(text))
	for i := 0; i < len(text); i++ {
		c := text[i]
		switch {
		case c == '"':
			b.WriteString("\\22")
		case c == '\\':
			b.WriteString("\\5C")
		case c >= 0x20 && c <= 0x7E:
			b.WriteByte(c)
		default:
			fmt.Fprintf(&b, "\\%02X", c)
		}
	}
	return b.String()
}
`))
	out = mergedCommentRE.ReplaceAllFunc(out, rewriteMergedComment)
	return out
}

func rewriteMergedComment(match []byte) []byte {
	parts := mergedCommentRE.FindSubmatch(match)
	if len(parts) != 3 {
		return match
	}
	line, err := strconv.Atoi(string(parts[1]))
	if err != nil {
		return match
	}
	col, err := strconv.Atoi(string(parts[2]))
	if err != nil {
		return match
	}
	line -= toolchainSourceLineOffset
	if line < 1 {
		line = 1
	}
	return []byte(fmt.Sprintf("// Osty: toolchain/llvmgen.osty:%d:%d", line, col))
}

func installWithCompileGate(root, outPath string, data []byte) error {
	prev, readErr := os.ReadFile(outPath)
	if readErr != nil && !os.IsNotExist(readErr) {
		return fmt.Errorf("read previous llvmgen support snapshot: %w", readErr)
	}
	havePrev := readErr == nil
	if err := os.WriteFile(outPath, data, 0o644); err != nil {
		return fmt.Errorf("install llvmgen support snapshot: %w", err)
	}
	cmd := exec.Command("go", "test", "-run", "^$", "./internal/llvmgen")
	cmd.Dir = root
	output, err := cmd.CombinedOutput()
	if err == nil {
		return nil
	}
	if havePrev {
		_ = os.WriteFile(outPath, prev, 0o644)
	} else {
		_ = os.Remove(outPath)
	}
	return fmt.Errorf("compile generated llvmgen support snapshot: %w\n%s", err, bytes.TrimSpace(output))
}

func findRepoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("no go.mod ancestor of %s", dir)
		}
		dir = parent
	}
}
