//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strconv"

	"github.com/osty/osty/internal/bootstrap/seedgen"
	"github.com/osty/osty/internal/llvmgen"
)

const mirGenSnapshotHeader = `// mir_generator_snapshot.go snapshots the Osty-authored MIR→LLVM emitter
// helpers into the native backend package so the hand-written
// mir_generator.go shrinks section-by-section as the self-host port lands.
// Source of truth: toolchain/mir_generator.osty. DO NOT EDIT this file by
// hand; run ` + "`go generate ./internal/llvmgen`" + ` after changing the Osty source.
`

const mirGenToolchainSourceLineOffset = 6

var (
	mirGenGeneratedHeaderRE = regexp.MustCompile(`(?m)\A// Code generated by osty\. DO NOT EDIT\.\n// Osty source: .*\n`)
	mirGenContainsRE        = regexp.MustCompile("(?s)// Osty: .*\\nfunc ostyStringsContains\\(s string, substr string\\) bool \\{\\n\\treturn llvmStrings\\.Contains\\(s, substr\\)\\n\\}\\n\\n")
	mirGenPrefixRE          = regexp.MustCompile("(?s)// Osty: .*\\nfunc ostyStringsHasPrefix\\(s string, prefix string\\) bool \\{\\n\\treturn llvmStrings\\.HasPrefix\\(s, prefix\\)\\n\\}\\n\\n")
	mirGenSuffixRE          = regexp.MustCompile("(?s)// Osty: .*\\nfunc ostyStringsHasSuffix\\(s string, suffix string\\) bool \\{\\n\\treturn llvmStrings\\.HasSuffix\\(s, suffix\\)\\n\\}\\n\\n")
	mirGenMergedCommentRE   = regexp.MustCompile(`// Osty: .*?/merged\.osty:(\d+):(\d+)`)
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run() error {
	root, err := findRepoRoot()
	if err != nil {
		return err
	}
	outPath := filepath.Join(root, "internal/llvmgen/mir_generator_snapshot.go")
	tmpDir, err := os.MkdirTemp("", "osty-mirgen-snapshot-*")
	if err != nil {
		return fmt.Errorf("create mirgen temp dir: %w", err)
	}
	defer os.RemoveAll(tmpDir)

	merged, err := llvmgen.MergeToolchainMIRGenerator(root)
	if err != nil {
		return err
	}
	merged = bytes.ReplaceAll(merged, []byte("\r\n"), []byte("\n"))
	mergedPath := filepath.Join(tmpDir, "merged.osty")
	if err := os.WriteFile(mergedPath, merged, 0o644); err != nil {
		return fmt.Errorf("write merged mirgen source: %w", err)
	}
	data, err := seedgen.Generate(seedgen.Config{
		SourcePath:  mergedPath,
		PackageName: "llvmgen",
		RepoRoot:    root,
	})
	if err != nil {
		return fmt.Errorf("generate mirgen snapshot: %w", err)
	}
	data = postprocessMirGenSnapshot(data)
	return installMirGenWithCompileGate(root, outPath, data)
}

func postprocessMirGenSnapshot(data []byte) []byte {
	out := mirGenGeneratedHeaderRE.ReplaceAll(data, []byte(mirGenSnapshotHeader))
	out = mirGenContainsRE.ReplaceAll(out, nil)
	out = mirGenPrefixRE.ReplaceAll(out, nil)
	out = mirGenSuffixRE.ReplaceAll(out, nil)
	out = bytes.ReplaceAll(out, []byte("ostyStringsContains("), []byte("llvmStrings.Contains("))
	out = bytes.ReplaceAll(out, []byte("ostyStringsHasPrefix("), []byte("llvmStrings.HasPrefix("))
	out = bytes.ReplaceAll(out, []byte("ostyStringsHasSuffix("), []byte("llvmStrings.HasSuffix("))
	out = mirGenMergedCommentRE.ReplaceAllFunc(out, rewriteMirGenMergedComment)
	return out
}

func rewriteMirGenMergedComment(match []byte) []byte {
	parts := mirGenMergedCommentRE.FindSubmatch(match)
	if len(parts) != 3 {
		return match
	}
	line, err := strconv.Atoi(string(parts[1]))
	if err != nil {
		return match
	}
	col, err := strconv.Atoi(string(parts[2]))
	if err != nil {
		return match
	}
	line -= mirGenToolchainSourceLineOffset
	if line < 1 {
		line = 1
	}
	return []byte(fmt.Sprintf("// Osty: toolchain/mir_generator.osty:%d:%d", line, col))
}

func installMirGenWithCompileGate(root, outPath string, data []byte) error {
	prev, readErr := os.ReadFile(outPath)
	if readErr != nil && !os.IsNotExist(readErr) {
		return fmt.Errorf("read previous mirgen snapshot: %w", readErr)
	}
	havePrev := readErr == nil
	if err := os.WriteFile(outPath, data, 0o644); err != nil {
		return fmt.Errorf("install mirgen snapshot: %w", err)
	}
	cmd := exec.Command("go", "test", "-run", "^$", "./internal/llvmgen")
	cmd.Dir = root
	output, err := cmd.CombinedOutput()
	if err == nil {
		return nil
	}
	if havePrev {
		_ = os.WriteFile(outPath, prev, 0o644)
	} else {
		_ = os.Remove(outPath)
	}
	return fmt.Errorf("compile generated mirgen snapshot: %w\n%s", err, bytes.TrimSpace(output))
}

func findRepoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("no go.mod ancestor of %s", dir)
		}
		dir = parent
	}
}
