package llvmgen

import (
	"errors"
	"strings"
	"testing"

	"github.com/osty/osty/internal/ast"
	"github.com/osty/osty/internal/parser"
)

func TestGenerateMainPrintsIntegerExpression(t *testing.T) {
	file := parseOK(t, `fn main() {
    println(40 + 2 * 3)
}
`)
	ir, err := Generate(file, Options{
		SourcePath: "/tmp/main.osty",
		Target:     "x86_64-unknown-linux-gnu",
	})
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	text := string(ir)
	for _, want := range []string{
		"; Code generated by osty LLVM backend. DO NOT EDIT.",
		`; Osty: /tmp/main.osty`,
		`source_filename = "/tmp/main.osty"`,
		`target triple = "x86_64-unknown-linux-gnu"`,
		`@.fmt_i64 = private unnamed_addr constant [5 x i8] c"%ld\0A\00"`,
		`declare i32 @printf(ptr, ...)`,
		`define i32 @main() {`,
		`%t0 = mul i64 2, 3`,
		`%t1 = add i64 40, %t0`,
		`call i32 (ptr, ...) @printf(ptr @.fmt_i64, i64 %t1)`,
		`ret i32 0`,
	} {
		if !strings.Contains(text, want) {
			t.Fatalf("IR missing %q:\n%s", want, text)
		}
	}
}

func TestGenerateScriptPrintsIntegerExpression(t *testing.T) {
	file := parseOK(t, `println((10 - 3) % 4)
`)
	ir, err := Generate(file, Options{SourcePath: "/tmp/script.osty"})
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	text := string(ir)
	for _, want := range []string{
		`%t0 = sub i64 10, 3`,
		`%t1 = srem i64 %t0, 4`,
		`call i32 (ptr, ...) @printf(ptr @.fmt_i64, i64 %t1)`,
	} {
		if !strings.Contains(text, want) {
			t.Fatalf("IR missing %q:\n%s", want, text)
		}
	}
}

func TestGenerateFunctionLetIf(t *testing.T) {
	file := parseOK(t, `fn add(a: Int, b: Int) -> Int {
    a + b
}

fn main() {
    let value = add(40, 2)
    if value == 42 {
        println(value)
    } else {
        println(0)
    }
}
`)
	ir, err := Generate(file, Options{SourcePath: "/tmp/scalar.osty"})
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	text := string(ir)
	for _, want := range []string{
		`define i64 @add(i64 %a, i64 %b) {`,
		`%t0 = add i64 %a, %b`,
		`ret i64 %t0`,
		`define i32 @main() {`,
		`%t0 = call i64 @add(i64 40, i64 2)`,
		`%t1 = icmp eq i64 %t0, 42`,
		`br i1 %t1, label %if.then0, label %if.else1`,
		`if.then0:`,
		`call i32 (ptr, ...) @printf(ptr @.fmt_i64, i64 %t0)`,
		`if.else1:`,
		`call i32 (ptr, ...) @printf(ptr @.fmt_i64, i64 0)`,
		`if.end2:`,
		`ret i32 0`,
	} {
		if !strings.Contains(text, want) {
			t.Fatalf("IR missing %q:\n%s", want, text)
		}
	}
}

func TestGenerateMutableRangeLoop(t *testing.T) {
	file := parseOK(t, `fn sumTo(n: Int) -> Int {
    let mut total = 0
    for i in 1..=n {
        total = total + i
    }
    total
}

fn main() {
    println(sumTo(5))
}
`)
	ir, err := Generate(file, Options{SourcePath: "/tmp/control.osty"})
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	text := string(ir)
	for _, want := range []string{
		`define i64 @sumTo(i64 %n) {`,
		`alloca i64`,
		`store i64 0`,
		`store i64 1`,
		`load i64`,
		`icmp sle i64`,
		`br i1`,
		`add i64`,
		`store i64`,
		`br label %for.cond0`,
		`for.end2:`,
		`ret i64`,
		`%t0 = call i64 @sumTo(i64 5)`,
		`call i32 (ptr, ...) @printf(ptr @.fmt_i64, i64 %t0)`,
	} {
		if !strings.Contains(text, want) {
			t.Fatalf("IR missing %q:\n%s", want, text)
		}
	}
}

func TestGenerateBooleanValueIf(t *testing.T) {
	file := parseOK(t, `fn choose(a: Int, b: Int) -> Int {
    if a < b && !(a == 0) {
        b - a
    } else {
        a + b
    }
}

fn main() {
    println(choose(3, 10))
}
`)
	ir, err := Generate(file, Options{SourcePath: "/tmp/booleans.osty"})
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	text := string(ir)
	for _, want := range []string{
		`define i64 @choose(i64 %a, i64 %b) {`,
		`%t0 = icmp slt i64 %a, %b`,
		`%t1 = icmp eq i64 %a, 0`,
		`%t2 = xor i1 %t1, true`,
		`%t3 = and i1 %t0, %t2`,
		`br i1 %t3, label %if.expr.then0, label %if.expr.else1`,
		`if.expr.then0:`,
		`%t4 = sub i64 %b, %a`,
		`if.expr.else1:`,
		`%t5 = add i64 %a, %b`,
		`if.expr.end2:`,
		`%t6 = phi i64 [ %t4, %if.expr.then0 ], [ %t5, %if.expr.else1 ]`,
		`ret i64 %t6`,
		`%t0 = call i64 @choose(i64 3, i64 10)`,
		`call i32 (ptr, ...) @printf(ptr @.fmt_i64, i64 %t0)`,
	} {
		if !strings.Contains(text, want) {
			t.Fatalf("IR missing %q:\n%s", want, text)
		}
	}
}

func TestGenerateUnsupportedShape(t *testing.T) {
	file := parseOK(t, `fn main() {
    println("nope")
}
`)
	_, err := Generate(file, Options{SourcePath: "/tmp/main.osty"})
	if !errors.Is(err, ErrUnsupported) {
		t.Fatalf("Generate error = %v, want ErrUnsupported", err)
	}
	var unsupported *UnsupportedError
	if !errors.As(err, &unsupported) {
		t.Fatalf("Generate error = %T, want *UnsupportedError", err)
	}
	if unsupported.Diagnostic.Code != "LLVM013" || unsupported.Diagnostic.Kind != "expression" {
		t.Fatalf("diagnostic = %+v, want LLVM013 expression", unsupported.Diagnostic)
	}
	if !strings.Contains(err.Error(), "value-if") {
		t.Fatalf("diagnostic hint missing self-hosted expression guidance:\n%s", err.Error())
	}
}

func TestGenerateGoFFIUnsupportedDiagnostic(t *testing.T) {
	file := parseOK(t, `use go "strings" as strings {
    fn Join(elems: List<String>, sep: String) -> String
}

fn main() {
    println(42)
}
`)
	_, err := Generate(file, Options{SourcePath: "/tmp/ffi.osty"})
	if !errors.Is(err, ErrUnsupported) {
		t.Fatalf("Generate error = %v, want ErrUnsupported", err)
	}
	var unsupported *UnsupportedError
	if !errors.As(err, &unsupported) {
		t.Fatalf("Generate error = %T, want *UnsupportedError", err)
	}
	diag := unsupported.Diagnostic
	if diag.Code != "LLVM001" || diag.Kind != "go-only" {
		t.Fatalf("diagnostic = %+v, want LLVM001 go-only", diag)
	}
	for _, want := range []string{`use go "strings"`, "Go backend", "--backend=go"} {
		if !strings.Contains(err.Error(), want) {
			t.Fatalf("diagnostic missing %q:\n%s", want, err.Error())
		}
	}
}

func TestGenerateUnsupportedTaxonomy(t *testing.T) {
	tests := []struct {
		name string
		src  string
		code string
		kind string
	}{
		{
			name: "source layout",
			src:  `fn helper() -> Int { 1 }`,
			code: "LLVM010",
			kind: "source-layout",
		},
		{
			name: "function signature",
			src:  `fn main(value: Int) {}`,
			code: "LLVM017",
			kind: "function-signature",
		},
		{
			name: "type system",
			src: `fn name() -> String {
    1
}

fn main() {
    println(42)
}
`,
			code: "LLVM011",
			kind: "type-system",
		},
		{
			name: "call",
			src: `fn main() {
    println(value: 42)
}
`,
			code: "LLVM015",
			kind: "call",
		},
		{
			name: "name",
			src: `fn main() {
    println(value)
}
`,
			code: "LLVM016",
			kind: "name",
		},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			file := parseOK(t, tc.src)
			_, err := Generate(file, Options{SourcePath: "/tmp/taxonomy.osty"})
			if !errors.Is(err, ErrUnsupported) {
				t.Fatalf("Generate error = %v, want ErrUnsupported", err)
			}
			var unsupported *UnsupportedError
			if !errors.As(err, &unsupported) {
				t.Fatalf("Generate error = %T, want *UnsupportedError", err)
			}
			if unsupported.Diagnostic.Code != tc.code || unsupported.Diagnostic.Kind != tc.kind {
				t.Fatalf("diagnostic = %+v, want %s %s", unsupported.Diagnostic, tc.code, tc.kind)
			}
		})
	}
}

func parseOK(t *testing.T, src string) *ast.File {
	t.Helper()
	file, diags := parser.ParseDiagnostics([]byte(src))
	if len(diags) != 0 {
		t.Fatalf("parse diagnostics: %v", diags)
	}
	return file
}
