// mir_generator_snapshot.go snapshots the Osty-authored MIR→LLVM emitter
// helpers into the native backend package so the hand-written
// mir_generator.go shrinks section-by-section as the self-host port lands.
// Source of truth: toolchain/mir_generator.osty. DO NOT EDIT this file by
// hand; run `go generate ./internal/llvmgen` after changing the Osty source.

package llvmgen

import (
	"math"
	llvmStrings "strings"
)

// Osty: toolchain/mir_generator.osty:32:5
func mirLlvmTypeForPrim(name string) string {
	// Osty: toolchain/mir_generator.osty:33:5
	if name == "Int" || name == "Int64" || name == "UInt64" {
		// Osty: toolchain/mir_generator.osty:34:9
		return "i64"
	}
	// Osty: toolchain/mir_generator.osty:36:5
	if name == "Int32" || name == "UInt32" || name == "Char" {
		// Osty: toolchain/mir_generator.osty:37:9
		return "i32"
	}
	// Osty: toolchain/mir_generator.osty:39:5
	if name == "Int16" || name == "UInt16" {
		// Osty: toolchain/mir_generator.osty:40:9
		return "i16"
	}
	// Osty: toolchain/mir_generator.osty:42:5
	if name == "Int8" || name == "UInt8" || name == "Byte" {
		// Osty: toolchain/mir_generator.osty:43:9
		return "i8"
	}
	// Osty: toolchain/mir_generator.osty:45:5
	if name == "Bool" {
		// Osty: toolchain/mir_generator.osty:46:9
		return "i1"
	}
	// Osty: toolchain/mir_generator.osty:48:5
	if name == "Float" || name == "Float64" {
		// Osty: toolchain/mir_generator.osty:49:9
		return "double"
	}
	// Osty: toolchain/mir_generator.osty:51:5
	if name == "Float32" {
		// Osty: toolchain/mir_generator.osty:52:9
		return "float"
	}
	// Osty: toolchain/mir_generator.osty:55:5
	if name == "String" || name == "Bytes" {
		// Osty: toolchain/mir_generator.osty:56:9
		return "ptr"
	}
	// Osty: toolchain/mir_generator.osty:59:5
	if name == "RawPtr" {
		// Osty: toolchain/mir_generator.osty:60:9
		return "ptr"
	}
	// Osty: toolchain/mir_generator.osty:63:5
	if name == "Unit" || name == "()" {
		// Osty: toolchain/mir_generator.osty:64:9
		return "void"
	}
	// Osty: toolchain/mir_generator.osty:66:5
	if name == "Never" {
		// Osty: toolchain/mir_generator.osty:67:9
		return "void"
	}
	return ""
}

// Osty: toolchain/mir_generator.osty:76:5
func mirLlvmTypeForOpaqueNamed(name string) string {
	// Osty: toolchain/mir_generator.osty:79:5
	if name == "List" || name == "Map" || name == "Set" || name == "Bytes" {
		// Osty: toolchain/mir_generator.osty:80:9
		return "ptr"
	}
	// Osty: toolchain/mir_generator.osty:83:5
	if name == "Channel" || name == "Handle" || name == "Group" || name == "TaskGroup" || name == "Select" || name == "Duration" {
		// Osty: toolchain/mir_generator.osty:85:9
		return "ptr"
	}
	// Osty: toolchain/mir_generator.osty:89:5
	if name == "ClosureEnv" {
		// Osty: toolchain/mir_generator.osty:90:9
		return "ptr"
	}
	return ""
}

// Osty: toolchain/mir_generator.osty:101:5
func mirLlvmTypeHeadName(typeText string) string {
	// Osty: toolchain/mir_generator.osty:105:5
	ltIdx := llvmStrings.Index(typeText, "<")
	_ = ltIdx
	// Osty: toolchain/mir_generator.osty:106:5
	stripped := func() string {
		if ltIdx >= 0 {
			return typeText[0:ltIdx]
		} else {
			return typeText
		}
	}()
	_ = stripped
	// Osty: toolchain/mir_generator.osty:111:5
	dotIdx := llvmStrings.Index(stripped, ".")
	_ = dotIdx
	return func() string {
		if dotIdx >= 0 {
			return stripped[(dotIdx + 1):len(stripped)]
		} else {
			return stripped
		}
	}()
}

// Osty: toolchain/mir_generator.osty:125:5
func mirLlvmTypeIsOptionalSurface(typeText string) bool {
	// Osty: toolchain/mir_generator.osty:126:5
	n := len(typeText)
	_ = n
	// Osty: toolchain/mir_generator.osty:127:5
	if n == 0 {
		// Osty: toolchain/mir_generator.osty:128:9
		return false
	}
	// Osty: toolchain/mir_generator.osty:130:5
	if !llvmStrings.HasSuffix(typeText, "?") {
		// Osty: toolchain/mir_generator.osty:131:9
		return false
	}
	// Osty: toolchain/mir_generator.osty:135:5
	depth := 0
	_ = depth
	// Osty: toolchain/mir_generator.osty:136:5
	i := 0
	_ = i
	// Osty: toolchain/mir_generator.osty:137:5
	prefix := typeText[0:(n - 1)]
	_ = prefix
	// Osty: toolchain/mir_generator.osty:138:5
	plen := len(prefix)
	_ = plen
	// Osty: toolchain/mir_generator.osty:139:5
	for i < plen {
		// Osty: toolchain/mir_generator.osty:140:9
		ch := prefix[i:(i + 1)]
		_ = ch
		// Osty: toolchain/mir_generator.osty:141:9
		if ch == "<" || ch == "(" {
			// Osty: toolchain/mir_generator.osty:142:13
			func() {
				var _cur1 int = depth
				var _rhs2 int = 1
				if _rhs2 > 0 && _cur1 > math.MaxInt-_rhs2 {
					panic("integer overflow")
				}
				if _rhs2 < 0 && _cur1 < math.MinInt-_rhs2 {
					panic("integer overflow")
				}
				depth = _cur1 + _rhs2
			}()
		} else if ch == ">" || ch == ")" {
			// Osty: toolchain/mir_generator.osty:144:13
			func() {
				var _cur3 int = depth
				var _rhs4 int = 1
				if _rhs4 < 0 && _cur3 > math.MaxInt+_rhs4 {
					panic("integer overflow")
				}
				if _rhs4 > 0 && _cur3 < math.MinInt+_rhs4 {
					panic("integer overflow")
				}
				depth = _cur3 - _rhs4
			}()
		}
		// Osty: toolchain/mir_generator.osty:146:9
		func() {
			var _cur5 int = i
			var _rhs6 int = 1
			if _rhs6 > 0 && _cur5 > math.MaxInt-_rhs6 {
				panic("integer overflow")
			}
			if _rhs6 < 0 && _cur5 < math.MinInt-_rhs6 {
				panic("integer overflow")
			}
			i = _cur5 + _rhs6
		}()
	}
	return depth == 0
}

// Osty: toolchain/mir_generator.osty:161:5
func mirIsHeapEqualityType(typeText string) bool {
	return typeText == "String" || typeText == "Bytes"
}

// Osty: toolchain/mir_generator.osty:171:5
func mirIsStringPrimTypeText(typeText string) bool {
	return typeText == "String"
}

// Osty: toolchain/mir_generator.osty:182:5
func mirIsStringOrderingSymbol(symbol string) bool {
	return symbol == "<" || symbol == "<=" || symbol == ">" || symbol == ">="
}

// Osty: toolchain/mir_generator.osty:192:5
func mirStringOrderingPredicate(symbol string) string {
	// Osty: toolchain/mir_generator.osty:193:5
	if symbol == "<" {
		// Osty: toolchain/mir_generator.osty:194:9
		return "slt"
	}
	// Osty: toolchain/mir_generator.osty:196:5
	if symbol == "<=" {
		// Osty: toolchain/mir_generator.osty:197:9
		return "sle"
	}
	// Osty: toolchain/mir_generator.osty:199:5
	if symbol == ">" {
		// Osty: toolchain/mir_generator.osty:200:9
		return "sgt"
	}
	// Osty: toolchain/mir_generator.osty:202:5
	if symbol == ">=" {
		// Osty: toolchain/mir_generator.osty:203:9
		return "sge"
	}
	return ""
}

// Osty: toolchain/mir_generator.osty:215:5
func mirIsUnitTypeText(typeText string) bool {
	return typeText == "Unit" || typeText == "()" || typeText == "Never"
}

// Osty: toolchain/mir_generator.osty:225:5
func mirIsFloatTypeText(typeText string) bool {
	return typeText == "Float" || typeText == "Float32" || typeText == "Float64" || typeText == "double" || typeText == "float"
}

// Osty: toolchain/mir_generator.osty:236:5
func mirIsScalarLLVMType(t string) bool {
	return t == "i1" || t == "i8" || t == "i16" || t == "i32" || t == "i64" || t == "float" || t == "double" || t == "ptr"
}

// Osty: toolchain/mir_generator.osty:246:5
func mirLlvmI1Text(v bool) string {
	// Osty: toolchain/mir_generator.osty:247:5
	if v {
		// Osty: toolchain/mir_generator.osty:248:9
		return "true"
	}
	return "false"
}

// Osty: toolchain/mir_generator.osty:259:5
func mirFirstNonEmpty(vals []string) string {
	// Osty: toolchain/mir_generator.osty:260:5
	n := len(vals)
	_ = n
	// Osty: toolchain/mir_generator.osty:261:5
	i := 0
	_ = i
	// Osty: toolchain/mir_generator.osty:262:5
	for i < n {
		// Osty: toolchain/mir_generator.osty:263:9
		x := vals[i]
		_ = x
		// Osty: toolchain/mir_generator.osty:264:9
		if x != "" {
			// Osty: toolchain/mir_generator.osty:265:13
			return x
		}
		// Osty: toolchain/mir_generator.osty:267:9
		func() {
			var _cur7 int = i
			var _rhs8 int = 1
			if _rhs8 > 0 && _cur7 > math.MaxInt-_rhs8 {
				panic("integer overflow")
			}
			if _rhs8 < 0 && _cur7 < math.MinInt-_rhs8 {
				panic("integer overflow")
			}
			i = _cur7 + _rhs8
		}()
	}
	return ""
}

// Osty: toolchain/mir_generator.osty:279:5
func mirEarliestAfter(input string, needle string) int {
	return llvmStrings.Index(input, needle)
}

// Osty: toolchain/mir_generator.osty:304:5
func mirEncodeLLVMString(s string) string {
	// Osty: toolchain/mir_generator.osty:314:5
	printable := " !#$%&'()*+,-./0123456789:;<=" + ">?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[]^_`abcdefghijklmnopqrstuvwxyz{|}~"
	_ = printable
	// Osty: toolchain/mir_generator.osty:315:5
	out := ""
	_ = out
	// Osty: toolchain/mir_generator.osty:316:5
	n := len(s)
	_ = n
	// Osty: toolchain/mir_generator.osty:317:5
	i := 0
	_ = i
	// Osty: toolchain/mir_generator.osty:318:5
	for i < n {
		// Osty: toolchain/mir_generator.osty:319:9
		ch := s[i:(i + 1)]
		_ = ch
		// Osty: toolchain/mir_generator.osty:320:9
		if ch == "\\" {
			// Osty: toolchain/mir_generator.osty:321:13
			out = out + "\\\\"
		} else if ch == "\"" {
			// Osty: toolchain/mir_generator.osty:323:13
			out = out + "\\22"
		} else if llvmStrings.Contains(printable, ch) {
			// Osty: toolchain/mir_generator.osty:325:13
			out = out + ch
		} else {
			// Osty: toolchain/mir_generator.osty:330:13
			plen := len(printable)
			_ = plen
			// Osty: toolchain/mir_generator.osty:331:13
			trap := printable[(plen + 1):(plen + 2)]
			_ = trap
			// Osty: toolchain/mir_generator.osty:332:13
			return trap
		}
		// Osty: toolchain/mir_generator.osty:334:9
		func() {
			var _cur9 int = i
			var _rhs10 int = 1
			if _rhs10 > 0 && _cur9 > math.MaxInt-_rhs10 {
				panic("integer overflow")
			}
			if _rhs10 < 0 && _cur9 < math.MinInt-_rhs10 {
				panic("integer overflow")
			}
			i = _cur9 + _rhs10
		}()
	}
	return out + "\\00"
}
