[package]
name = "gui-inspector"
version = "0.1.0"
edition = "0.5"
description = "Osty Inspector demo built on std.gui and Qt Quick."

[dependencies]

[gui]
backend = "qtquick"
entry = "ui/main.qml"

[target.arm64-darwin]
link = ["osty_qt"]

[target.amd64-darwin]
link = ["osty_qt"]

[target.amd64-linux]
link = ["osty_qt"]

[target.amd64-windows]
link = ["osty_qt"]
