package doctest

import (
	"fmt"
	"strings"
)

// BuildRunnerSource assembles the synthesised runner file content for
// a slice of extracted doctests. Each doctest becomes a
// `#[test] fn <FnName> () { <body> }` at top level; a single
// `use std.testing as testing` line at the top lets blocks call
// `testing.assertEq` etc. without explicit imports.
//
// The caller is responsible for ordering: doctests are emitted in the
// slice's input order.
func BuildRunnerSource(docs []Doctest) []byte {
	var b strings.Builder
	b.WriteString("// Generated by `osty test --doc` — DO NOT EDIT.\n")
	b.WriteString("// Each #[test] fn wraps one `````osty ````` fenced block.\n")
	b.WriteString("use std.testing as testing\n\n")
	for _, d := range docs {
		fmt.Fprintf(&b, "#[test]\nfn %s() {\n", FnName(d))
		// Indent block body by four spaces so Osty's brace-based
		// structure stays readable in dumps; semantically a no-op.
		for _, ln := range strings.Split(d.Source, "\n") {
			if ln == "" {
				b.WriteByte('\n')
				continue
			}
			b.WriteString("    ")
			b.WriteString(ln)
			b.WriteByte('\n')
		}
		b.WriteString("}\n\n")
	}
	return []byte(b.String())
}

// FnName renders a stable identifier for one doctest. Owner names are
// sanitised to ASCII letters / digits / underscores; any other
// character is rewritten to `_`. Empty owners (file-level doctests,
// not currently extracted) fall back to `file`.
func FnName(d Doctest) string {
	owner := sanitizeIdent(d.Owner)
	if owner == "" {
		owner = "file"
	}
	return fmt.Sprintf("test_doc_%s_%d", owner, d.OrdinalInOwner)
}

func sanitizeIdent(name string) string {
	if name == "" {
		return ""
	}
	var b strings.Builder
	for i, r := range name {
		ok := (r >= 'a' && r <= 'z') ||
			(r >= 'A' && r <= 'Z') ||
			r == '_' ||
			(i > 0 && r >= '0' && r <= '9')
		if ok {
			b.WriteRune(r)
		} else {
			b.WriteByte('_')
		}
	}
	return b.String()
}
