package main

import (
	"strings"
	"testing"

	"github.com/osty/osty/internal/parser"
	"github.com/osty/osty/internal/resolve"
)

// appendDoctestCases: given a package containing at least one
// source file with a ```osty doc block, it should synthesise the
// runner file, attach it, and return one test case per block.

func TestAppendDoctestCasesFindsBlock(t *testing.T) {
	src := []byte("/// Greets.\n" +
		"/// ```osty\n" +
		"/// let n = 1 + 2\n" +
		"/// let _ = n\n" +
		"/// ```\n" +
		"pub fn greet() -> Int { 0 }\n")
	pkg := singleFilePackageForDoctest(t, "greet.osty", src)
	tests, err := appendDoctestCases(pkg, nil)
	if err != nil {
		t.Fatalf("appendDoctestCases: %v", err)
	}
	if len(tests) != 1 {
		t.Fatalf("expected 1 doctest case, got %d", len(tests))
	}
	if tests[0].Name != "test_doc_greet_1" {
		t.Errorf("name: got %q, want test_doc_greet_1", tests[0].Name)
	}
	if !strings.HasSuffix(tests[0].Path, doctestRunnerFilename) {
		t.Errorf("path: got %q, want ...%s", tests[0].Path, doctestRunnerFilename)
	}
	// Runner should have been appended to the package.
	if len(pkg.Files) != 2 {
		t.Errorf("expected 2 files (source + runner), got %d", len(pkg.Files))
	}
}

func TestAppendDoctestCasesMultipleBlocks(t *testing.T) {
	src := []byte("/// First.\n" +
		"/// ```osty\n" +
		"/// let _ = 1\n" +
		"/// ```\n" +
		"/// Second.\n" +
		"/// ```osty\n" +
		"/// let _ = 2\n" +
		"/// ```\n" +
		"pub fn api() -> Int { 0 }\n")
	pkg := singleFilePackageForDoctest(t, "api.osty", src)
	tests, err := appendDoctestCases(pkg, nil)
	if err != nil {
		t.Fatalf("appendDoctestCases: %v", err)
	}
	if len(tests) != 2 {
		t.Fatalf("expected 2 doctest cases, got %d", len(tests))
	}
	wantNames := []string{"test_doc_api_1", "test_doc_api_2"}
	for i, tc := range tests {
		if tc.Name != wantNames[i] {
			t.Errorf("tests[%d].Name = %q, want %q", i, tc.Name, wantNames[i])
		}
	}
}

func TestAppendDoctestCasesReturnsEmptyWhenNoBlocks(t *testing.T) {
	src := []byte("pub fn foo() -> Int { 42 }\n")
	pkg := singleFilePackageForDoctest(t, "foo.osty", src)
	tests, err := appendDoctestCases(pkg, nil)
	if err != nil {
		t.Fatalf("appendDoctestCases: %v", err)
	}
	if len(tests) != 0 {
		t.Errorf("expected 0 doctest cases, got %d", len(tests))
	}
	if len(pkg.Files) != 1 {
		t.Errorf("no-doc package should not grow; got %d files", len(pkg.Files))
	}
}

func TestAppendDoctestCasesHonoursFilter(t *testing.T) {
	src := []byte("/// A.\n" +
		"/// ```osty\n" +
		"/// let _ = 1\n" +
		"/// ```\n" +
		"pub fn alpha() -> Int { 1 }\n" +
		"/// B.\n" +
		"/// ```osty\n" +
		"/// let _ = 2\n" +
		"/// ```\n" +
		"pub fn beta() -> Int { 2 }\n")
	pkg := singleFilePackageForDoctest(t, "x.osty", src)
	tests, err := appendDoctestCases(pkg, []string{"alpha"})
	if err != nil {
		t.Fatalf("appendDoctestCases: %v", err)
	}
	if len(tests) != 1 {
		t.Fatalf("expected 1 filtered doctest, got %d", len(tests))
	}
	if tests[0].Name != "test_doc_alpha_1" {
		t.Errorf("filter should keep alpha's test, got %q", tests[0].Name)
	}
}

func TestBuildDoctestRunnerSourceShape(t *testing.T) {
	// One-doc construction. The runner should start with the magic
	// header, import std.testing, and wrap the block in a #[test] fn.
	src := []byte("/// ok.\n" +
		"/// ```osty\n" +
		"/// let _ = 1\n" +
		"/// ```\n" +
		"pub fn a() -> Int { 0 }\n")
	pkg := singleFilePackageForDoctest(t, "a.osty", src)
	_, err := appendDoctestCases(pkg, nil)
	if err != nil {
		t.Fatalf("appendDoctestCases: %v", err)
	}
	// Runner file is the last one appended.
	runner := pkg.Files[len(pkg.Files)-1]
	if runner == nil {
		t.Fatal("runner file missing")
	}
	got := string(runner.Source)
	for _, want := range []string{
		"// Generated by `osty test --doc`",
		"use std.testing as testing",
		"#[test]",
		"fn test_doc_a_1()",
		"let _ = 1",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("runner source missing %q\n--\n%s\n--", want, got)
		}
	}
}

func TestSanitizeIdentSafe(t *testing.T) {
	cases := map[string]string{
		"add":           "add",
		"add-two":       "add_two",
		"parse::<T>":    "parse___T_",
		"":              "",
		"Foo99":         "Foo99",
		"9leading":      "_leading",
		"µ_weird":       "__weird",
		"with space":    "with_space",
	}
	for in, want := range cases {
		if got := sanitizeIdentSafe(in); got != want {
			t.Errorf("sanitizeIdentSafe(%q) = %q, want %q", in, got, want)
		}
	}
}

// singleFilePackageForDoctest parses src into a Package with a
// single file. Fails the test on parse errors.
func singleFilePackageForDoctest(t *testing.T, path string, src []byte) *resolve.Package {
	t.Helper()
	file, diags := parser.ParseDiagnostics(src)
	for _, d := range diags {
		if d != nil && d.Severity.String() == "error" {
			t.Fatalf("parse error: %s", d.Message)
		}
	}
	if file == nil {
		t.Fatal("parse returned nil file")
	}
	return &resolve.Package{
		Name: "docpkg",
		Dir:  ".",
		Files: []*resolve.PackageFile{{
			Path:   path,
			Source: src,
			File:   file,
		}},
	}
}
