package selfhostcache

import (
	"context"
	"crypto/ed25519"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"
)

// TrustedKeyEnv selects the ed25519 public key (hex-encoded, 64
// characters / 32 bytes) the resolver requires manifests to be
// signed by. When unset, signature verification is **disabled** —
// manifests are accepted unsigned. A6 keeps this opt-in so existing
// A4-class deployments keep working until the operator opts into
// signing by setting the env var.
//
// The encoding intentionally matches what `crypto/ed25519`'s
// `MarshalBinary` would produce so a key generated by the
// `osty sign-self` tooling can be pasted directly without
// re-encoding.
const TrustedKeyEnv = "OSTY_SELF_TRUSTED_KEY"

// SignatureSuffix is appended to the manifest URL to derive the
// canonical detached-signature URL. e.g. for a manifest at
// `<base>/<key>.json` the signature lives at `<base>/<key>.json.sig`.
const SignatureSuffix = ".sig"

// SignatureSize is the length in bytes of an ed25519 detached
// signature. Network responses larger than this are rejected
// upstream so a 4 GB payload at the signature URL cannot exhaust
// memory.
const SignatureSize = ed25519.SignatureSize

// ErrSignatureMissing surfaces when the registry returned a 404 for
// the signature URL but a trusted key is configured. Treated as a
// hard failure — falling back to unsigned manifests would defeat
// the security goal.
var ErrSignatureMissing = errors.New("selfhostcache: signature missing for manifest but trusted key is configured")

// ErrSignatureInvalid surfaces when the manifest body fails ed25519
// verification against the trusted key. The downloaded binary is
// rejected and the cache is left untouched.
var ErrSignatureInvalid = errors.New("selfhostcache: manifest signature does not verify under trusted key")

// ErrTrustedKeyMalformed surfaces when `OSTY_SELF_TRUSTED_KEY` is
// set but does not decode to a valid 32-byte ed25519 public key.
// Promoted to a hard error so a typo'd key is caught at startup
// instead of silently disabling verification.
var ErrTrustedKeyMalformed = errors.New("selfhostcache: trusted key not a 64-char hex ed25519 public key")

// TrustedKey returns the ed25519 public key the resolver should
// require manifests to be signed under. The boolean return is
// `false` when no key is configured — the caller must treat that
// as "verification disabled" and accept unsigned manifests.
//
// Resolution order: OSTY_SELF_TRUSTED_KEY env var first, then the
// repo-committed `DefaultTrustedKeyHex` constant. Empty default +
// unset env preserves the legacy warn-only behaviour (A6); a
// committed default upgrades fresh clones to verify-by-default
// without requiring users to discover and export the env var.
func TrustedKey() (ed25519.PublicKey, bool, error) {
	return trustedKeyWithDefault(DefaultTrustedKeyHex)
}

// trustedKeyWithDefault is the test-friendly form of TrustedKey —
// callers inject the default explicitly so the unit suite can
// exercise both the "default unset" (legacy warn-only) and
// "default present" (fresh-clone verify) branches without rewriting
// package-level state.
func trustedKeyWithDefault(defaultHex string) (ed25519.PublicKey, bool, error) {
	raw := strings.TrimSpace(os.Getenv(TrustedKeyEnv))
	if raw == "" {
		raw = strings.TrimSpace(defaultHex)
	}
	if raw == "" {
		return nil, false, nil
	}
	pub, err := ParseTrustedKey(raw)
	if err != nil {
		return nil, false, err
	}
	return pub, true, nil
}

// ParseTrustedKey decodes a hex-encoded ed25519 public key.
// Exposed so tests + the producer-side `osty sign-self` CLI share
// one source of truth for the key encoding.
func ParseTrustedKey(s string) (ed25519.PublicKey, error) {
	s = strings.TrimSpace(s)
	if len(s) != ed25519.PublicKeySize*2 {
		return nil, fmt.Errorf("%w (got %d hex chars, want %d)", ErrTrustedKeyMalformed, len(s), ed25519.PublicKeySize*2)
	}
	bytes, err := hex.DecodeString(s)
	if err != nil {
		return nil, fmt.Errorf("%w: %v", ErrTrustedKeyMalformed, err)
	}
	return ed25519.PublicKey(bytes), nil
}

// VerifyManifest checks the detached `signature` against `body`
// using `pub`. Returns `ErrSignatureInvalid` on mismatch — callers
// surface that as the canonical signature-failure.
func VerifyManifest(pub ed25519.PublicKey, body, signature []byte) error {
	if len(signature) != SignatureSize {
		return fmt.Errorf("%w (signature length %d, want %d)", ErrSignatureInvalid, len(signature), SignatureSize)
	}
	if !ed25519.Verify(pub, body, signature) {
		return ErrSignatureInvalid
	}
	return nil
}

// fetchSignature pulls the detached ed25519 signature from
// `<manifestURL>.sig` using the same client as the manifest +
// binary. A `404` collapses to `ErrSignatureMissing` so callers can
// distinguish "registry doesn't sign" from "transport blew up".
func fetchSignature(ctx context.Context, client *http.Client, manifestURL string) ([]byte, error) {
	url := manifestURL + SignatureSuffix
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Accept", "application/octet-stream")
	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("selfhostcache: GET %s: %w", url, err)
	}
	defer resp.Body.Close()
	if resp.StatusCode == http.StatusNotFound {
		return nil, ErrSignatureMissing
	}
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("selfhostcache: GET %s: HTTP %d", url, resp.StatusCode)
	}
	// Accept either raw bytes (64 octets) or hex-encoded (128 hex
	// chars). The hex form is friendlier for storage backends that
	// reject binary uploads (some object stores reject empty MIME).
	// Allow up to 16 trailing whitespace chars so a `cat`-into-secret
	// or `printf '%s\n'` pipeline doesn't trip the limit.
	const maxSigSize = SignatureSize*2 + 16
	body, err := io.ReadAll(io.LimitReader(resp.Body, maxSigSize+1))
	if err != nil {
		return nil, fmt.Errorf("selfhostcache: read signature: %w", err)
	}
	if len(body) > maxSigSize {
		return nil, fmt.Errorf("selfhostcache: signature exceeds %d bytes", maxSigSize)
	}
	return decodeSignature(body)
}

// decodeSignature accepts raw or hex-encoded ed25519 signature
// bytes and returns the canonical 64-byte form.
func decodeSignature(body []byte) ([]byte, error) {
	switch len(body) {
	case SignatureSize:
		out := make([]byte, SignatureSize)
		copy(out, body)
		return out, nil
	case SignatureSize * 2:
		out := make([]byte, SignatureSize)
		if _, err := hex.Decode(out, body); err != nil {
			return nil, fmt.Errorf("selfhostcache: signature hex decode: %w", err)
		}
		return out, nil
	default:
		// Try trimming trailing whitespace (curl|cat output) and
		// retry once as hex.
		trimmed := strings.TrimSpace(string(body))
		if len(trimmed) == SignatureSize*2 {
			out := make([]byte, SignatureSize)
			if _, err := hex.Decode(out, []byte(trimmed)); err != nil {
				return nil, fmt.Errorf("selfhostcache: signature hex decode: %w", err)
			}
			return out, nil
		}
		return nil, fmt.Errorf("selfhostcache: unexpected signature length %d (want %d raw or %d hex)", len(body), SignatureSize, SignatureSize*2)
	}
}
