// Code generated by internal/selfhost/astbridge/gen_astbridge.go from internal/ast/ast.go. DO NOT EDIT.

package astbridge

import (
	"github.com/osty/osty/internal/ast"
	"github.com/osty/osty/internal/token"
)

type (
	File           = *ast.File
	Decl           = ast.Decl
	FnDecl         = *ast.FnDecl
	Stmt           = ast.Stmt
	Expr           = ast.Expr
	Type           = ast.Type
	Pattern        = ast.Pattern
	Block          = *ast.Block
	Annotation     = *ast.Annotation
	AnnotationArg  = *ast.AnnotationArg
	GenericParam   = *ast.GenericParam
	Receiver       = *ast.Receiver
	Param          = *ast.Param
	Field          = *ast.Field
	Variant        = *ast.Variant
	Arg            = *ast.Arg
	MapEntry       = *ast.MapEntry
	MatchArm       = *ast.MatchArm
	StructLitField = *ast.StructLitField
	StructPatField = *ast.StructPatField
	Pos            = token.Pos
	Token          = token.Token
	Kind           = token.Kind
)

func NilDecl() Decl                             { return nil }
func NilFnDecl() FnDecl                         { return nil }
func NilStmt() Stmt                             { return nil }
func NilExpr() Expr                             { return nil }
func NilType() Type                             { return nil }
func NilPattern() Pattern                       { return nil }
func NilBlock() Block                           { return nil }
func NilReceiver() Receiver                     { return nil }
func NilParam() Param                           { return nil }
func NilField() Field                           { return nil }
func NilVariant() Variant                       { return nil }
func NilAnnotation() Annotation                 { return nil }
func NilAnnotationArg() AnnotationArg           { return nil }
func NilGenericParam() GenericParam             { return nil }
func NilArg() Arg                               { return nil }
func NilMatchArm() MatchArm                     { return nil }
func NilStructLitField() StructLitField         { return nil }
func NilStructPatField() StructPatField         { return nil }
func IsNilDecl(v Decl) bool                     { return v == nil }
func IsNilFnDecl(v FnDecl) bool                 { return v == nil }
func IsNilStmt(v Stmt) bool                     { return v == nil }
func IsNilExpr(v Expr) bool                     { return v == nil }
func IsNilType(v Type) bool                     { return v == nil }
func IsNilPattern(v Pattern) bool               { return v == nil }
func IsNilBlock(v Block) bool                   { return v == nil }
func IsNilReceiver(v Receiver) bool             { return v == nil }
func IsNilParam(v Param) bool                   { return v == nil }
func IsNilField(v Field) bool                   { return v == nil }
func IsNilVariant(v Variant) bool               { return v == nil }
func IsNilAnnotation(v Annotation) bool         { return v == nil }
func IsNilAnnotationArg(v AnnotationArg) bool   { return v == nil }
func IsNilGenericParam(v GenericParam) bool     { return v == nil }
func IsNilArg(v Arg) bool                       { return v == nil }
func IsNilMatchArm(v MatchArm) bool             { return v == nil }
func IsNilStructLitField(v StructLitField) bool { return v == nil }
func IsNilStructPatField(v StructPatField) bool { return v == nil }

func EmptyDeclList() []Decl                     { return nil }
func EmptyFnDeclList() []FnDecl                 { return nil }
func EmptyStmtList() []Stmt                     { return nil }
func EmptyExprList() []Expr                     { return nil }
func EmptyTypeList() []Type                     { return nil }
func EmptyPatternList() []Pattern               { return nil }
func EmptyAnnotationList() []Annotation         { return nil }
func EmptyAnnotationArgList() []AnnotationArg   { return nil }
func EmptyGenericParamList() []GenericParam     { return nil }
func EmptyParamList() []Param                   { return nil }
func EmptyFieldList() []Field                   { return nil }
func EmptyVariantList() []Variant               { return nil }
func EmptyArgList() []Arg                       { return nil }
func EmptyMapEntryList() []MapEntry             { return nil }
func EmptyMatchArmList() []MatchArm             { return nil }
func EmptyStructLitFieldList() []StructLitField { return nil }
func EmptyStructPatFieldList() []StructPatField { return nil }

func KindEOF() Kind        { return token.EOF }
func KindIllegal() Kind    { return token.ILLEGAL }
func KindNewline() Kind    { return token.NEWLINE }
func KindIdent() Kind      { return token.IDENT }
func KindInt() Kind        { return token.INT }
func KindFloat() Kind      { return token.FLOAT }
func KindChar() Kind       { return token.CHAR }
func KindByte() Kind       { return token.BYTE }
func KindString() Kind     { return token.STRING }
func KindRawString() Kind  { return token.RAWSTRING }
func KindFn() Kind         { return token.FN }
func KindStruct() Kind     { return token.STRUCT }
func KindEnum() Kind       { return token.ENUM }
func KindInterface() Kind  { return token.INTERFACE }
func KindType() Kind       { return token.TYPE }
func KindLet() Kind        { return token.LET }
func KindMut() Kind        { return token.MUT }
func KindPub() Kind        { return token.PUB }
func KindIf() Kind         { return token.IF }
func KindElse() Kind       { return token.ELSE }
func KindMatch() Kind      { return token.MATCH }
func KindFor() Kind        { return token.FOR }
func KindBreak() Kind      { return token.BREAK }
func KindContinue() Kind   { return token.CONTINUE }
func KindReturn() Kind     { return token.RETURN }
func KindUse() Kind        { return token.USE }
func KindDefer() Kind      { return token.DEFER }
func KindLParen() Kind     { return token.LPAREN }
func KindRParen() Kind     { return token.RPAREN }
func KindLBrace() Kind     { return token.LBRACE }
func KindRBrace() Kind     { return token.RBRACE }
func KindLBracket() Kind   { return token.LBRACKET }
func KindRBracket() Kind   { return token.RBRACKET }
func KindComma() Kind      { return token.COMMA }
func KindColon() Kind      { return token.COLON }
func KindSemicolon() Kind  { return token.SEMICOLON }
func KindDot() Kind        { return token.DOT }
func KindPlus() Kind       { return token.PLUS }
func KindMinus() Kind      { return token.MINUS }
func KindStar() Kind       { return token.STAR }
func KindSlash() Kind      { return token.SLASH }
func KindPercent() Kind    { return token.PERCENT }
func KindEq() Kind         { return token.EQ }
func KindNeq() Kind        { return token.NEQ }
func KindLt() Kind         { return token.LT }
func KindGt() Kind         { return token.GT }
func KindLeq() Kind        { return token.LEQ }
func KindGeq() Kind        { return token.GEQ }
func KindAnd() Kind        { return token.AND }
func KindOr() Kind         { return token.OR }
func KindNot() Kind        { return token.NOT }
func KindBitAnd() Kind     { return token.BITAND }
func KindBitOr() Kind      { return token.BITOR }
func KindBitXor() Kind     { return token.BITXOR }
func KindBitNot() Kind     { return token.BITNOT }
func KindShl() Kind        { return token.SHL }
func KindShr() Kind        { return token.SHR }
func KindAssign() Kind     { return token.ASSIGN }
func KindPlusEq() Kind     { return token.PLUSEQ }
func KindMinusEq() Kind    { return token.MINUSEQ }
func KindStarEq() Kind     { return token.STAREQ }
func KindSlashEq() Kind    { return token.SLASHEQ }
func KindPercentEq() Kind  { return token.PERCENTEQ }
func KindBitAndEq() Kind   { return token.BITANDEQ }
func KindBitOrEq() Kind    { return token.BITOREQ }
func KindBitXorEq() Kind   { return token.BITXOREQ }
func KindShlEq() Kind      { return token.SHLEQ }
func KindShrEq() Kind      { return token.SHREQ }
func KindQuestion() Kind   { return token.QUESTION }
func KindQDot() Kind       { return token.QDOT }
func KindQQ() Kind         { return token.QQ }
func KindDotDot() Kind     { return token.DOTDOT }
func KindDotDotEq() Kind   { return token.DOTDOTEQ }
func KindArrow() Kind      { return token.ARROW }
func KindChanArrow() Kind  { return token.CHANARROW }
func KindColonColon() Kind { return token.COLONCOLON }
func KindUnderscore() Kind { return token.UNDERSCORE }
func KindAt() Kind         { return token.AT }
func KindHash() Kind       { return token.HASH }

func FileNode(pos, end Pos, uses []Decl, decls []Decl, stmts []Stmt) File {
	f := &ast.File{PosV: pos, EndV: end, Stmts: compactStmts(stmts)}
	for _, d := range uses {
		if u, ok := d.(*ast.UseDecl); ok && u != nil {
			f.Uses = append(f.Uses, u)
		}
	}
	f.Decls = compactDecls(decls)
	return f
}

func FnDeclNode(pos, end Pos, pub bool, name string, generics []GenericParam, recv Receiver, params []Param, ret Type, body Block, doc string, anns []Annotation) FnDecl {
	return &ast.FnDecl{
		PosV:        pos,
		EndV:        end,
		Pub:         pub,
		Name:        name,
		Generics:    compactGenericParams(generics),
		Recv:        recv,
		Params:      compactParams(params),
		ReturnType:  ret,
		Body:        body,
		DocComment:  doc,
		Annotations: compactAnnotations(anns),
	}
}

func FnDeclAsDecl(fn FnDecl) Decl {
	if fn == nil {
		return nil
	}
	return fn
}

func ReceiverNode(pos, end Pos, mut bool, mutPos Pos) Receiver {
	return &ast.Receiver{PosV: pos, EndV: end, Mut: mut, MutPos: mutPos}
}

func StructDeclNode(pos, end Pos, pub bool, name string, generics []GenericParam, fields []Field, methods []FnDecl, doc string, anns []Annotation) Decl {
	return &ast.StructDecl{
		PosV:        pos,
		EndV:        end,
		Pub:         pub,
		Name:        name,
		Generics:    compactGenericParams(generics),
		Fields:      compactFields(fields),
		Methods:     compactFnDecls(methods),
		DocComment:  doc,
		Annotations: compactAnnotations(anns),
	}
}

func EnumDeclNode(pos, end Pos, pub bool, name string, generics []GenericParam, variants []Variant, methods []FnDecl, doc string, anns []Annotation) Decl {
	return &ast.EnumDecl{
		PosV:        pos,
		EndV:        end,
		Pub:         pub,
		Name:        name,
		Generics:    compactGenericParams(generics),
		Variants:    compactVariants(variants),
		Methods:     compactFnDecls(methods),
		DocComment:  doc,
		Annotations: compactAnnotations(anns),
	}
}

func InterfaceDeclNode(pos, end Pos, pub bool, name string, generics []GenericParam, extends []Type, methods []FnDecl, doc string, anns []Annotation) Decl {
	return &ast.InterfaceDecl{
		PosV:        pos,
		EndV:        end,
		Pub:         pub,
		Name:        name,
		Generics:    compactGenericParams(generics),
		Extends:     compactTypes(extends),
		Methods:     compactFnDecls(methods),
		DocComment:  doc,
		Annotations: compactAnnotations(anns),
	}
}

func TypeAliasDeclNode(pos, end Pos, pub bool, name string, generics []GenericParam, target Type, doc string, anns []Annotation) Decl {
	return &ast.TypeAliasDecl{
		PosV:        pos,
		EndV:        end,
		Pub:         pub,
		Name:        name,
		Generics:    compactGenericParams(generics),
		Target:      target,
		DocComment:  doc,
		Annotations: compactAnnotations(anns),
	}
}

func UseDeclNode(pos, end Pos, raw string, path []string, isGo bool, alias string, body []Decl) Decl {
	u := &ast.UseDecl{PosV: pos, EndV: end, Path: compactStrings(path), RawPath: raw, Alias: alias, IsGoFFI: isGo, GoBody: compactDecls(body)}
	if isGo {
		u.GoPath = raw
	} else if useDeclIsRuntimeFFI(u) {
		u.IsRuntimeFFI = true
		u.RuntimePath = raw
	}
	return u
}

func useDeclIsRuntimeFFI(u *ast.UseDecl) bool {
	return u != nil && len(u.GoBody) > 0 && len(u.Path) > 0 && u.Path[0] == "runtime"
}

func LetDeclNode(pos, end Pos, pub, mut bool, mutPos Pos, name string, typ Type, value Expr, doc string, anns []Annotation) Decl {
	return &ast.LetDecl{
		PosV:        pos,
		EndV:        end,
		Pub:         pub,
		Mut:         mut,
		MutPos:      mutPos,
		Name:        name,
		Type:        typ,
		Value:       value,
		DocComment:  doc,
		Annotations: compactAnnotations(anns),
	}
}

func FieldNode(pos, end Pos, pub bool, name string, typ Type, def Expr, doc string, anns []Annotation) Field {
	return &ast.Field{PosV: pos, EndV: end, Pub: pub, Name: name, Type: typ, Default: def, DocComment: doc, Annotations: compactAnnotations(anns)}
}

func VariantNode(pos, end Pos, name string, fields []Type, anns []Annotation, doc string) Variant {
	return &ast.Variant{PosV: pos, EndV: end, Name: name, Fields: compactTypes(fields), Annotations: compactAnnotations(anns), DocComment: doc}
}

func ParamNode(pos, end Pos, name string, pat Pattern, typ Type, def Expr) Param {
	return &ast.Param{PosV: pos, EndV: end, Name: name, Pattern: pat, Type: typ, Default: def}
}

func GenericParamNode(pos, end Pos, name string, constraints []Type) GenericParam {
	return &ast.GenericParam{PosV: pos, EndV: end, Name: name, Constraints: compactTypes(constraints)}
}

func AnnotationNode(pos, end Pos, name string, args []AnnotationArg) Annotation {
	return &ast.Annotation{PosV: pos, EndV: end, Name: name, Args: compactAnnotationArgs(args)}
}

func AnnotationArgNode(pos Pos, key string, value Expr) AnnotationArg {
	return &ast.AnnotationArg{PosV: pos, Key: key, Value: value}
}

func NamedTypeNode(pos, end Pos, path []string, args []Type) Type {
	return &ast.NamedType{PosV: pos, EndV: end, Path: compactStrings(path), Args: compactTypes(args)}
}

func OptionalTypeNode(pos, end Pos, inner Type) Type {
	return &ast.OptionalType{PosV: pos, EndV: end, Inner: inner}
}

func TupleTypeNode(pos, end Pos, elems []Type) Type {
	return &ast.TupleType{PosV: pos, EndV: end, Elems: compactTypes(elems)}
}

func FnTypeNode(pos, end Pos, params []Type, ret Type) Type {
	return &ast.FnType{PosV: pos, EndV: end, Params: compactTypes(params), ReturnType: ret}
}

func BlockNode(pos, end Pos, stmts []Stmt) Block {
	return &ast.Block{PosV: pos, EndV: end, Stmts: compactStmts(stmts)}
}

func BlockAsStmt(b Block) Stmt {
	if b == nil {
		return nil
	}
	return b
}

func BlockAsExpr(b Block) Expr {
	if b == nil {
		return nil
	}
	return b
}

func LetStmtNode(pos, end Pos, pat Pattern, mut bool, mutPos Pos, typ Type, value Expr) Stmt {
	return &ast.LetStmt{PosV: pos, EndV: end, Pattern: pat, Mut: mut, MutPos: mutPos, Type: typ, Value: value}
}

func ReturnStmtNode(pos, end Pos, value Expr) Stmt {
	return &ast.ReturnStmt{PosV: pos, EndV: end, Value: value}
}

func BreakStmtNode(pos, end Pos) Stmt {
	return &ast.BreakStmt{PosV: pos, EndV: end}
}

func ContinueStmtNode(pos, end Pos) Stmt {
	return &ast.ContinueStmt{PosV: pos, EndV: end}
}

func DeferStmtNode(pos, end Pos, x Expr) Stmt {
	return &ast.DeferStmt{PosV: pos, EndV: end, X: x}
}

func ForStmtNode(pos, end Pos, isForLet bool, pat Pattern, iter Expr, body Block) Stmt {
	return &ast.ForStmt{PosV: pos, EndV: end, IsForLet: isForLet, Pattern: pat, Iter: iter, Body: body}
}

func AssignStmtNode(pos, end Pos, op Kind, target Expr, value Expr) Stmt {
	return &ast.AssignStmt{PosV: pos, EndV: end, Op: op, Targets: []ast.Expr{target}, Value: value}
}

func ChanSendStmtNode(pos, end Pos, channel, value Expr) Stmt {
	return &ast.ChanSendStmt{PosV: pos, EndV: end, Channel: channel, Value: value}
}

func ExprStmtNode(x Expr) Stmt {
	if x == nil {
		return nil
	}
	return &ast.ExprStmt{X: x}
}

func IdentExpr(pos, end Pos, name string) Expr {
	return &ast.Ident{PosV: pos, EndV: end, Name: name}
}

func IntLitExpr(pos, end Pos, text string) Expr {
	return &ast.IntLit{PosV: pos, EndV: end, Text: text}
}

func FloatLitExpr(pos, end Pos, text string) Expr {
	return &ast.FloatLit{PosV: pos, EndV: end, Text: text}
}

func BoolLitExpr(pos, end Pos, value bool) Expr {
	return &ast.BoolLit{PosV: pos, EndV: end, Value: value}
}

func CharLitExpr(pos, end Pos, value string) Expr {
	return &ast.CharLit{PosV: pos, EndV: end, Value: firstRune(value)}
}

func ByteLitExpr(pos, end Pos, value string) Expr {
	return &ast.ByteLit{PosV: pos, EndV: end, Value: firstByte(value)}
}

func StringLitFromToken(pos, end Pos, tok Token) Expr {
	return &ast.StringLit{PosV: pos, EndV: end, IsRaw: tok.Kind == token.RAWSTRING, IsTriple: tok.Triple, Parts: stringPartsToAST(tok.Parts)}
}

func StringLitExpr(pos, end Pos, value string) Expr {
	return &ast.StringLit{PosV: pos, EndV: end, Parts: []ast.StringPart{{IsLit: true, Lit: value}}}
}

func UnaryExprNode(pos, end Pos, op Kind, x Expr) Expr {
	return &ast.UnaryExpr{PosV: pos, EndV: end, Op: op, X: x}
}

func BinaryExprNode(pos, end Pos, op Kind, left, right Expr) Expr {
	return &ast.BinaryExpr{PosV: pos, EndV: end, Op: op, Left: left, Right: right}
}

func QuestionExprNode(pos, end Pos, x Expr) Expr {
	return &ast.QuestionExpr{PosV: pos, EndV: end, X: x}
}

func CallExprNode(pos, end Pos, fn Expr, args []Arg) Expr {
	return &ast.CallExpr{PosV: pos, EndV: end, Fn: fn, Args: compactArgs(args)}
}

func FieldExprNode(pos, end Pos, x Expr, name string, optional bool) Expr {
	return &ast.FieldExpr{PosV: pos, EndV: end, X: x, Name: name, IsOptional: optional}
}

func IndexExprNode(pos, end Pos, x, index Expr) Expr {
	return &ast.IndexExpr{PosV: pos, EndV: end, X: x, Index: index}
}

func TurbofishExprNode(pos, end Pos, base Expr, args []Type) Expr {
	return &ast.TurbofishExpr{PosV: pos, EndV: end, Base: base, Args: compactTypes(args)}
}

func RangeExprNode(pos, end Pos, start, stop Expr, inclusive bool) Expr {
	return &ast.RangeExpr{PosV: pos, EndV: end, Start: start, Stop: stop, Inclusive: inclusive}
}

func ParenExprNode(pos, end Pos, x Expr) Expr {
	return &ast.ParenExpr{PosV: pos, EndV: end, X: x}
}

func TupleExprNode(pos, end Pos, elems []Expr) Expr {
	return &ast.TupleExpr{PosV: pos, EndV: end, Elems: compactExprs(elems)}
}

func ListExprNode(pos, end Pos, elems []Expr) Expr {
	return &ast.ListExpr{PosV: pos, EndV: end, Elems: compactExprs(elems)}
}

func MapEntryNode(key, value Expr) MapEntry {
	return &ast.MapEntry{Key: key, Value: value}
}

func MapExprNode(pos, end Pos, entries []MapEntry, empty bool) Expr {
	return &ast.MapExpr{PosV: pos, EndV: end, Entries: compactMapEntries(entries), Empty: empty}
}

func StructLitFieldNode(pos Pos, name string, value Expr) StructLitField {
	return &ast.StructLitField{PosV: pos, Name: name, Value: value}
}

func StructLitNode(pos, end Pos, typ Expr, fields []StructLitField, spread Expr) Expr {
	return &ast.StructLit{PosV: pos, EndV: end, Type: typ, Fields: compactStructLitFields(fields), Spread: spread}
}

func IfExprNode(pos, end Pos, isIfLet bool, pat Pattern, cond Expr, then Block, alt Expr) Expr {
	return &ast.IfExpr{PosV: pos, EndV: end, IsIfLet: isIfLet, Pattern: pat, Cond: cond, Then: then, Else: alt}
}

func MatchArmNode(pos Pos, pat Pattern, guard, body Expr) MatchArm {
	return &ast.MatchArm{PosV: pos, Pattern: pat, Guard: guard, Body: body}
}

func MatchExprNode(pos, end Pos, scrutinee Expr, arms []MatchArm) Expr {
	return &ast.MatchExpr{PosV: pos, EndV: end, Scrutinee: scrutinee, Arms: compactMatchArms(arms)}
}

func ClosureExprNode(pos, end Pos, params []Param, ret Type, body Expr) Expr {
	return &ast.ClosureExpr{PosV: pos, EndV: end, Params: compactParams(params), ReturnType: ret, Body: body}
}

func ArgNode(pos Pos, name string, value Expr) Arg {
	return &ast.Arg{PosV: pos, Name: name, Value: value}
}

func IdentPatNode(pos, end Pos, name string) Pattern {
	return &ast.IdentPat{PosV: pos, EndV: end, Name: name}
}

func WildcardPatNode(pos, end Pos) Pattern {
	return &ast.WildcardPat{PosV: pos, EndV: end}
}

func LiteralPatNode(pos, end Pos, lit Expr) Pattern {
	return &ast.LiteralPat{PosV: pos, EndV: end, Literal: lit}
}

func TuplePatNode(pos, end Pos, elems []Pattern) Pattern {
	return &ast.TuplePat{PosV: pos, EndV: end, Elems: compactPatterns(elems)}
}

func VariantPatNode(pos, end Pos, path []string, args []Pattern) Pattern {
	return &ast.VariantPat{PosV: pos, EndV: end, Path: compactStrings(path), Args: compactPatterns(args)}
}

func StructPatFieldNode(pos Pos, name string, pat Pattern) StructPatField {
	return &ast.StructPatField{PosV: pos, Name: name, Pattern: pat}
}

func StructPatNode(pos, end Pos, typ []string, fields []StructPatField, rest bool) Pattern {
	return &ast.StructPat{PosV: pos, EndV: end, Type: compactStrings(typ), Fields: compactStructPatFields(fields), Rest: rest}
}

func BindingPatNode(pos, end Pos, name string, pat Pattern) Pattern {
	return &ast.BindingPat{PosV: pos, EndV: end, Name: name, Pattern: pat}
}

func RangePatNode(pos, end Pos, start, stop Expr, inclusive bool) Pattern {
	return &ast.RangePat{PosV: pos, EndV: end, Start: start, Stop: stop, Inclusive: inclusive}
}

func OrPatNode(pos, end Pos, alts []Pattern) Pattern {
	return &ast.OrPat{PosV: pos, EndV: end, Alts: compactPatterns(alts)}
}

func ExprPos(e Expr, fallback Pos) Pos {
	if e == nil {
		return fallback
	}
	return e.Pos()
}

func ExprEnd(e Expr, fallback Pos) Pos {
	if e == nil {
		return fallback
	}
	return e.End()
}

func compactDecls(in []Decl) []ast.Decl {
	out := make([]ast.Decl, 0, len(in))
	for _, v := range in {
		if v != nil {
			out = append(out, v)
		}
	}
	return out
}

func compactFnDecls(in []FnDecl) []*ast.FnDecl {
	out := make([]*ast.FnDecl, 0, len(in))
	for _, v := range in {
		if v != nil {
			out = append(out, v)
		}
	}
	return out
}

func compactStmts(in []Stmt) []ast.Stmt {
	out := make([]ast.Stmt, 0, len(in))
	for _, v := range in {
		if v != nil {
			out = append(out, v)
		}
	}
	return out
}

func compactExprs(in []Expr) []ast.Expr {
	out := make([]ast.Expr, 0, len(in))
	for _, v := range in {
		if v != nil {
			out = append(out, v)
		}
	}
	return out
}

func compactTypes(in []Type) []ast.Type {
	out := make([]ast.Type, 0, len(in))
	for _, v := range in {
		if v != nil {
			out = append(out, v)
		}
	}
	return out
}

func compactPatterns(in []Pattern) []ast.Pattern {
	out := make([]ast.Pattern, 0, len(in))
	for _, v := range in {
		if v != nil {
			out = append(out, v)
		}
	}
	return out
}

func compactGenericParams(in []GenericParam) []*ast.GenericParam {
	out := make([]*ast.GenericParam, 0, len(in))
	for _, v := range in {
		if v != nil {
			out = append(out, v)
		}
	}
	return out
}

func compactParams(in []Param) []*ast.Param {
	out := make([]*ast.Param, 0, len(in))
	for _, v := range in {
		if v != nil {
			out = append(out, v)
		}
	}
	return out
}

func compactFields(in []Field) []*ast.Field {
	out := make([]*ast.Field, 0, len(in))
	for _, v := range in {
		if v != nil {
			out = append(out, v)
		}
	}
	return out
}

func compactVariants(in []Variant) []*ast.Variant {
	out := make([]*ast.Variant, 0, len(in))
	for _, v := range in {
		if v != nil {
			out = append(out, v)
		}
	}
	return out
}

func compactAnnotations(in []Annotation) []*ast.Annotation {
	out := make([]*ast.Annotation, 0, len(in))
	for _, v := range in {
		if v != nil {
			out = append(out, v)
		}
	}
	return out
}

func compactAnnotationArgs(in []AnnotationArg) []*ast.AnnotationArg {
	out := make([]*ast.AnnotationArg, 0, len(in))
	for _, v := range in {
		if v != nil {
			out = append(out, v)
		}
	}
	return out
}

func compactArgs(in []Arg) []*ast.Arg {
	out := make([]*ast.Arg, 0, len(in))
	for _, v := range in {
		if v != nil {
			out = append(out, v)
		}
	}
	return out
}

func compactMapEntries(in []MapEntry) []*ast.MapEntry {
	out := make([]*ast.MapEntry, 0, len(in))
	for _, v := range in {
		if v != nil {
			out = append(out, v)
		}
	}
	return out
}

func compactMatchArms(in []MatchArm) []*ast.MatchArm {
	out := make([]*ast.MatchArm, 0, len(in))
	for _, v := range in {
		if v != nil {
			out = append(out, v)
		}
	}
	return out
}

func compactStructLitFields(in []StructLitField) []*ast.StructLitField {
	out := make([]*ast.StructLitField, 0, len(in))
	for _, v := range in {
		if v != nil {
			out = append(out, v)
		}
	}
	return out
}

func compactStructPatFields(in []StructPatField) []*ast.StructPatField {
	out := make([]*ast.StructPatField, 0, len(in))
	for _, v := range in {
		if v != nil {
			out = append(out, v)
		}
	}
	return out
}

func compactStrings(in []string) []string {
	out := make([]string, 0, len(in))
	for _, v := range in {
		if v != "" {
			out = append(out, v)
		}
	}
	return out
}
